// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/core/active-tab.js
// Robust active-tab resolution (3-tier fallback)
// Extracted from js/sidebar.js (lines 3985-4043) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
async function ensureActiveTab() {
  try {
    const queryTabs = async (queryObj) => {
      if (typeof browser !== "undefined" && browser.tabs && browser.tabs.query) {
        try {
          const res = await browser.tabs.query(queryObj);
          return res || [];
        } catch (e) {
          return [];
        }
      }
      if (typeof chrome !== "undefined" && chrome.tabs && chrome.tabs.query) {
        return await new Promise((resolve) => {
          chrome.tabs.query(queryObj, (tabs) => {
            if (chrome.runtime?.lastError) resolve([]);
            else resolve(tabs || []);
          });
        });
      }
      return [];
    };

    const isWebTab = (t) => {
      if (!t || !t.id) return false;
      const u = t.url || "";
      if (u.startsWith("moz-extension://") || u.startsWith("chrome-extension://") || u.startsWith("about:") || u.startsWith("chrome:")) {
        return false;
      }
      return true;
    };

    // 1. Try active tab in current window
    let tabs = await queryTabs({ active: true, currentWindow: true });
    let validTabs = tabs.filter(isWebTab);

    // 2. Try active tab in last focused window (needed when sidebar has focus)
    if (validTabs.length === 0) {
      tabs = await queryTabs({ active: true, lastFocusedWindow: true });
      validTabs = tabs.filter(isWebTab);
    }

    // 3. Fallback: any active tab in any window
    if (validTabs.length === 0) {
      tabs = await queryTabs({ active: true });
      validTabs = tabs.filter(isWebTab);
    }

    const targetTab = validTabs[0] || tabs[0];
    if (targetTab && targetTab.id) {
      activeTabId = targetTab.id;
      return targetTab;
    }
    return null;
  } catch (e) {
    console.warn("ensureActiveTab exception:", e);
  }
  return null;
}

