// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/core/browser.js
// Browser compat layer + unified storage helpers (storGet/storSet/storRemove)
// Extracted from js/sidebar.js (lines 1-68) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// Web Super Assistant - Sidebar Controller
// Controls: Citation Generator, Element Redactor & Blur, Smart Screenshot Engine

// Universal browser/chrome compatibility layer (Firefox 55+ & Chrome/Edge)
// Firefox 55+ supports chrome.* as alias for browser.* in callback style
// This is the official MDN-recommended approach for cross-browser extensions
if (typeof chrome === "undefined" && typeof browser !== "undefined") {
  // On very old Firefox (pre-55) - provide chrome alias
  try { window.chrome = browser; } catch (e) {}
}
const _storLocal = (typeof chrome !== "undefined" && chrome.storage && chrome.storage.local)
  ? chrome.storage.local
  : ((typeof browser !== "undefined" && browser.storage && browser.storage.local)
    ? browser.storage.local : null);

// Universal storage helpers (handles both Promise-style Firefox and callback-style Chrome)
function storGet(key, cb) {
  if (!_storLocal) { if (cb) cb({}); return; }
  try {
    let callbackFired = false;
    const p = _storLocal.get(key, (res) => {
      callbackFired = true;
      if (!p || typeof p.then !== "function") {
        if (cb) cb(res || {});
      }
    });
    if (p && typeof p.then === "function") {
      p.then(res => { if (!callbackFired && cb) cb(res || {}); }).catch(() => { if (!callbackFired && cb) cb({}); });
    }
  } catch (e) {
    try { _storLocal.get(key, (res) => { if (cb) cb(res || {}); }); } catch(err) { if (cb) cb({}); }
  }
}
function storSet(obj, cb) {
  if (!_storLocal) { if (cb) cb(); return; }
  try {
    let callbackFired = false;
    const p = _storLocal.set(obj, () => {
      callbackFired = true;
      if (!p || typeof p.then !== "function") {
        if (cb) cb();
      }
    });
    if (p && typeof p.then === "function") {
      p.then(() => { if (!callbackFired && cb) cb(); }).catch(() => { if (!callbackFired && cb) cb(); });
    }
  } catch (e) {
    try { _storLocal.set(obj, () => { if (cb) cb(); }); } catch(err) { if (cb) cb(); }
  }
}
function storRemove(key, cb) {
  if (!_storLocal) { if (cb) cb(); return; }
  try {
    let callbackFired = false;
    const p = _storLocal.remove(key, () => {
      callbackFired = true;
      if (!p || typeof p.then !== "function") {
        if (cb) cb();
      }
    });
    if (p && typeof p.then === "function") {
      p.then(() => { if (!callbackFired && cb) cb(); }).catch(() => { if (!callbackFired && cb) cb(); });
    }
  } catch (e) {
    try { _storLocal.remove(key, () => { if (cb) cb(); }); } catch(err) { if (cb) cb(); }
  }
}

