// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/core/constants.js
// Shared constants, org detection, author-name cleaning, getI18nText
// Extracted from js/sidebar.js (lines 69-114) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
const getI18nText = (key, params = null) => (window.i18n ? window.i18n.t(key, null, params) : key);

const MONTHS_IEEE = ["", "Jan.", "Feb.", "Mar.", "Apr.", "May", "June", "July", "Aug.", "Sept.", "Oct.", "Nov.", "Dec."];
const MONTHS_FULL = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

function getTodayIeee() {
  const d = new Date();
  return `${MONTHS_IEEE[d.getMonth() + 1] || ""} ${d.getDate()}, ${d.getFullYear()}`;
}

function getTodayApa() {
  const d = new Date();
  return `${MONTHS_FULL[d.getMonth() + 1] || ""} ${d.getDate()}, ${d.getFullYear()}`;
}

const ORG_NAMES = new Set([
  "google", "microsoft", "openai", "meta", "apple", "amazon", "ibm", "intel",
  "the hacker news", "reuters", "bbc", "bbc news", "cnn", "associated press",
  "bloomberg", "techcrunch", "the verge", "wired", "ars technica", "zdnet",
  "vnexpress", "tuổi trẻ", "dân trí", "genk", "bleepingcomputer", "sansec",
  "mozilla", "github", "cloudflare", "ieee", "acm", "nist", "iso", "w3c"
]);
const ORG_KEYWORDS = ["news", "team", "foundation", "institute", "corp", "inc", "llc", "labs", "group", "agency", "editorial"];

const VIETNAMESE_SURNAMES = new Set([
  "nguyễn", "nguyen", "trần", "tran", "lê", "le", "phạm", "pham", "hoàng", "hoang",
  "huỳnh", "huynh", "phan", "vũ", "vu", "võ", "vo", "đặng", "dang", "bùi", "bui",
  "đỗ", "do", "hồ", "ho", "ngô", "ngo", "dương", "duong", "lý", "ly", "đào", "dao",
  "đoàn", "doan", "vương", "vuong", "trịnh", "trinh", "đinh", "dinh", "lâm", "lam",
  "phùng", "phung", "mai", "tô", "to", "hà", "ha", "tạ", "ta", "trương", "truong",
  "quách", "quach", "thân", "than", "tăng", "tang", "la", "lưu", "luu"
]);

function isOrganization(name) {
  if (!name) return false;
  const low = name.trim().toLowerCase();
  if (ORG_NAMES.has(low)) return true;
  return ORG_KEYWORDS.some(k => low === k || low.includes(` ${k}`) || low.includes(`${k} `));
}

function cleanAuthorName(name) {
  if (!name) return "";
  if (typeof name !== "string") {
    if (Array.isArray(name)) name = name.join(", ");
    else name = String(name);
  }
  let s = name.trim();
  if (s.startsWith("http://") || s.startsWith("https://")) return "";
  s = s.replace(/^(by|written by|posted by|author|tác giả|theo|ảnh)\s*[:\-–]?\s*/i, "");
  s = s.replace(/@\w+/g, "");
  s = s.replace(/\s*[-–|]\s*(the hacker news|techcrunch|the verge|reuters|bbc|vnexpress).*$/i, "");
  s = s.replace(/,\s*(phóng viên|biên tập viên|reporter|editor|contributor).*$/i, "");
  s = s.replace(/^[,;\s&]+|[,;\s&]+$/g, "");
  return s.trim();
}

