// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/core/messaging.js
// Content-script injection + safe sendTabMessage (Chrome/Firefox)
// Extracted from js/sidebar.js (lines 4157-4269) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
async function safeSendTabMessage(tabId, message, timeoutMs) {
  if (!tabId) return null;
  const to = Math.min(20000, Math.max(200, Number(timeoutMs) || 800));
  try {
    if (typeof browser !== "undefined" && browser.tabs && browser.tabs.sendMessage) {
      return await Promise.race([
        browser.tabs.sendMessage(tabId, message).catch(() => null),
        new Promise(r => setTimeout(() => r(null), to))
      ]);
    }
    if (typeof chrome !== "undefined" && chrome.tabs && chrome.tabs.sendMessage) {
      return await new Promise((resolve) => {
        let responded = false;
        try {
          chrome.tabs.sendMessage(tabId, message, (res) => {
            responded = true;
            if (chrome.runtime?.lastError) {
              resolve(null);
            } else {
              resolve(res || null);
            }
          });
        } catch (e) {
          resolve(null);
        }
        setTimeout(() => {
          if (!responded) resolve(null);
        }, to);
      });
    }
  } catch (err) {
    return null;
  }
  return null;
}

// Lazy on-demand injection fallback for already open tabs.
// VERIFIED: returns true only if a PING actually gets a pong back after all
// attempts (previously it always returned true, silently masking failures).
async function ensureContentScriptInjected(tabId) {
  if (!tabId) return false;

  const pingNow = () => Promise.race([
    safeSendTabMessage(tabId, { action: "PING" }),
    new Promise(r => setTimeout(() => r(null), 350))
  ]);

  // 1. Already injected?
  const first = await pingNow();
  if (first && first.pong) {
    return true;
  }

  const contentFiles = [
    "OS/js/content/i18n.js",
    "OS/js/content/inspect.js",
    "OS/js/content/snip.js",
    "OS/js/content/scroll.js",
    "OS/js/content/citation.js",
    "OS/js/content/security.js",
    "OS/js/content/social.js",
    "OS/js/content/main.js"
  ];

  // 2. Inject content CSS and modular scripts as fallback (Chrome MV3 / Firefox MV3)
  try {
    const scriptingApi = (typeof chrome !== "undefined" && chrome.scripting)
      ? chrome.scripting
      : ((typeof browser !== "undefined" && browser.scripting) ? browser.scripting : null);

    if (scriptingApi && scriptingApi.executeScript) {
      await scriptingApi.insertCSS({
        target: { tabId },
        files: ["OS/css/content.css"]
      }).catch(() => {});

      await scriptingApi.executeScript({
        target: { tabId },
        files: contentFiles
      }).catch(() => {});

      // Verify the injection actually landed before declaring success.
      await new Promise(r => setTimeout(r, 80));
      for (let i = 0; i < 3; i++) {
        const p = await pingNow();
        if (p && p.pong) return true;
        await new Promise(r => setTimeout(r, 120));
      }
      return false;
    }

    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
    if (tabsApi && tabsApi.executeScript) {
      for (const f of contentFiles) {
        await tabsApi.executeScript(tabId, { file: f }).catch(() => {});
      }
      await new Promise(r => setTimeout(r, 60));
      for (let i = 0; i < 3; i++) {
        const p = await pingNow();
        if (p && p.pong) return true;
        await new Promise(r => setTimeout(r, 120));
      }
      return false;
    }
  } catch (injectErr) {
    console.warn("Script injection fallback error:", injectErr);
  }
  return false;
}

async function sendTabMessage(msg, cb) {
  const tab = await ensureActiveTab();
  if (!tab || !tab.id) {
    if (cb) cb(null);
    return null;
  }

  const restrictedProtocols = ["about:", "chrome:", "edge:", "moz-extension:", "chrome-extension:"];
  if (tab.url && restrictedProtocols.some(p => tab.url.startsWith(p))) {
    if (cb) cb(null);
    return null;
  }

  await ensureContentScriptInjected(tab.id);

  const to = Math.min(20000, Math.max(1200, Number(msg && msg.timeoutMs) || 1200));
  const res = await Promise.race([
    safeSendTabMessage(tab.id, msg, to),
    new Promise(r => setTimeout(() => r(null), to + 150))
  ]);

  if (cb) cb(res);
  return res;
}

