// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/core/messaging.js
// Content-script injection + safe sendTabMessage (Chrome/Firefox)
// Extracted from js/sidebar.js (lines 4157-4269) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
async function safeSendTabMessage(tabId, message) {
  if (!tabId) return null;
  try {
    if (typeof browser !== "undefined" && browser.tabs && browser.tabs.sendMessage) {
      return await browser.tabs.sendMessage(tabId, message).catch(() => null);
    }
    if (typeof chrome !== "undefined" && chrome.tabs && chrome.tabs.sendMessage) {
      return await new Promise((resolve) => {
        let responded = false;
        try {
          chrome.tabs.sendMessage(tabId, message, (res) => {
            responded = true;
            if (chrome.runtime?.lastError) {
              resolve(null);
            } else {
              resolve(res || null);
            }
          });
        } catch (e) {
          resolve(null);
        }
        setTimeout(() => {
          if (!responded) resolve(null);
        }, 800);
      });
    }
  } catch (err) {
    return null;
  }
  return null;
}

// Lazy on-demand injection fallback for already open tabs
async function ensureContentScriptInjected(tabId) {
  if (!tabId) return false;

  // 1. Quick PING with timeout
  const ping = await Promise.race([
    safeSendTabMessage(tabId, { action: "PING" }),
    new Promise(r => setTimeout(() => r(null), 400))
  ]);
  if (ping && ping.pong) {
    return true;
  }

  // 2. Inject content CSS and modular scripts as fallback
  try {
    const scriptingApi = (typeof chrome !== "undefined" && chrome.scripting) 
      ? chrome.scripting 
      : ((typeof browser !== "undefined" && browser.scripting) ? browser.scripting : null);

    const contentFiles = [
      "OS/js/content/i18n.js",
      "OS/js/content/inspect.js",
      "OS/js/content/snip.js",
      "OS/js/content/scroll.js",
      "OS/js/content/citation.js",
      "OS/js/content/main.js"
    ];

    if (scriptingApi && scriptingApi.executeScript) {
      await scriptingApi.insertCSS({
        target: { tabId },
        files: ["OS/css/content.css"]
      }).catch(() => {});

      await scriptingApi.executeScript({
        target: { tabId },
        files: contentFiles
      }).catch(() => {});

      await new Promise(r => setTimeout(r, 60));
      return true;
    }

    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
    if (tabsApi && tabsApi.executeScript) {
      for (const f of contentFiles) {
        await tabsApi.executeScript(tabId, { file: f }).catch(() => {});
      }
      await new Promise(r => setTimeout(r, 60));
      return true;
    }
  } catch (injectErr) {
    console.warn("Script injection fallback error:", injectErr);
  }
  return false;
}

async function sendTabMessage(msg, cb) {
  const tab = await ensureActiveTab();
  if (!tab || !tab.id) {
    if (cb) cb(null);
    return null;
  }

  const restrictedProtocols = ["about:", "chrome:", "edge:", "moz-extension:", "chrome-extension:"];
  if (tab.url && restrictedProtocols.some(p => tab.url.startsWith(p))) {
    if (cb) cb(null);
    return null;
  }

  await ensureContentScriptInjected(tab.id);

  const res = await Promise.race([
    safeSendTabMessage(tab.id, msg),
    new Promise(r => setTimeout(() => r(null), 1200))
  ]);

  if (cb) cb(res);
  return res;
}

