// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/utils/names.js
// Vietnamese diacritic removal + author display-name normalization
// Extracted from js/sidebar.js (lines 139-227) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
function removeVietnameseDiacritics(str) {
  if (!str) return "";
  return str
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D");
}

function normalizeAuthorDisplayName(name) {
  if (!name || typeof name !== "string") return "";
  let s = cleanAuthorName(name);
  if (!s) return "";
  s = s.replace(/,\s*(jr\.?|sr\.?|iii|ii|iv)(?=\s*,|\s*$)/gi, " $1");
  if (s.includes(",")) {
    const p = s.split(",");
    if (p.length === 2) {
      const last = p[0].trim();
      const first = p[1].trim();
      if (last && first) {
        const lastClean = removeVietnameseDiacritics(last).toLowerCase();
        const isVn = VIETNAMESE_SURNAMES.has(last.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastClean);
        return isVn ? `${last} ${first}`.trim() : `${first} ${last}`.trim();
      }
    }
  }
  return s;
}

function normalizeAuthorsString(raw) {
  if (!raw) return "";
  if (Array.isArray(raw)) {
    return raw.map(x => normalizeAuthorDisplayName(typeof x === "string" ? x : (x?.name || ""))).filter(Boolean).join(", ");
  }
  let s = String(raw).trim();
  if (!s) return "";
  
  if (s.includes(";") || s.includes("\n")) {
    const sep = s.includes(";") ? ";" : "\n";
    return s.split(sep)
      .map(part => part.replace(/^\s*(?:and|và|&)\s+/i, "").trim())
      .map(normalizeAuthorDisplayName)
      .filter(Boolean)
      .join(", ");
  }
  
  let cleanStr = s.replace(/\s*&\s*/g, " and ").replace(/\s*&amp;\s*/g, " and ").replace(/\s+và\s+/gi, " and ");
  if (/\s+and\s+/i.test(cleanStr) && !/,\s+and\s+/i.test(cleanStr)) {
    const andParts = cleanStr.split(/\s+and\s+/i);
    if (andParts.length === 2 && !andParts[0].includes(";") && andParts[0].split(",").length <= 2) {
      return andParts.map(normalizeAuthorDisplayName).filter(Boolean).join(", ");
    }
  }
  
  const withCommas = cleanStr.replace(/,\s+and\s+/gi, ", ").replace(/\s+and\s+/gi, ", ").trim();
  const parts = withCommas.split(",").map(p => p.trim()).filter(Boolean);
  if (parts.length <= 1) {
    return normalizeAuthorDisplayName(parts[0] || "");
  }

  if (parts.length === 2) {
    const w0 = parts[0].trim().split(/\s+/).length;
    const w1 = parts[1].trim().split(/\s+/).length;
    if (w0 === 1 || w1 === 1 || /^[A-Z]\.(\s*[A-Z]\.)*$/i.test(parts[1].trim())) {
      return normalizeAuthorDisplayName(parts[0] + ", " + parts[1]);
    }
  }
  
  // Check if parts are Last, First pairs
  let isPairs = parts.length >= 4 && parts.length % 2 === 0;
  if (isPairs) {
    let allHaveMultipleWords = parts.every(p => p.trim().split(/\s+/).length >= 2);
    if (allHaveMultipleWords) {
      const oddAreInitials = parts.filter((_, idx) => idx % 2 === 1).every(p => /^[A-Z]\.(\s*[A-Z]\.)*$/i.test(p.trim()));
      if (!oddAreInitials) isPairs = false;
    }
  }
  
  if (isPairs) {
    const res = [];
    for (let i = 0; i < parts.length; i += 2) {
      res.push(normalizeAuthorDisplayName(parts[i] + ", " + parts[i + 1]));
    }
    return res.filter(Boolean).join(", ");
  }
  
  return parts.map(normalizeAuthorDisplayName).filter(Boolean).join(", ");
}

