// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/editor/notes.js
// Research-notes markdown-lite composer (toolbar, preview, counts)
// Extracted from js/sidebar.js (lines 241-571) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
function getTodayIeee() {
  const d = new Date();
  return `${MONTHS_IEEE[d.getMonth() + 1] || ""} ${d.getDate()}, ${d.getFullYear()}`;
}

function getTodayApa() {
  const d = new Date();
  return `${MONTHS_FULL[d.getMonth() + 1] || ""} ${d.getDate()}, ${d.getFullYear()}`;
}

// // ----------------------------------------------------------------------------
// Citation Formatters & Multi-Author Parsing (IEEE, APA 7th, Harvard, MLA 9th, BibTeX)
// ----------------------------------------------------------------------------
function formatResearchNote(rawNote, lang = "vi", isHtml = false) {
  if (!rawNote) return "";
  let clean = rawNote.trim();
  while (
    (clean.startsWith('"') && clean.endsWith('"')) ||
    (clean.startsWith('“') && clean.endsWith('”')) ||
    (clean.startsWith('«') && clean.endsWith('»'))
  ) {
    clean = clean.slice(1, -1).trim();
  }
  if (!clean) return "";

  const noteLabel = (window.i18n ? window.i18n.t("lbl_notes") : null) || 
    (lang === "en" ? "Research Notes" : (lang === "zh" ? "研究笔记" : (lang === "ja" ? "研究メモ" : (lang === "ru" ? "Заметки к исследованию" : "Ghi chú nghiên cứu"))));

  if (isHtml) {
    const escaped = clean.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
    const rendered = escaped
      .replace(/\*\*\*([^*]+)\*\*\*/g, "<strong><em>$1</em></strong>")
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/\*([^*]+)\*/g, "<em>$1</em>")
      .replace(/`([^`]+)`/g, "<code>$1</code>")
      .replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2">$1</a>')
      .replace(/\n/g, "<br>");
    return `<div style="margin-top:12px; padding-top:8px; border-top:1px dashed rgba(255,255,255,0.15); font-size:11px; line-height:1.55; color:#94a3b8; font-style:italic;"><div style="font-style:normal; font-weight:600; color:#cbd5e1; font-size:10px; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:3px;">${noteLabel}:</div>"${rendered}"</div>`;
  }

  return `\n\n${noteLabel}:\n"${clean}"`;
}

// ---- Notes: markdown-lite renderer (DOM-safe, no innerHTML) ----
function notesAppendInline(parent, text) {
  const tokenRe = /(\*\*\*[^*]+\*\*\*|\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`|\[([^\]]+)\]\(((?:https?:\/\/)[^)\s]+)\))/g;
  let last = 0;
  let m;
  while ((m = tokenRe.exec(text)) !== null) {
    if (m.index > last) parent.appendChild(document.createTextNode(text.slice(last, m.index)));
    const tok = m[0];
    if (tok.length > 6 && tok.slice(0, 3) === "***" && tok.slice(-3) === "***") {
      const s = document.createElement("strong");
      const em = document.createElement("em");
      em.textContent = tok.slice(3, -3);
      s.appendChild(em);
      parent.appendChild(s);
    } else if (tok.length > 4 && tok.slice(0, 2) === "**" && tok.slice(-2) === "**") {
      const s = document.createElement("strong");
      s.textContent = tok.slice(2, -2);
      parent.appendChild(s);
    } else if (tok.length > 2 && tok[0] === "*" && tok.slice(-1) === "*") {
      const s = document.createElement("em");
      s.textContent = tok.slice(1, -1);
      parent.appendChild(s);
    } else if (tok[0] === "`") {
      const s = document.createElement("code");
      s.textContent = tok.slice(1, -1);
      parent.appendChild(s);
    } else if (m[2] !== undefined) {
      const a = document.createElement("a");
      a.href = m[3];
      a.target = "_blank";
      a.rel = "noreferrer";
      a.textContent = m[2];
      parent.appendChild(a);
    }
    last = tokenRe.lastIndex;
  }
  if (last < text.length) parent.appendChild(document.createTextNode(text.slice(last)));
}

function buildNoteMarkdownNode(text) {
  const frag = document.createDocumentFragment();
  const lines = String(text || "").replace(/\r\n/g, "\n").split("\n");
  let i = 0;
  const isUl = function (l) { return /^\s*[-*]\s+/.test(l); };
  const isOl = function (l) { return /^\s*\d+[.)]\s+/.test(l); };
  const isHead = function (l) { return /^#{1,3}\s+/.test(l); };
  while (i < lines.length) {
    if (!lines[i].trim()) { i++; continue; }
    const line = lines[i];
    if (isUl(line)) {
      const ul = document.createElement("ul");
      while (i < lines.length && isUl(lines[i])) {
        const li = document.createElement("li");
        notesAppendInline(li, lines[i].replace(/^\s*[-*]\s+/, ""));
        ul.appendChild(li);
        i++;
      }
      frag.appendChild(ul);
    } else if (isOl(line)) {
      const ol = document.createElement("ol");
      while (i < lines.length && isOl(lines[i])) {
        const li = document.createElement("li");
        notesAppendInline(li, lines[i].replace(/^\s*\d+[.)]\s+/, ""));
        ol.appendChild(li);
        i++;
      }
      frag.appendChild(ol);
    } else if (isHead(line)) {
      const h = document.createElement("div");
      h.style.fontWeight = "800";
      h.style.color = "#e2e8f0";
      h.style.marginBottom = "3px";
      h.textContent = line.replace(/^#{1,3}\s+/, "");
      frag.appendChild(h);
      i++;
    } else {
      const p = document.createElement("div");
      notesAppendInline(p, line);
      frag.appendChild(p);
      i++;
    }
  }
  return frag;
}

function notesSelRange(field) {
  let s = field.dataset.selStart;
  let e = field.dataset.selEnd;
  if (s === undefined || e === undefined || s === "" ) {
    s = field.selectionStart || 0;
    e = field.selectionEnd || 0;
  }
  s = parseInt(s, 10) || 0;
  e = parseInt(e, 10) || 0;
  if (s > e) { const t = s; s = e; e = t; }
  return [s, e];
}

function notesTrackSelection() {
  const field = document.getElementById("f-notes");
  if (!field) return;
  field.dataset.selStart = String(field.selectionStart || 0);
  field.dataset.selEnd = String(field.selectionEnd || 0);
}

function notesUnwrapSize(selected, marker) {
  if (!selected.startsWith(marker) || !selected.endsWith(marker)) return 0;
  const isTriple = selected.startsWith("***") && selected.endsWith("***");
  if (marker === "**") return 2;
  if (selected.startsWith("**") || selected.endsWith("**")) {
    return isTriple ? 1 : 0;
  }
  return 1;
}

function notesToggleInline(field, marker) {
  if (!field) return;
  const [start, end] = notesSelRange(field);
  const val = field.value;
  const selected = val.slice(start, end);
  const mlen = marker.length;
  if (!selected) {
    const ins = marker + marker;
    field.value = val.slice(0, start) + ins + val.slice(end);
    field.focus();
    field.setSelectionRange(start + mlen, start + mlen);
    return;
  }
  const strip = notesUnwrapSize(selected, marker);
  const content = strip ? selected.slice(strip, selected.length - strip) : marker + selected + marker;
  field.value = val.slice(0, start) + content + val.slice(end);
  field.focus();
  field.setSelectionRange(start + strip, start + content.length);
}

function notesInsertLink(field) {
  if (!field) return;
  const [start, end] = notesSelRange(field);
  const val = field.value;
  const selected = val.slice(start, end);
  const linkRe = /^\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)$/;
  if (selected && linkRe.test(selected)) {
    const inner = selected.replace(linkRe, "$1");
    field.value = val.slice(0, start) + inner + val.slice(end);
    field.focus();
    field.setSelectionRange(start, start + inner.length);
    return;
  }
  if (!selected) {
    const ph = "[tiêu đề link](https://)";
    field.value = val.slice(0, start) + ph + val.slice(end);
    field.focus();
    field.setSelectionRange(start + 1, start + 1 + "tiêu đề link".length);
    return;
  }
  const wrapped = "[" + selected + "](https://)";
  field.value = val.slice(0, start) + wrapped + val.slice(end);
  field.focus();
  const urlStart = start + selected.length + 3;
  const urlEnd = urlStart + "https://".length;
  field.setSelectionRange(urlStart, urlEnd);
}

function notesToggleLinePrefix(field, prefix) {
  if (!field) return;
  const start = field.selectionStart || 0;
  const end = field.selectionEnd || 0;
  const val = field.value;
  const lineStart = val.lastIndexOf("\n", start - 1) + 1;
  const nextNl = val.indexOf("\n", end);
  const lineEnd = nextNl === -1 ? val.length : nextNl;
  const selBlock = val.slice(lineStart, lineEnd);
  if (selBlock.split("\n").some(function (l) { return l.indexOf(prefix) === 0; })) {
    field.value = val.slice(0, lineStart) + selBlock.split("\n").map(function (l) {
      return l.indexOf(prefix) === 0 ? l.slice(prefix.length) : l;
    }).join("\n") + val.slice(lineEnd);
    field.setSelectionRange(Math.max(lineStart, start - prefix.length), lineEnd);
  } else {
    field.value = val.slice(0, lineStart) + prefix + selBlock.replace(/\n/g, "\n" + prefix) + val.slice(lineEnd);
    field.setSelectionRange(lineStart + prefix.length, lineEnd + prefix.length);
  }
  field.focus();
}

function notesAutoResize() {
  const field = document.getElementById("f-notes");
  if (!field) return;
  field.style.height = "auto";
  field.style.height = Math.min(Math.max(field.scrollHeight, 44), 220) + "px";
}

function notesUpdateCount() {
  const field = document.getElementById("f-notes");
  const counter = document.getElementById("notes-count");
  if (field && counter) {
    const len = field.value.length;
    counter.textContent = len > 0
      ? (window.i18n ? window.i18n.t("notes_count", null, { count: len }) : len + " ký tự")
      : "";
  }
}

function notesUpdatePreview() {
  const field = document.getElementById("f-notes");
  const preview = document.getElementById("notes-preview");
  const btn = document.querySelector('.notes-tool-btn[data-md="preview"]');
  if (!field || !preview || !btn) return;
  const on = preview.style.display !== "none";
  if (on && preview.classList.contains("notes-preview")) {
    preview.textContent = "";
    const words = field.value.trim();
    if (!words) {
      const empty = document.createElement("div");
      empty.className = "cal-empty";
      empty.textContent = window.i18n ? window.i18n.t("notes_preview_empty") : "Ghi chú trống";
      preview.appendChild(empty);
    } else {
      preview.appendChild(buildNoteMarkdownNode(words));
    }
  }
}

function notesInitToolbar() {
  const toolbar = document.getElementById("notes-toolbar");
  const field = document.getElementById("f-notes");
  if (!toolbar || !field) return;
  if (toolbar.dataset.bound) return;
  toolbar.dataset.bound = "1";

  ["select", "keyup", "mouseup", "click", "focus"].forEach(function (evt) {
    field.addEventListener(evt, notesTrackSelection);
  });

  toolbar.querySelectorAll(".notes-tool-btn").forEach(function (btn) {
    btn.addEventListener("click", function (ev) {
      ev.preventDefault();
      const md = btn.getAttribute("data-md");
      if (md === "bold") {
        notesToggleInline(field, "**");
      } else if (md === "italic") {
        notesToggleInline(field, "*");
      } else if (md === "link") {
        notesInsertLink(field);
      } else if (md === "list") {
        notesToggleLinePrefix(field, "- ");
      } else if (md === "preview") {
        const preview = document.getElementById("notes-preview");
        const on = preview.style.display !== "none";
        preview.style.display = on ? "none" : "block";
        btn.classList.toggle("active", !on);
        btn.setAttribute("aria-pressed", on ? "false" : "true");
        const span = btn.querySelector("span");
        if (span) {
          span.textContent = window.i18n ? window.i18n.t(!on ? "notes_preview_hide" : "notes_preview_btn") : (!on ? "Ẩn" : "Xem");
        }
        notesUpdatePreview();
      }
      updateNotesClearButton();
      notesUpdateCount();
      notesAutoResize();
      syncMetaFromInputs();
    });
  });

  field.addEventListener("keydown", function (e) {
    const mod = e.ctrlKey || e.metaKey;
    if (mod && (e.key === "b" || e.key === "B")) {
      e.preventDefault();
      notesToggleInline(field, "**");
      updateNotesClearButton();
      syncMetaFromInputs();
    } else if (mod && (e.key === "i" || e.key === "I")) {
      e.preventDefault();
      notesToggleInline(field, "*");
      updateNotesClearButton();
      syncMetaFromInputs();
    }
  });

  field.addEventListener("input", function () {
    notesAutoResize();
    notesUpdateCount();
    notesUpdatePreview();
  });
  notesAutoResize();
  notesUpdateCount();
}

