// ---------------------------------------------------------------------------
// ScholarFlow i18n unification - generate_content_i18n.js
// Regenerates OS/js/content/i18n.js from the single source of truth,
// OS/locales/{vi,en,zh,ru,ja}.js (content_* namespace keys).
//
// Content scripts run in an isolated world and cannot load the locale files,
// so this checked-in artifact keeps them in sync with the locale dumps.
//
// Usage: node scripts/i18n/generate_content_i18n.js [--verify]
//   (default)  - regenerate OS/js/content/i18n.js
//   --verify   - compare generated bytes with the checked-in file, no write.
// Exit 0 = ok, 1 = error (or drift detected in --verify mode).
// ---------------------------------------------------------------------------

"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("node:vm");

const ROOT = path.resolve(__dirname, "..", "..");
const LANGS = ["vi", "en", "zh", "ru", "ja"];
const OUT = path.join(ROOT, "OS", "js", "content", "i18n.js");
const MANIFEST = path.join(__dirname, "namespace_manifest.json");

function readUtf8(p) {
  return fs.readFileSync(p, "utf8");
}

function loadLocale(lang) {
  const code = readUtf8(path.join(ROOT, "OS", "locales", lang + ".js"));
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, { filename: lang + ".js" });
  return sandbox.window["I18N_" + lang.toUpperCase()];
}

function generate() {
  let contentKeys = null;
  const perLang = {};
  for (const lang of LANGS) {
    const raw = loadLocale(lang);
    const dict = {};
    for (const [k, v] of Object.entries(raw)) {
      if (k.startsWith("content_")) dict[k.slice("content_".length)] = v;
    }
    if (!contentKeys) contentKeys = Object.keys(dict);
    else if (JSON.stringify(Object.keys(dict)) !== JSON.stringify(contentKeys)) {
      throw new Error(`content_* key parity broken in ${lang}.js`);
    }
    perLang[lang] = dict;
  }

  const lines = [];
  lines.push("// ---------------------------------------------------------------------------");
  lines.push("// ScholarFlow in-page content-script i18n (GENERATED)");
  lines.push("// Regenerate with: node scripts/i18n/generate_content_i18n.js");
  lines.push("// Source of truth  : OS/locales/*.js (content_* keys)");
  lines.push("// Do NOT edit manually - manual edits are overwritten on regeneration.");
  lines.push("// ---------------------------------------------------------------------------");
  lines.push("");
  lines.push("");
  lines.push("  let currentAppLang = \"vi\";");
  lines.push("  try {");
  lines.push("    const storageApi = (typeof browser !== \"undefined\" && browser.storage) ? browser.storage : chrome.storage;");
  lines.push("    if (storageApi && storageApi.local) {");
  lines.push("      storageApi.local.get(\"app_language\", (res) => {");
  lines.push("        if (res && res.app_language) {");
  lines.push("          currentAppLang = res.app_language;");
  lines.push("        }");
  lines.push("      });");
  lines.push("      if (storageApi.onChanged) {");
  lines.push("        storageApi.onChanged.addListener((changes, area) => {");
  lines.push("          if (area === \"local\" && changes.app_language) {");
  lines.push("            currentAppLang = changes.app_language.newValue || \"vi\";");
  lines.push("          }");
  lines.push("        });");
  lines.push("      }");
  lines.push("    }");
  lines.push("  } catch (e) {}");
  lines.push("");
  lines.push("  const CONTENT_I18N = {");
  for (const lang of LANGS) {
    lines.push(`    ${lang}: {`);
    for (const key of contentKeys) {
      lines.push(`      ${key}: ${JSON.stringify(perLang[lang][key])},`);
    }
    lines.push("    },");
  }
  lines.push("  };");
  lines.push("");
  lines.push("  function tContent(key, ...args) {");
  lines.push("    try {");
  lines.push("      const dict = (CONTENT_I18N && (CONTENT_I18N[currentAppLang] || CONTENT_I18N.vi)) || {};");
  lines.push("      const val = dict[key] || (CONTENT_I18N && CONTENT_I18N.vi ? CONTENT_I18N.vi[key] : \"\") || \"\";");
  lines.push("      if (typeof val === \"function\") return val(...args);");
  lines.push("      if (typeof val !== \"string\") return String(val);");
  lines.push("      let out = val;");
  lines.push("      for (let i = 0; i < args.length && i < 10; i++) {");
  lines.push("        if (args[i] !== undefined && args[i] !== null) {");
  lines.push("          out = out.split(\"{\" + i + \"}\").join(String(args[i]));");
  lines.push("        }");
  lines.push("      }");
  lines.push("      return out;");
  lines.push("    } catch (e) {");
  lines.push("      return \"\";");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  function notifySidebar(msg) {");
  lines.push("    const runtimeApi = (typeof browser !== \"undefined\" && browser.runtime) ? browser.runtime");
  lines.push("      : ((typeof chrome !== \"undefined\" && chrome.runtime) ? chrome.runtime : null);");
  lines.push("    if (runtimeApi && runtimeApi.sendMessage) {");
  lines.push("      try {");
  lines.push("        const p = runtimeApi.sendMessage(msg);");
  lines.push("        if (p && typeof p.catch === \"function\") p.catch(() => {});");
  lines.push("      } catch (e) {}");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  window.CONTENT_I18N = CONTENT_I18N;");
  lines.push("  window.tContent = tContent;");
  lines.push("  window.notifySidebar = notifySidebar;");
  return lines.join("\n") + "\n";
}

try {
  if (fs.existsSync(MANIFEST)) {
    const manifest = JSON.parse(readUtf8(MANIFEST));
    const expected = manifest.content;
    const probe = loadLocale("vi");
    const actual = Object.keys(probe)
      .filter((k) => k.startsWith("content_"))
      .map((k) => k.slice("content_".length))
      .sort();
    if (JSON.stringify(actual) !== JSON.stringify([...expected].sort())) {
      throw new Error(
        "content_* keys in locale files do not match namespace_manifest.json - run merge_namespaces.js first"
      );
    }
  }

  const out = generate();
  const args = process.argv.slice(2);
  if (args.includes("--verify")) {
    const cur = fs.existsSync(OUT) ? readUtf8(OUT) : null;
    if (cur === out) {
      console.log("[generate] VERIFY OK - OS/js/content/i18n.js is in sync");
      process.exit(0);
    }
    console.error("[generate] VERIFY FAIL - OS/js/content/i18n.js is out of sync (run without --verify)");
    process.exit(1);
  }

  fs.writeFileSync(OUT, out);
  console.log("[generate] OS/js/content/i18n.js regenerated");
  console.log("[generate] OK");
  process.exit(0);
} catch (e) {
  console.error("[generate] FAIL: " + e.message);
  process.exit(1);
}