// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/tabs/calendar.js
// Calendar (ICS subscription) module incl. manual events
// Extracted from js/sidebar.js (lines 7494-8530) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Calendar (ICS subscription) module
// ----------------------------------------------------------------------------
let calFeeds = [];
let calData = {};
let calViewYear = 0;
let calViewMonth = 0;
let calSelectedKey = "";
let calFeedsLoaded = false;
let calViewMode = "month"; // "month" | "week" | "list"
let calViewFocusKey = "";  // anchor date key for week/list navigation
let calHiddenFeedIds = []; // feed ids hidden from calendar
const CAL_PALETTE = ["#38bdf8", "#818cf8", "#34d399", "#fbbf24", "#f472b6", "#a78bfa", "#22d3ee", "#fb923c"];
const CAL_PICKER_PALETTE = ["#ef4444", "#fb923c", "#facc15", "#a3e635", "#22c55e", "#14b8a6", "#06b6d4", "#3b82f6", "#6366f1", "#8b5cf6", "#d946ef", "#ec4899"];
const CAL_MONTHS = {
  vi: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
  en: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  zh: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
  ru: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
  ja: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"]
};
const CAL_WEEKDAY_DOW = {
  vi: ["T2", "T3", "T4", "T5", "T6", "T7", "CN"],
  en: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  zh: ["一", "二", "三", "四", "五", "六", "日"],
  ru: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
  ja: ["月", "火", "水", "木", "金", "土", "日"]
};
const CAL_WEEKDAY_FULL = {
  vi: ["Chủ Nhật", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  en: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  zh: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
  ru: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
  ja: ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"]
};

function calPad2(n) { return n < 10 ? "0" + n : "" + n; }
function calDateKey(d) { return d.getFullYear() + "-" + calPad2(d.getMonth() + 1) + "-" + calPad2(d.getDate()); }
function calParseKey(k) { const p = k.split("-"); return [parseInt(p[0], 10), parseInt(p[1], 10), parseInt(p[2], 10)]; }
function calTodayKey() { return calDateKey(new Date()); }
function calFeedColor(i) {
  if (i === 0) {
    try {
      var p = (getComputedStyle(document.documentElement).getPropertyValue('--primary') || '').trim();
      if (p && p.startsWith('#')) return p;
      var rgb = (getComputedStyle(document.documentElement).getPropertyValue('--primary-rgb') || '').trim();
      if (rgb) {
        var parts = rgb.split(',').map(function (n) { return parseInt(n.trim(), 10); });
        if (parts.length === 3 && !isNaN(parts[0])) {
          return '#' + parts.map(function (x) { return x.toString(16).padStart(2, '0'); }).join('');
        }
      }
    } catch (e) {}
  }
  return CAL_PALETTE[i % CAL_PALETTE.length];
}
function calMonthArr(lang) { return CAL_MONTHS[lang] || CAL_MONTHS.en; }
function calDowArr(lang) { return CAL_WEEKDAY_DOW[lang] || CAL_WEEKDAY_DOW.en; }
function calDowFullArr(lang) { return CAL_WEEKDAY_FULL[lang] || CAL_WEEKDAY_FULL.en; }

function calLoad() {
  storGet("sf_cal", (res) => {
    const data = res && res.sf_cal ? res.sf_cal : {};
    calFeeds = Array.isArray(data.feeds) ? data.feeds : [];
    calData = data.events && typeof data.events === "object" ? data.events : {};
    calHiddenFeedIds = Array.isArray(data.hidden) ? data.hidden : [];
    if (!calViewYear) {
      const now = new Date();
      calViewYear = now.getFullYear();
      calViewMonth = now.getMonth();
    }
    if (!calSelectedKey) calSelectedKey = calTodayKey();
    if (!calViewFocusKey) calViewFocusKey = calSelectedKey;
    calRenderCalendar();
    calRenderFeedList();
  });
}

function calPersist() {
  storSet({ sf_cal: { feeds: calFeeds, events: calData, hidden: calHiddenFeedIds } });
}

function calUnfoldIcs(text) {
  return text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n")
    .reduce(function (acc, line) {
      if ((line[0] === " " || line[0] === "\t") && acc.length) {
        acc[acc.length - 1] += line.slice(1).trimEnd();
      } else if (line.trim()) {
        acc.push(line.trim());
      }
      return acc;
    }, []);
}

function calParseDtValue(value, allDay) {
  if (allDay) {
    const m = /^(\d{4})(\d{2})(\d{2})$/.exec(value);
    return m ? { key: m[1] + "-" + m[2] + "-" + m[3], time: null } : null;
  }
  let date = null;
  if (/Z$/.test(value)) {
    const m = /^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/.exec(value);
    if (m) date = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]));
  } else {
    const m = /^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})$/.exec(value);
    if (m) date = new Date(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]);
  }
  if (!date || isNaN(date.getTime())) return null;
  return { key: calDateKey(date), time: calPad2(date.getHours()) + ":" + calPad2(date.getMinutes()) };
}

function calNormalizeEvent(e) {
  const start = calParseDtValue(e.dtstart, !!e.allday);
  if (!start) return null;
  let end = null;
  if (e.dtend) end = calParseDtValue(e.dtend, !!e.allday);
  if (end && end.key === start.key && (!end.time || end.time === start.time)) end = null;
  return {
    uid: e.uid || "",
    summary: (e.summary || "").replace(/\\,/g, ",").trim() || "(No title)",
    location: e.location || "",
    description: (e.description || "").replace(/\\n/g, " ").replace(/\\,/g, ",").slice(0, 200),
    url: e.url || "",
    start: start,
    end: end,
    allDay: !!e.allday,
    rrule: (e.rrule || "").replace(/\\n/g, "")
  };
}

function calParseIcs(text) {
  const lines = calUnfoldIcs(text);
  const events = [];
  let cur = null;
  let inSubComponent = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const ci = line.indexOf(":");
    if (ci === -1) continue;
    const nameRaw = line.slice(0, ci);
    const value = line.slice(ci + 1).trim();
    const name = nameRaw.split(";")[0].toUpperCase();
    const isDate = /;VALUE=DATE$/i.test(nameRaw);
    if (name === "BEGIN") {
      if (value.toUpperCase() === "VEVENT") {
        cur = { dtstart: "", dtend: "", allday: false, summary: "", location: "", description: "", url: "", uid: "", rrule: "" };
        inSubComponent = false;
      } else if (cur) {
        inSubComponent = true;
      }
    } else if (name === "END") {
      if (value.toUpperCase() === "VEVENT") {
        if (cur) events.push(cur);
        cur = null;
        inSubComponent = false;
      } else if (inSubComponent) {
        inSubComponent = false;
      }
    } else if (cur && !inSubComponent) {
      if (name === "SUMMARY") cur.summary = value;
      else if (name === "LOCATION") cur.location = value;
      else if (name === "DESCRIPTION") cur.description = value;
      else if (name === "URL") cur.url = value;
      else if (name === "UID") cur.uid = value;
      else if (name === "RRULE") cur.rrule = value;
      else if (name === "DTSTART") { cur.dtstart = value; if (isDate) cur.allday = true; }
      else if (name === "DTEND") { cur.dtend = value; if (isDate) cur.allday = true; }
    }
  }
  return events.map(calNormalizeEvent).filter(function (e) { return e !== null; });
}

function calOccurrencesInRange(ev, rangeStartKey, rangeEndKey) {
  const out = [];
  const s = calParseKey(ev.start.key);
  const startDate = new Date(s[0], s[1] - 1, s[2]);
  const ms = calParseKey(rangeStartKey);
  const me = calParseKey(rangeEndKey);
  const rangeStartMs = new Date(ms[0], ms[1] - 1, ms[2]).getTime();
  const rangeEndMs = new Date(me[0], me[1] - 1, me[2]).getTime();

  if (!ev.rrule) {
    const startMs = startDate.getTime();
    let endMs = startMs + 86400000;
    if (ev.end) {
      const e = calParseKey(ev.end.key);
      const eDate = new Date(e[0], e[1] - 1, e[2]);
      endMs = eDate.getTime() + 86400000;
    }
    if (endMs <= startMs) endMs = startMs + 86400000;
    for (let t = startMs; t < endMs; t += 86400000) {
      const d = new Date(t);
      const k = calDateKey(d);
      if (k < rangeStartKey || k > rangeEndKey) continue;
      out.push({ ev: ev, key: k, feedIndex: -1 });
    }
    return out;
  }

  const parts = {};
  ev.rrule.split(";").forEach(function (p) {
    const i = p.indexOf("=");
    if (i > -1) parts[p.slice(0, i).toUpperCase()] = p.slice(i + 1);
  });
  const freq = (parts.FREQ || "").toUpperCase();
  const interval = Math.max(1, parseInt(parts.INTERVAL, 10) || 1);
  let untilMs = rangeEndMs;
  if (parts.UNTIL) {
    const um = /^(\d{4})(\d{2})(\d{2})/.exec(parts.UNTIL);
    if (um) {
      const u = new Date(+um[1], +um[2] - 1, +um[3]);
      u.setDate(u.getDate() + 1);
      untilMs = Math.min(untilMs, u.getTime());
    }
  }
  const countMax = parseInt(parts.COUNT, 10) || Infinity;
  const dowMap = { SU: 0, MO: 1, TU: 2, WE: 3, TH: 4, FR: 5, SA: 6 };
  let dows = null;
  if (parts.BYDAY) {
    dows = new Set();
    parts.BYDAY.split(",").forEach(function (d) {
      const m = /([A-Z]{2})$/.exec(d);
      if (m && dowMap[m[1]] !== undefined) dows.add(dowMap[m[1]]);
    });
    if (!dows.size) dows = null;
  }

  if (freq === "DAILY") {
    let cur = new Date(Math.max(startDate.getTime(), rangeStartMs - 366 * 86400000));
    let count = 0;
    while (cur.getTime() <= untilMs) {
      const diff = Math.round((cur.getTime() - startDate.getTime()) / 86400000);
      if (diff >= 0 && (diff % interval) === 0) {
        count++;
        if (count > countMax) break;
        if (cur.getTime() >= rangeStartMs && cur.getTime() <= rangeEndMs) out.push({ ev: ev, key: calDateKey(cur) });
      }
      cur.setDate(cur.getDate() + 1);
    }
  } else if (freq === "MONTHLY") {
    const dom = startDate.getDate();
    let curY = s[0];
    let curM = s[1] - 1;
    let count = 0;
    let guard = 0;
    while (guard++ < 2400) {
      if (new Date(curY, curM, 1).getTime() > untilMs) break;
      const diff = (curY - s[0]) * 12 + (curM - (s[1] - 1));
      if (diff >= 0 && (diff % interval) === 0) {
        count++;
        if (count > countMax) break;
        const lastDay = new Date(curY, curM + 1, 0).getDate();
        const occDate = new Date(curY, curM, Math.min(dom, lastDay));
        if (occDate.getTime() >= rangeStartMs && occDate.getTime() <= rangeEndMs) out.push({ ev: ev, key: calDateKey(occDate) });
      }
      curM = curM === 11 ? 0 : curM + 1;
      if (curM === 0) curY++;
    }
  } else if (freq === "YEARLY") {
    let curY = s[0];
    const lastDay = new Date(curY, s[1], 0).getDate();
    const dom = Math.min(s[2], lastDay);
    let count = 0;
    let guard = 0;
    while (guard++ < 2400) {
      if (new Date(curY, s[1] - 1, 1).getTime() > untilMs) break;
      const diff = curY - s[0];
      if (diff >= 0 && (diff % interval) === 0) {
        count++;
        if (count > countMax) break;
        const occDate = new Date(curY, s[1] - 1, dom);
        if (occDate.getTime() >= rangeStartMs && occDate.getTime() <= rangeEndMs) out.push({ ev: ev, key: calDateKey(occDate) });
      }
      curY++;
    }
  } else {
    const weekTarget = dows ? dows : new Set([startDate.getDay()]);
    let cur = new Date(startDate);
    let count = 0;
    while (cur.getTime() <= untilMs) {
      const diff = Math.round((cur.getTime() - startDate.getTime()) / 86400000);
      const weekIdx = Math.floor(diff / 7);
      if (diff >= 0 && (weekIdx % interval) === 0 && weekTarget.has(cur.getDay())) {
        if (cur.getTime() >= rangeStartMs) {
          count++;
          if (count > countMax) break;
          if (cur.getTime() <= rangeEndMs) out.push({ ev: ev, key: calDateKey(cur) });
        }
      }
      cur.setDate(cur.getDate() + 1);
    }
  }
  return out;
}

function calBuildMap(startKey, endKey) {
  const dayMap = {};
  calFeeds.forEach(function (feed, feedIndex) {
    if (calHiddenFeedIds.indexOf(feed.id) !== -1) return;
    const list = calData[feed.id];
    if (!Array.isArray(list)) return;
    const feedColor = feed.color || calFeedColor(feedIndex);
    list.forEach(function (ev) {
      const color = ev.color || feedColor;
      calOccurrencesInRange(ev, startKey, endKey).forEach(function (occ) {
        const idx = occ.feedIndex < 0 ? feedIndex : occ.feedIndex;
        if (!dayMap[occ.key]) dayMap[occ.key] = [];
        dayMap[occ.key].push({ ev: ev, feedIndex: idx, color: color, key: occ.key });
      });
    });
  });
  for (const k in dayMap) {
    dayMap[k].sort(function (a, b) {
      const ta = a.ev.allDay ? "00:00" : (a.ev.start.time || "00:00");
      const tb = b.ev.allDay ? "00:00" : (b.ev.start.time || "00:00");
      return ta < tb ? -1 : (ta > tb ? 1 : 0);
    });
  }
  return dayMap;
}

function calBuildMonth() {
  const first = new Date(calViewYear, calViewMonth, 1);
  const days = new Date(calViewYear, calViewMonth + 1, 0).getDate();
  const monthStartKey = calDateKey(first);
  const monthEndKey = calDateKey(new Date(calViewYear, calViewMonth, days));
  const dayMap = calBuildMap(monthStartKey, monthEndKey);
  return { first: first, days: days, monthStartKey: monthStartKey, dayMap: dayMap };
}

// ---- View navigation helpers ----
function calSyncFocusToView() {
  const p = calParseKey(calViewFocusKey || calTodayKey());
  calViewYear = p[0];
  calViewMonth = p[1] - 1;
}
function calSetFocusToMonth() {
  calViewFocusKey = calViewYear + "-" + calPad2(calViewMonth + 1) + "-01";
}
function calMondayOf(d) {
  const x = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const dow = (x.getDay() + 6) % 7;
  x.setDate(x.getDate() - dow);
  return x;
}
function calShiftFocus(days) {
  const p = calParseKey(calViewFocusKey || calTodayKey());
  const d = new Date(p[0], p[1] - 1, p[2]);
  d.setDate(d.getDate() + days);
  calViewFocusKey = calDateKey(d);
  calSyncFocusToView();
}
function calMonthLabelText() {
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  const mArr = calMonthArr(lang);
  return mArr[calViewMonth] + " " + calViewYear;
}
function calWeekLabelText() {
  const p = calParseKey(calViewFocusKey || calTodayKey());
  const start = calMondayOf(new Date(p[0], p[1] - 1, p[2]));
  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  const mArr = calMonthArr(lang);
  const sDay = mArr[start.getMonth()] + " " + start.getDate();
  const eDay = mArr[end.getMonth()] + " " + end.getDate() + ", " + end.getFullYear();
  return (sDay === eDay) ? sDay : sDay + " – " + eDay;
}
function calSyncViewButtons() {
  document.querySelectorAll(".cal-view-btn").forEach(function (btn) {
    btn.classList.toggle("active", btn.getAttribute("data-mode") === calViewMode);
  });
}

// ---- Event row builder (day panel + list view) ----
function calEventTimeRange(ev) {
  if (ev.allDay) return "ALL DAY";
  const s = ev.start.time || "";
  const e = ev.end ? ev.end.time : "";
  if (s && e && e !== s) return s + " – " + e;
  return s || "";
}

function calEventTooltip(ev) {
  const parts = [ev.summary];
  if (ev.location) parts.push("Vị trí: " + ev.location);
  if (ev.description) parts.push(ev.description);
  if (ev.url) parts.push(ev.url);
  return parts.join(" | ");
}

function calExtractMeetingInfo(ev) {
  if (!ev) return null;
  const sources = [ev.location, ev.url, ev.description].filter(Boolean);
  if (!sources.length) return null;
  const text = sources.join(" ");

  const patterns = [
    { type: "meet", name: "Google Meet", regex: /https?:\/\/meet\.google\.com\/[a-z0-9\-]+/i },
    { type: "zoom", name: "Zoom", regex: /https?:\/\/[a-zA-Z0-9.\-_]*zoom\.us\/(?:j|my)\/[a-zA-Z0-9?=_/-]+/i },
    { type: "teams", name: "MS Teams", regex: /https?:\/\/teams\.(?:microsoft|live)\.com\/[^\s"'>]+/i },
    { type: "discord", name: "Discord", regex: /https?:\/\/(?:discord\.gg|discord\.com\/(?:channels|invite))\/[^\s"'>]+/i },
    { type: "skype", name: "Skype", regex: /https?:\/\/join\.skype\.com\/[a-zA-Z0-9]+/i },
    { type: "webex", name: "Webex", regex: /https?:\/\/[a-zA-Z0-9.\-_]*webex\.com\/[^\s"'>]+/i },
    { type: "jitsi", name: "Jitsi", regex: /https?:\/\/meet\.jit\.si\/[^\s"'>]+/i }
  ];

  for (let i = 0; i < patterns.length; i++) {
    const p = patterns[i];
    const m = p.regex.exec(text);
    if (m) {
      return {
        type: p.type,
        name: p.name,
        url: m[0]
      };
    }
  }
  return null;
}

function calGetMeetingStatus(item) {
  if (!item || !item.ev) return { status: "none", label: "" };
  const ev = item.ev;
  const now = new Date();
  const todayKey = calTodayKey();
  const dateKey = item.key || (ev.start ? ev.start.key : todayKey);

  if (ev.allDay) {
    if (dateKey === todayKey) {
      return {
        status: "live",
        label: window.i18n ? window.i18n.t("cal_meeting_live") : "🟢 Đang diễn ra"
      };
    }
    return {
      status: dateKey > todayKey ? "upcoming" : "passed",
      label: ""
    };
  }

  const p = calParseKey(dateKey);
  let sh = 0;
  let sm = 0;
  if (ev.start && ev.start.time) {
    const tp = ev.start.time.split(":");
    sh = parseInt(tp[0], 10) || 0;
    sm = parseInt(tp[1], 10) || 0;
  }
  const startDt = new Date(p[0], p[1] - 1, p[2], sh, sm, 0);

  let endDt = null;
  if (ev.end && ev.end.time) {
    const ep = calParseKey(ev.end.key || dateKey);
    const etp = ev.end.time.split(":");
    const eh = parseInt(etp[0], 10) || 0;
    const em = parseInt(etp[1], 10) || 0;
    endDt = new Date(ep[0], ep[1] - 1, ep[2], eh, em, 0);
  }
  if (!endDt || endDt.getTime() <= startDt.getTime()) {
    endDt = new Date(startDt.getTime() + 60 * 60 * 1000);
  }

  const nowMs = now.getTime();
  const startMs = startDt.getTime();
  const endMs = endDt.getTime();

  if (nowMs >= startMs && nowMs <= endMs) {
    return {
      status: "live",
      label: window.i18n ? window.i18n.t("cal_meeting_live") : "🟢 Đang diễn ra"
    };
  }

  const diffMins = (startMs - nowMs) / (60 * 1000);
  if (diffMins > 0 && diffMins <= 15) {
    return {
      status: "soon",
      label: window.i18n ? window.i18n.t("cal_meeting_soon") : "🔔 Sắp bắt đầu"
    };
  }

  if (diffMins > 15) {
    return { status: "upcoming", label: "" };
  }

  return { status: "passed", label: "" };
}

function calCreateMeetingIcon() {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", "12");
  svg.setAttribute("height", "12");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", "currentColor");
  svg.setAttribute("stroke-width", "2.2");
  svg.setAttribute("stroke-linecap", "round");
  svg.setAttribute("stroke-linejoin", "round");
  svg.style.flexShrink = "0";
  svg.style.display = "inline-block";
  svg.style.verticalAlign = "middle";

  const poly = document.createElementNS("http://www.w3.org/2000/svg", "polygon");
  poly.setAttribute("points", "23 7 16 12 23 17 23 7");
  svg.appendChild(poly);

  const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
  rect.setAttribute("x", "1");
  rect.setAttribute("y", "5");
  rect.setAttribute("width", "15");
  rect.setAttribute("height", "14");
  rect.setAttribute("rx", "2");
  rect.setAttribute("ry", "2");
  svg.appendChild(rect);

  return svg;
}

function calBuildMeetingActions(item) {
  const meeting = calExtractMeetingInfo(item.ev);
  if (!meeting) return null;

  const statusInfo = calGetMeetingStatus(item);
  const card = document.createElement("div");
  card.className = "cal-meeting-card" +
    (statusInfo.status === "live" ? " is-live" : (statusInfo.status === "soon" ? " is-soon" : ""));

  const left = document.createElement("div");
  left.className = "cal-meeting-left";

  const platform = document.createElement("span");
  platform.className = "cal-meeting-platform-badge";
  platform.appendChild(calCreateMeetingIcon());
  const pName = document.createElement("span");
  pName.textContent = meeting.name;
  platform.appendChild(pName);
  left.appendChild(platform);

  if (statusInfo.status === "live") {
    const badge = document.createElement("span");
    badge.className = "cal-meeting-badge-live";
    const dot = document.createElement("span");
    dot.className = "cal-meeting-pulse-dot";
    badge.appendChild(dot);
    const txt = document.createElement("span");
    txt.textContent = statusInfo.label;
    badge.appendChild(txt);
    left.appendChild(badge);
  } else if (statusInfo.status === "soon") {
    const badge = document.createElement("span");
    badge.className = "cal-meeting-badge-soon";
    const icon = document.createElement("span");
    icon.textContent = "⏰ ";
    badge.appendChild(icon);
    const txt = document.createElement("span");
    txt.textContent = statusInfo.label;
    badge.appendChild(txt);
    left.appendChild(badge);
  }

  card.appendChild(left);

  const joinBtn = document.createElement("a");
  joinBtn.href = meeting.url;
  joinBtn.target = "_blank";
  joinBtn.rel = "noreferrer";
  joinBtn.className = "cal-btn-join-meeting" +
    (statusInfo.status === "live" ? " is-live" : (statusInfo.status === "soon" ? " is-soon" : ""));

  joinBtn.appendChild(calCreateMeetingIcon());
  const btnTxt = document.createElement("span");
  btnTxt.textContent = (statusInfo.status === "live" || statusInfo.status === "soon")
    ? (window.i18n ? window.i18n.t("cal_meeting_join_now") : "Vào phòng họp ngay")
    : (window.i18n ? window.i18n.t("cal_meeting_join") : "Vào phòng họp");
  joinBtn.appendChild(btnTxt);
  card.appendChild(joinBtn);

  return card;
}

function calCreateClockIcon() {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", "11");
  svg.setAttribute("height", "11");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", "currentColor");
  svg.setAttribute("stroke-width", "2.2");
  svg.setAttribute("stroke-linecap", "round");
  svg.setAttribute("stroke-linejoin", "round");
  svg.style.flexShrink = "0";

  const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
  circle.setAttribute("cx", "12");
  circle.setAttribute("cy", "12");
  circle.setAttribute("r", "10");
  svg.appendChild(circle);

  const poly = document.createElementNS("http://www.w3.org/2000/svg", "polyline");
  poly.setAttribute("points", "12 6 12 12 16 14");
  svg.appendChild(poly);

  return svg;
}

function calBuildEventRow(item, isAllDay) {
  const row = document.createElement("div");
  row.className = "cal-event-item" + (isAllDay ? " is-allday" : "");
  row.style.borderLeftColor = item.color;

  const topRow = document.createElement("div");
  topRow.className = "cal-event-top";

  const time = document.createElement("div");
  time.className = "cal-event-time";
  time.appendChild(calCreateClockIcon());
  const timeTxt = document.createElement("span");
  timeTxt.textContent = isAllDay
    ? (window.i18n ? window.i18n.t("cal_all_day") : "All day")
    : calEventTimeRange(item.ev);
  time.appendChild(timeTxt);
  topRow.appendChild(time);

  const feed = calFeeds[item.feedIndex];
  if (feed) {
    const chip = document.createElement("span");
    chip.className = "cal-event-feed";
    chip.style.background = item.color + "26";
    chip.style.color = item.color;
    chip.style.borderColor = item.color + "55";
    chip.textContent = feed.name;
    chip.title = feed.url;
    topRow.appendChild(chip);
  }

  row.appendChild(topRow);

  const body = document.createElement("div");
  body.className = "cal-event-body";

  const title = document.createElement("div");
  title.className = "cal-event-title";
  title.textContent = item.ev.summary;
  body.appendChild(title);

  const meeting = calExtractMeetingInfo(item.ev);
  const meetingUrl = meeting ? meeting.url : "";

  if (item.ev.location) {
    const locStr = item.ev.location.trim();
    const isMeetingUrl = meetingUrl && (locStr === meetingUrl || locStr.indexOf(meetingUrl) !== -1);
    if (!isMeetingUrl) {
      const loc = document.createElement("div");
      loc.className = "cal-event-meta loc";
      const isHttp = /^https?:\/\//i.test(locStr);
      if (isHttp) {
        const link = document.createElement("a");
        link.className = "cal-event-link";
        link.href = locStr;
        link.target = "_blank";
        link.rel = "noreferrer";
        link.textContent = locStr;
        loc.appendChild(link);
      } else {
        loc.textContent = "📍 " + locStr;
      }
      body.appendChild(loc);
    }
  }

  if (item.ev.description) {
    const desc = document.createElement("div");
    desc.className = "cal-event-meta desc";
    desc.textContent = item.ev.description;
    body.appendChild(desc);
  }

  if (item.ev.url) {
    const urlStr = item.ev.url.trim();
    const isMeetingUrl = meetingUrl && (urlStr === meetingUrl || urlStr.indexOf(meetingUrl) !== -1);
    if (!isMeetingUrl) {
      const linkDiv = document.createElement("div");
      linkDiv.className = "cal-event-meta";
      const link = document.createElement("a");
      link.className = "cal-event-link";
      link.href = urlStr;
      link.target = "_blank";
      link.rel = "noreferrer";
      link.textContent = "🔗 " + urlStr;
      linkDiv.appendChild(link);
      body.appendChild(linkDiv);
    }
  }

  const meetingActions = calBuildMeetingActions(item);
  if (meetingActions) {
    body.appendChild(meetingActions);
  }

  row.appendChild(body);
  return row;
}

function calAppendChips(container, items, max) {
  const m = Math.min(items.length, max);
  for (let j = 0; j < m; j++) {
    const chip = document.createElement("div");
    chip.className = "cal-chip" + (max > 4 ? " cw" : "");
    chip.style.background = items[j].color + "33";
    chip.style.borderLeftColor = items[j].color;
    const t = items[j].ev.allDay ? "" : (items[j].ev.start.time || "");
    chip.textContent = t && t !== "00:00" ? t + " " + items[j].ev.summary : items[j].ev.summary;
    chip.title = calEventTooltip(items[j].ev);
    container.appendChild(chip);
  }
  if (items.length > max) {
    const more = document.createElement("div");
    more.className = "cal-chip-more";
    more.textContent = "+" + (items.length - max);
    container.appendChild(more);
  }
}

function calFormatDayHeading(key) {
  const p = calParseKey(key);
  const d = new Date(p[0], p[1] - 1, p[2]);
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  const mArr = calMonthArr(lang);
  const wArr = calDowFullArr(lang);
  return wArr[d.getDay()] + ", " + mArr[d.getMonth()] + " " + d.getDate() + ", " + d.getFullYear();
}

function calRenderLiveMeetingBanner() {
  const banner = document.getElementById("cal-live-meeting-banner");
  if (!banner) return;

  const todayKey = calTodayKey();
  const dayMap = calBuildMap(todayKey, todayKey);
  const evs = dayMap[todayKey] || [];

  const activeMeetings = [];
  evs.forEach(function (it) {
    const meeting = calExtractMeetingInfo(it.ev);
    if (!meeting) return;
    const statusInfo = calGetMeetingStatus(it);
    if (statusInfo.status === "live" || statusInfo.status === "soon") {
      activeMeetings.push({ item: it, meeting: meeting, statusInfo: statusInfo });
    }
  });

  if (!activeMeetings.length) {
    banner.style.display = "none";
    banner.textContent = "";
    banner.className = "cal-live-meeting-banner";
    return;
  }

  activeMeetings.sort(function (a, b) {
    if (a.statusInfo.status === "live" && b.statusInfo.status !== "live") return -1;
    if (b.statusInfo.status === "live" && a.statusInfo.status !== "live") return 1;
    return 0;
  });

  banner.textContent = "";
  const hasLive = activeMeetings.some(function (m) { return m.statusInfo.status === "live"; });
  banner.className = "cal-live-meeting-banner " + (hasLive ? "is-live" : "is-soon");

  const header = document.createElement("div");
  header.className = "cal-live-banner-header";

  const title = document.createElement("div");
  title.className = "cal-live-banner-title";
  title.appendChild(calCreateMeetingIcon());
  const titleTxt = document.createElement("span");
  titleTxt.textContent = window.i18n ? window.i18n.t("cal_meeting_live_banner") : "Cuộc họp đang diễn ra hoặc sắp bắt đầu:";
  title.appendChild(titleTxt);
  header.appendChild(title);
  banner.appendChild(header);

  activeMeetings.slice(0, 3).forEach(function (entry) {
    const mItem = document.createElement("div");
    mItem.className = "cal-live-banner-item";

    const info = document.createElement("div");
    info.className = "cal-live-banner-info";

    const name = document.createElement("div");
    name.className = "cal-live-banner-name";
    name.textContent = (entry.statusInfo.status === "live" ? "🟢 " : "🔔 ") + entry.item.ev.summary;
    info.appendChild(name);

    const timeRow = document.createElement("div");
    timeRow.className = "cal-live-banner-time";
    const timeStr = entry.item.ev.allDay
      ? (window.i18n ? window.i18n.t("cal_all_day") : "All day")
      : calEventTimeRange(entry.item.ev);
    timeRow.textContent = entry.meeting.name + " • " + timeStr;
    info.appendChild(timeRow);

    mItem.appendChild(info);

    const cta = document.createElement("a");
    cta.href = entry.meeting.url;
    cta.target = "_blank";
    cta.rel = "noreferrer";
    cta.className = "cal-btn-join-meeting " + (entry.statusInfo.status === "live" ? "is-live" : "is-soon");
    cta.appendChild(calCreateMeetingIcon());
    const ctaTxt = document.createElement("span");
    ctaTxt.textContent = window.i18n ? window.i18n.t("cal_meeting_join_now") : "Vào phòng họp ngay";
    cta.appendChild(ctaTxt);

    mItem.appendChild(cta);
    banner.appendChild(mItem);
  });

  banner.style.display = "flex";
}

function calRenderCalendar() {
  const grid = document.getElementById("cal-grid");
  const list = document.getElementById("cal-list");
  const label = document.getElementById("cal-month-label");
  if (!grid || !list || !label) return;
  calSyncFocusToView();
  calRenderLiveMeetingBanner();
  if (calViewMode === "week") {
    grid.style.display = "grid";
    list.style.display = "none";
    calRenderWeek(grid, label);
  } else if (calViewMode === "list") {
    grid.style.display = "none";
    list.style.display = "block";
    calRenderList(list, label);
  } else {
    grid.style.display = "grid";
    list.style.display = "none";
    calRenderMonth(grid, label);
  }
  calRenderDayPanel();
  calSyncViewButtons();
}

function calRenderMonth(grid, label) {
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  label.textContent = calMonthLabelText();

  grid.textContent = "";
  const wdArr = calDowArr(lang);
  wdArr.forEach(function (w) {
    const el = document.createElement("div");
    el.className = "cal-weekday";
    el.textContent = w;
    grid.appendChild(el);
  });

  const built = calBuildMonth();
  const lead = (built.first.getDay() + 6) % 7;
  const prevDays = new Date(calViewYear, calViewMonth, 0).getDate();
  const total = Math.ceil((lead + built.days) / 7) * 7;
  const today = calTodayKey();

  for (let i = 0; i < total; i++) {
    let date, key, monthOk;
    if (i < lead) {
      date = new Date(calViewYear, calViewMonth - 1, prevDays - lead + i + 1);
      key = calDateKey(date);
      monthOk = false;
    } else if (i < lead + built.days) {
      date = new Date(calViewYear, calViewMonth, i - lead + 1);
      key = calDateKey(date);
      monthOk = true;
    } else {
      date = new Date(calViewYear, calViewMonth + 1, i - lead - built.days + 1);
      key = calDateKey(date);
      monthOk = false;
    }

    const cell = document.createElement("div");
    cell.className = "cal-cell" + (monthOk ? "" : " is-out");
    if (key === today) cell.classList.add("is-today");
    if (key === calSelectedKey) cell.classList.add("is-selected");

    const num = document.createElement("div");
    num.className = "cal-day-num";
    num.textContent = "" + date.getDate();
    cell.appendChild(num);

    calAppendChips(cell, built.dayMap[key] || [], 3);

    const k = key;
    cell.addEventListener("click", function () {
      calSelectedKey = k;
      calRenderCalendar();
    });
    grid.appendChild(cell);
  }
}

function calRenderWeek(grid, label) {
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  label.textContent = calWeekLabelText();

  grid.textContent = "";
  const p = calParseKey(calViewFocusKey || calTodayKey());
  const start = calMondayOf(new Date(p[0], p[1] - 1, p[2]));
  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  const sKey = calDateKey(start);
  const eKey = calDateKey(end);
  const map = calBuildMap(sKey, eKey);
  const today = calTodayKey();

  for (let i = 0; i < 7; i++) {
    const d = new Date(start);
    d.setDate(start.getDate() + i);
    const key = calDateKey(d);
    const head = document.createElement("div");
    head.className = "cal-week-head" + (key === today ? " is-today" : "");
    const dnum = document.createElement("div");
    dnum.className = "cal-week-head-day";
    dnum.textContent = calDowArr(lang)[i];
    const ddate = document.createElement("div");
    ddate.className = "cal-week-head-date";
    ddate.textContent = "" + d.getDate();
    head.appendChild(dnum);
    head.appendChild(ddate);
    const hk = key;
    head.addEventListener("click", function () {
      calSelectedKey = hk;
      calRenderCalendar();
    });
    grid.appendChild(head);
  }

  for (let i = 0; i < 7; i++) {
    const d = new Date(start);
    d.setDate(start.getDate() + i);
    const key = calDateKey(d);
    const cell = document.createElement("div");
    cell.className = "cal-wcell";
    if (key === today) cell.classList.add("is-today");
    if (key === calSelectedKey) cell.classList.add("is-selected");
    const dayEvs = map[key] || [];
    if (!dayEvs.length) {
      const spacer = document.createElement("div");
      spacer.className = "cal-empty-week";
      cell.appendChild(spacer);
    }
    calAppendChips(cell, dayEvs, 6);
    const k = key;
    cell.addEventListener("click", function () {
      calSelectedKey = k;
      calRenderCalendar();
    });
    grid.appendChild(cell);
  }
}

function calRenderList(box, label) {
  label.textContent = calMonthLabelText();
  box.textContent = "";
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  const mArr = calMonthArr(lang);
  const wFull = calDowFullArr(lang);
  const days = new Date(calViewYear, calViewMonth + 1, 0).getDate();
  const sKey = calDateKey(new Date(calViewYear, calViewMonth, 1));
  const eKey = calDateKey(new Date(calViewYear, calViewMonth, days));
  const map = calBuildMap(sKey, eKey);
  const today = calTodayKey();
  let any = false;

  for (let d = 1; d <= days; d++) {
    const key = calViewYear + "-" + calPad2(calViewMonth + 1) + "-" + calPad2(d);
    const dayEvs = map[key] || [];
    if (!dayEvs.length) continue;
    any = true;
    const date = new Date(calViewYear, calViewMonth, d);
    const section = document.createElement("div");
    section.className = "cal-list-day";
    const head = document.createElement("div");
    head.className = "cal-list-day-head" + (key === today ? " is-today" : "");
    head.textContent = wFull[date.getDay()] + ", " + mArr[date.getMonth()] + " " + d + ", " + calViewYear;
    section.appendChild(head);
    const inner = document.createElement("div");
    inner.style.display = "flex";
    inner.style.flexDirection = "column";
    inner.style.gap = "6px";
    const allDay = dayEvs.filter(function (it) { return it.ev.allDay; });
    const timed = dayEvs.filter(function (it) { return !it.ev.allDay; });
    allDay.forEach(function (it) { inner.appendChild(calBuildEventRow(it, true)); });
    timed.forEach(function (it) { inner.appendChild(calBuildEventRow(it, false)); });
    section.appendChild(inner);
    box.appendChild(section);
  }

  if (!any) {
    const empty = document.createElement("div");
    empty.className = "cal-empty";
    empty.textContent = window.i18n ? window.i18n.t("cal_empty_list") : "No events this month";
    box.appendChild(empty);
  }
}

// ----------------------------------------------------------------------------
// Weather & Humidity Subsystem (Open-Meteo local API)
// ----------------------------------------------------------------------------
let calWeatherData = null;

const CAL_WMO_WEATHER = {
  0: { icon: "☀️", text: "Trời quang" },
  1: { icon: "🌤️", text: "Ít mây" },
  2: { icon: "⛅", text: "Mây rải rác" },
  3: { icon: "☁️", text: "Nhiều mây" },
  45: { icon: "🌫️", text: "Sương mù" },
  48: { icon: "🌫️", text: "Sương mù đọng sương" },
  51: { icon: "🌦️", text: "Mưa phùn nhẹ" },
  53: { icon: "🌦️", text: "Mưa phùn vừa" },
  55: { icon: "🌧️", text: "Mưa phùn dày" },
  61: { icon: "🌧️", text: "Mưa nhỏ" },
  63: { icon: "🌧️", text: "Mưa vừa" },
  65: { icon: "🌧️", text: "Mưa to" },
  71: { icon: "🌨️", text: "Tuyết rơi nhẹ" },
  73: { icon: "🌨️", text: "Tuyết vừa" },
  75: { icon: "❄️", text: "Tuyết dày" },
  80: { icon: "🌦️", text: "Mưa rào nhẹ" },
  81: { icon: "🌧️", text: "Mưa rào vừa" },
  82: { icon: "⛈️", text: "Mưa rào rất to" },
  95: { icon: "⛈️", text: "Dông sét" },
  96: { icon: "⛈️", text: "Dông kèm mưa đá" },
  99: { icon: "⛈️", text: "Dông lớn kèm mưa đá" }
};

function calGetWmoInfo(code) {
  const item = CAL_WMO_WEATHER[code] || { icon: "⛅", text: "Thời tiết" };
  const key = "weather_wmo_" + code;
  const translated = (typeof t === "function" ? t(key) : (window.i18n ? window.i18n.t(key) : null));
  return {
    icon: item.icon,
    text: (translated && translated !== key) ? translated : item.text
  };
}

function calRenderWeatherUI() {
  const pillIcon = document.getElementById("cal-weather-icon");
  const pillTemp = document.getElementById("cal-weather-temp");
  const pillHumid = document.getElementById("cal-weather-humidity");
  const pillBtn = document.getElementById("btn-cal-weather-pill");
  const previewTxt = document.getElementById("cal-weather-preview-text");
  const alertBox = document.getElementById("cal-weather-alert-box");
  const dailyList = document.getElementById("cal-weather-daily-list");

  if (!calWeatherData || !calWeatherData.current) return;

  const cur = calWeatherData.current;
  const wmo = calGetWmoInfo(cur.weather_code);
  const tempVal = Math.round(cur.temperature_2m);
  const humidVal = Math.round(cur.relative_humidity_2m);
  const isHighHumidity = humidVal >= 80;

  if (pillIcon) pillIcon.textContent = wmo.icon;
  if (pillTemp) pillTemp.textContent = tempVal + "°C";
  if (pillHumid) pillHumid.textContent = "💧 " + humidVal + "%";

  const headerWeather = document.getElementById("sf-header-weather");
  if (headerWeather) {
    headerWeather.textContent = wmo.icon + " " + tempVal + "°C";
    const detailText = window.i18n ? window.i18n.t("weather_click_detail") : "Bấm để xem chi tiết";
    headerWeather.title = (wmo.text ? wmo.text + " • " : "") + tempVal + "°C • 💧 " + humidVal + "% (" + detailText + ")";
  }

  if (pillBtn) {
    pillBtn.classList.toggle("has-rain-alert", isHighHumidity);
    if (isHighHumidity) {
      pillBtn.title = (window.i18n ? window.i18n.t("cal_weather_rain_alert") : "Độ ẩm cao (>80%) - Nguy cơ mưa cao!");
    } else {
      pillBtn.title = (window.i18n ? window.i18n.t("cal_weather_modal_title") : "Dự báo thời tiết & độ ẩm");
    }
  }

  if (previewTxt) {
    previewTxt.textContent = wmo.icon + " " + tempVal + "°C | 💧 " + humidVal + "% (" + wmo.text + ")";
  }

  // 7-day modal contents: Current Weather Hero Card
  const modalScroll = document.querySelector("#cal-weather-modal .modal-body-scroll");
  if (modalScroll) {
    let hero = modalScroll.querySelector(".cal-weather-hero");
    if (!hero) {
      hero = document.createElement("div");
      hero.className = "cal-weather-hero";
      modalScroll.insertBefore(hero, modalScroll.firstChild);
    }
    hero.textContent = "";

    const mainCol = document.createElement("div");
    mainCol.className = "cal-weather-hero-main";

    const heroIcon = document.createElement("span");
    heroIcon.className = "cal-weather-hero-icon";
    heroIcon.textContent = wmo.icon;
    mainCol.appendChild(heroIcon);

    const titleCol = document.createElement("div");
    const heroTemp = document.createElement("div");
    heroTemp.className = "cal-weather-hero-temp";
    heroTemp.textContent = tempVal + "°C";
    titleCol.appendChild(heroTemp);

    const heroDesc = document.createElement("div");
    heroDesc.className = "cal-weather-hero-desc";
    heroDesc.textContent = wmo.text || "";
    titleCol.appendChild(heroDesc);

    mainCol.appendChild(titleCol);
    hero.appendChild(mainCol);

    const metricsCol = document.createElement("div");
    metricsCol.className = "cal-weather-hero-metrics";

    const humidPill = document.createElement("span");
    humidPill.className = "cal-weather-metric-pill" + (isHighHumidity ? " alert" : "");
    humidPill.textContent = "💧 " + humidVal + "%" + (isHighHumidity ? " (Mưa cao)" : "");
    metricsCol.appendChild(humidPill);

    const rangePill = document.createElement("span");
    rangePill.className = "cal-weather-metric-pill";
    if (calWeatherData.daily && calWeatherData.daily.temperature_2m_min && calWeatherData.daily.temperature_2m_max) {
      rangePill.textContent = "🌡️ " + Math.round(calWeatherData.daily.temperature_2m_min[0]) + "° ~ " + Math.round(calWeatherData.daily.temperature_2m_max[0]) + "°C";
    } else {
      rangePill.textContent = "🌡️ " + tempVal + "°C";
    }
    metricsCol.appendChild(rangePill);

    hero.appendChild(metricsCol);
  }

  // 7-day modal contents
  if (alertBox) {
    if (isHighHumidity) {
      alertBox.style.display = "flex";
      alertBox.textContent = "";
      const alertIcon = document.createElement("span");
      alertIcon.style.fontSize = "16px";
      alertIcon.textContent = "🌧️";
      alertBox.appendChild(alertIcon);

      const alertTxt = document.createElement("div");
      alertTxt.textContent = window.i18n ? window.i18n.t("cal_weather_rain_alert") : "Độ ẩm không khí rất cao (>80%). Nguy cơ mưa cao, hãy chú ý mang ô khi ra ngoài!";
      alertBox.appendChild(alertTxt);
    } else {
      alertBox.style.display = "none";
    }
  }

  if (dailyList && calWeatherData.daily && Array.isArray(calWeatherData.daily.time)) {
    dailyList.textContent = "";
    const daily = calWeatherData.daily;
    const len = daily.time.length;
    for (let i = 0; i < len; i++) {
      const dateStr = daily.time[i];
      const code = daily.weather_code ? daily.weather_code[i] : 0;
      const dwmo = calGetWmoInfo(code);
      const minT = daily.temperature_2m_min ? Math.round(daily.temperature_2m_min[i]) : "--";
      const maxT = daily.temperature_2m_max ? Math.round(daily.temperature_2m_max[i]) : "--";
      const prob = daily.precipitation_probability_max ? Math.round(daily.precipitation_probability_max[i]) : 0;

      const isToday = (dateStr === calTodayKey());
      const card = document.createElement("div");
      card.className = "cal-weather-day-card" + (isToday ? " is-today" : "");

      // Left column: Icon + Date & condition
      const left = document.createElement("div");
      left.className = "cal-weather-day-left";

      const iconSpan = document.createElement("span");
      iconSpan.className = "cal-weather-day-icon";
      iconSpan.textContent = dwmo.icon;
      left.appendChild(iconSpan);

      const info = document.createElement("div");
      info.className = "cal-weather-day-info";

      const dateSpan = document.createElement("div");
      dateSpan.className = "cal-weather-day-date";
      
      let formattedDate = dateStr;
      try {
        const parts = dateStr.split("-");
        if (parts.length === 3) {
          const dObj = new Date(parseInt(parts[0], 10), parseInt(parts[1], 10) - 1, parseInt(parts[2], 10));
          const dowNames = (window.i18n && typeof calDowArr === "function") ? calDowArr(window.i18n.getLanguage ? window.i18n.getLanguage() : "vi") : ["T2", "T3", "T4", "T5", "T6", "T7", "CN"];
          const dow = dowNames[(dObj.getDay() + 6) % 7];
          formattedDate = dow + ", " + parts[2] + "/" + parts[1];
        }
      } catch (_) {}

      dateSpan.textContent = formattedDate;

      if (isToday) {
        const todayTag = document.createElement("span");
        todayTag.className = "cal-weather-day-tag";
        todayTag.textContent = window.i18n ? window.i18n.t("cal_btn_today") : "Hôm nay";
        dateSpan.appendChild(todayTag);
      }
      info.appendChild(dateSpan);

      const condSpan = document.createElement("div");
      condSpan.className = "cal-weather-day-cond";
      condSpan.textContent = dwmo.text || "";
      info.appendChild(condSpan);

      left.appendChild(info);
      card.appendChild(left);

      // Right column: Temp range + Rain prob
      const right = document.createElement("div");
      right.className = "cal-weather-day-right";

      const tempRange = document.createElement("div");
      tempRange.className = "cal-weather-temp-range";

      const minSpan = document.createElement("span");
      minSpan.className = "cal-weather-temp-min";
      minSpan.textContent = minT + "°";
      tempRange.appendChild(minSpan);

      const barSpan = document.createElement("span");
      barSpan.className = "cal-weather-temp-bar";
      tempRange.appendChild(barSpan);

      const maxSpan = document.createElement("span");
      maxSpan.className = "cal-weather-temp-max";
      maxSpan.textContent = maxT + "°C";
      tempRange.appendChild(maxSpan);

      right.appendChild(tempRange);

      const rainPill = document.createElement("span");
      rainPill.className = "cal-weather-rain-pill" + (prob >= 70 ? " high" : "");
      rainPill.textContent = "💧 " + prob + "%";
      right.appendChild(rainPill);

      card.appendChild(right);
      dailyList.appendChild(card);
    }
  }

  calUpdateDayWeather(calSelectedKey);
}

function calUpdateDayWeather(dateKey) {
  const badge = document.getElementById("cal-day-weather-badge");
  if (!badge) return;
  if (!calWeatherData || !calWeatherData.daily || !Array.isArray(calWeatherData.daily.time)) {
    badge.style.display = "none";
    return;
  }
  const idx = calWeatherData.daily.time.indexOf(dateKey);
  if (idx === -1) {
    badge.style.display = "none";
    return;
  }
  const daily = calWeatherData.daily;
  const code = daily.weather_code ? daily.weather_code[idx] : 0;
  const dwmo = calGetWmoInfo(code);
  const minT = daily.temperature_2m_min ? Math.round(daily.temperature_2m_min[idx]) : "--";
  const maxT = daily.temperature_2m_max ? Math.round(daily.temperature_2m_max[idx]) : "--";
  const prob = daily.precipitation_probability_max ? Math.round(daily.precipitation_probability_max[idx]) : 0;

  badge.textContent = dwmo.icon + " " + minT + "°-" + maxT + "°C • 💧" + prob + "%";
  badge.title = dwmo.text + " - Xác suất mưa: " + prob + "%";
  badge.style.display = "inline-flex";
}

function calFetchWeather(lat, lon, silent) {
  const fetchFn = (typeof fetch === "function") ? fetch : (typeof window !== "undefined" && typeof window.fetch === "function" ? window.fetch : (typeof globalThis !== "undefined" && typeof globalThis.fetch === "function" ? globalThis.fetch : null));
  if (!fetchFn) return;

  const url = "https://api.open-meteo.com/v1/forecast?latitude=" + lat + "&longitude=" + lon +
    "&current=temperature_2m,relative_humidity_2m,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto";

  const opts = {};
  if (typeof AbortSignal !== "undefined" && typeof AbortSignal.timeout === "function") {
    opts.signal = AbortSignal.timeout(10000);
  }

  fetchFn(url, opts)
    .then(function (res) {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.json();
    })
    .then(function (data) {
      calWeatherData = data;
      storSet({ sf_cal_weather_cache: { lat: lat, lon: lon, fetchedAt: Date.now(), data: data } });
      calRenderWeatherUI();
      if (!silent) {
        showToast(window.i18n ? window.i18n.t("cal_toast_updated", null, { name: "Weather" }) : "✓ Đã cập nhật thời tiết", "success");
      }
    })
    .catch(function (err) {
      console.error("Open-Meteo weather fetch error:", err);
      const previewTxt = document.getElementById("cal-weather-preview-text");
      if (previewTxt && !calWeatherData) {
        previewTxt.textContent = window.i18n ? window.i18n.t("cal_weather_error") : "Không thể tải thời tiết";
      }
    });
}

// ----------------------------------------------------------------------------
// Modal Controllers
// ----------------------------------------------------------------------------
function calOpenEventModal(dateKey) {
  const modal = document.getElementById("cal-event-modal");
  if (!modal) return;
  const startEl = document.getElementById("cal-manual-start-date");
  const endEl = document.getElementById("cal-manual-end-date");
  const titleEl = document.getElementById("cal-manual-title");
  const locEl = document.getElementById("cal-manual-loc");

  const fillDate = dateKey || calSelectedKey || calTodayKey();
  if (startEl) startEl.value = fillDate;
  if (endEl) endEl.value = fillDate;
  if (titleEl) {
    titleEl.value = "";
    setTimeout(function () { titleEl.focus(); }, 60);
  }
  if (locEl) locEl.value = "";

  modal.style.display = "flex";
}

function calCloseEventModal() {
  const modal = document.getElementById("cal-event-modal");
  if (modal) modal.style.display = "none";
}

function calOpenSettingsModal() {
  const modal = document.getElementById("cal-settings-modal");
  if (modal) modal.style.display = "flex";
}

function calCloseSettingsModal() {
  const modal = document.getElementById("cal-settings-modal");
  if (modal) modal.style.display = "none";
}

function calOpenWeatherModal() {
  const modal = document.getElementById("cal-weather-modal");
  if (modal) modal.style.display = "flex";
}

function calCloseWeatherModal() {
  const modal = document.getElementById("cal-weather-modal");
  if (modal) modal.style.display = "none";
}

function calRenderDayPanel() {
  const head = document.getElementById("cal-day-head");
  const box = document.getElementById("cal-day-events");
  if (!head || !box) return;
  const built = calBuildMap(calSelectedKey, calSelectedKey);
  const evs = built[calSelectedKey] || [];
  head.textContent = calFormatDayHeading(calSelectedKey) + (evs.length ? " (" + evs.length + ")" : "");
  calUpdateDayWeather(calSelectedKey);
  box.textContent = "";
  if (!evs.length) {
    const empty = document.createElement("div");
    empty.className = "cal-empty";
    empty.textContent = window.i18n ? window.i18n.t("cal_no_events") : "No events this day";
    box.appendChild(empty);
    return;
  }
  const allDay = evs.filter(function (it) { return it.ev.allDay; });
  const timed = evs.filter(function (it) { return !it.ev.allDay; });
  timed.sort(function (a, b) {
    const ta = a.ev.start.time || "00:00";
    const tb = b.ev.start.time || "00:00";
    return ta < tb ? -1 : (ta > tb ? 1 : 0);
  });
  allDay.forEach(function (it) { box.appendChild(calBuildEventRow(it, true)); });
  if (allDay.length && timed.length) {
    const sep = document.createElement("div");
    sep.className = "cal-timeline-sep";
    box.appendChild(sep);
  }
  timed.forEach(function (it) { box.appendChild(calBuildEventRow(it, false)); });
}

function calRenderFeedList() {
  const list = document.getElementById("cal-feed-list");
  if (!list) return;
  list.textContent = "";
  if (!calFeeds.length) {
    const empty = document.createElement("div");
    empty.className = "cal-empty";
    empty.textContent = window.i18n ? window.i18n.t("cal_no_feeds") : "";
    list.appendChild(empty);
    return;
  }
  calFeeds.forEach(function (feed, idx) {
    const isHidden = calHiddenFeedIds.indexOf(feed.id) !== -1;
    const row = document.createElement("div");
    row.className = "cal-feed-row" + (isHidden ? " is-hidden" : "");

    const dot = document.createElement("span");
    dot.className = "cal-feed-dot";
    const dotColor = feed.color || calFeedColor(idx);
    dot.style.background = dotColor;
    dot.title = dotColor;
    row.appendChild(dot);

    const nameEl = document.createElement("span");
    nameEl.className = "cal-feed-name";
    nameEl.textContent = (isHidden ? "• " : "● ") + feed.name;
    nameEl.title = feed.url ? feed.url : feed.name;
    row.appendChild(nameEl);

    const countEl = document.createElement("span");
    countEl.className = "cal-feed-count";
    const evts = Array.isArray(calData[feed.id]) ? calData[feed.id].length : 0;
    countEl.textContent = window.i18n ? window.i18n.t("cal_count_events", null, { count: evts }) : (evts + " events");
    row.appendChild(countEl);

    const eye = document.createElement("button");
    eye.className = "cal-feed-btn cal-eye" + (isHidden ? " is-off" : "");
    eye.title = window.i18n ? window.i18n.t(isHidden ? "cal_btn_feed_show" : "cal_btn_feed_hide") : "Toggle";
    if (isHidden) {
      eye.innerHTML = '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94"></path><path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>';
    } else {
      eye.innerHTML = '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>';
    }
    eye.addEventListener("click", function () {
      const pos = calHiddenFeedIds.indexOf(feed.id);
      if (pos === -1) calHiddenFeedIds.push(feed.id);
      else calHiddenFeedIds.splice(pos, 1);
      calPersist();
      calRenderFeedList();
      calRenderCalendar();
    });
    row.appendChild(eye);

    const refresh = document.createElement("button");
    refresh.className = "cal-feed-btn";
    refresh.title = window.i18n ? window.i18n.t("cal_btn_feed_refresh") : "Refresh";
    refresh.innerHTML = '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 4 23 10 17 10"></polyline><polyline points="1 20 1 14 7 14"></polyline><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path></svg>';
    refresh.addEventListener("click", function () { calRefreshFeed(feed.id); });
    if (!feed.url) {
      refresh.style.visibility = "hidden";
      refresh.title = "";
    }
    row.appendChild(refresh);

    const del = document.createElement("button");
    del.className = "cal-feed-btn cal-del";
    del.title = window.i18n ? window.i18n.t("cal_btn_feed_remove") : "Remove";
    del.innerHTML = '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>';
    del.addEventListener("click", function () {
      calFeeds = calFeeds.filter(function (f) { return f.id !== feed.id; });
      delete calData[feed.id];
      calPersist();
      calRenderFeedList();
      calRenderCalendar();
    });
    row.appendChild(del);

    list.appendChild(row);
  });
}

function calRefreshFeed(id, silent) {
  const feed = calFeeds.find(function (f) { return f.id === id; });
  if (!feed || !feed.url) return;
  fetch(feed.url, { cache: "no-store", signal: AbortSignal.timeout(12000) })
    .then(function (res) {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.text();
    })
    .then(function (text) {
      const parsed = calParseIcs(text);
      calData[id] = parsed;
      calPersist();
      calRenderFeedList();
      calRenderCalendar();
      if (!silent) {
        showToast(window.i18n ? window.i18n.t("cal_toast_updated", null, { name: feed.name }) : "✓ Calendar updated", "success");
      }
    })
    .catch(function (err) {
      showToast(window.i18n ? window.i18n.t("cal_toast_error", null, { name: feed.name }) : "⚠️ Cannot load calendar", "error");
      console.error("ICS fetch failed:", err);
    });
}

function calManualFeedEnsure() {
  let feed = calFeeds.find(function (f) { return f.id === "cal_manual"; });
  if (!feed) {
    feed = {
      id: "cal_manual",
      url: "",
      name: window.i18n ? window.i18n.t("cal_manual_feed_name") : "Lịch thủ công",
      manual: true
    };
    calFeeds.push(feed);
  }
  if (!calData["cal_manual"]) calData["cal_manual"] = [];
  return feed;
}

let calManualColor = "";
function calSyncColorUI() {
  const picker = document.getElementById("cal-manual-color-rgb");
  const hexEl = document.getElementById("cal-manual-hex");
  if (picker && calManualColor) picker.value = calManualColor;
  if (hexEl && calManualColor) hexEl.textContent = calManualColor;
  const box = document.getElementById("cal-manual-color");
  if (box) {
    box.querySelectorAll(".cal-color-swatch").forEach(function (x) {
      x.classList.toggle("active", x.dataset.color === calManualColor);
    });
  }
}
function calBuildColorSwatches() {
  const box = document.getElementById("cal-manual-color");
  if (!box) return;
  box.textContent = "";
  CAL_PICKER_PALETTE.forEach(function (c) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "cal-color-swatch" + (c === calManualColor ? " active" : "");
    btn.style.background = c;
    btn.style.color = c;
    btn.dataset.color = c;
    btn.title = c;
    btn.setAttribute("aria-label", c);
    btn.addEventListener("click", function () {
      calManualColor = c;
      calSyncColorUI();
    });
    box.appendChild(btn);
  });
  if (!calManualColor && CAL_PICKER_PALETTE.length) {
    calManualColor = CAL_PICKER_PALETTE[0];
  }
  calSyncColorUI();
}

function calAddManualEvent() {
  const g = function (id) { return document.getElementById(id); };
  const title = (g("cal-manual-title").value || "").trim();
  const startDate = g("cal-manual-start-date").value;
  if (!title || !startDate) {
    showToast(window.i18n ? window.i18n.t("cal_toast_manual_invalid") : "⚠️ Vui lòng nhập tiêu đề và chọn ngày bắt đầu", "error");
    if (!title) g("cal-manual-title").focus();
    else g("cal-manual-start-date").focus();
    return;
  }
  const allDay = g("cal-manual-allday").checked;
  const startTime = allDay ? "" : g("cal-manual-start-time").value;
  const endDate = g("cal-manual-end-date").value;
  let endTime = allDay ? "" : g("cal-manual-end-time").value;
  const freq = g("cal-manual-freq").value;
  const endMode = g("cal-manual-end").value;
  let rrule = "";
  if (freq !== "none") {
    const fmap = { daily: "DAILY", weekly: "WEEKLY", monthly: "MONTHLY", yearly: "YEARLY" };
    let rr = "FREQ=" + (fmap[freq] || "DAILY") + ";INTERVAL=1";
    if (freq === "weekly") {
      const p = calParseKey(startDate);
      const d = new Date(p[0], p[1] - 1, p[2]);
      const names = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"];
      rr += ";BYDAY=" + names[d.getDay()];
    }
    if (endMode === "until" && g("cal-manual-until").value) {
      rr += ";UNTIL=" + g("cal-manual-until").value.replace(/-/g, "");
    } else if (endMode === "count") {
      const n = Math.max(1, parseInt(g("cal-manual-count").value, 10) || 1);
      rr += ";COUNT=" + n;
    }
    rrule = rr;
  }
  const eve = {
    uid: "m_" + Date.now() + "_" + Math.floor(Math.random() * 100000),
    summary: title,
    location: (g("cal-manual-loc").value || "").trim(),
    description: "",
    url: "",
    start: { key: startDate, time: allDay ? null : (startTime || "00:00") },
    end: null,
    allDay: allDay,
    color: calManualColor || CAL_PICKER_PALETTE[0],
    rrule: rrule
  };
  if (endDate) {
    eve.end = { key: endDate, time: allDay ? null : (endTime || startTime || "00:00") };
  } else if (endTime) {
    eve.end = { key: startDate, time: endTime };
  }
  calManualFeedEnsure();
  calData["cal_manual"].push(eve);
  calPersist();
  g("cal-manual-title").value = "";
  g("cal-manual-loc").value = "";
  calCloseEventModal();
  showToast(window.i18n ? window.i18n.t("cal_toast_manual_created") : "✓ Đã thêm sự kiện thủ công");
  calRenderFeedList();
  calRenderCalendar();
}

function calCreateDemoMeeting() {
  const now = new Date();
  const todayKey = calDateKey(now);
  const startH = calPad2(now.getHours());
  const startM = calPad2(now.getMinutes());

  const endObj = new Date(now.getTime() + 45 * 60 * 1000);
  const endKey = calDateKey(endObj);
  const endH = calPad2(endObj.getHours());
  const endM = calPad2(endObj.getMinutes());

  const demoEvent = {
    uid: "demo_meet_" + Date.now(),
    summary: "Họp nhóm nghiên cứu (Demo Live)",
    location: "https://meet.google.com/sf-demo-meet",
    description: "Cuộc họp trực tuyến mẫu thử nghiệm tính năng phòng họp ScholarFlow",
    url: "https://meet.google.com/sf-demo-meet",
    start: { key: todayKey, time: startH + ":" + startM },
    end: { key: endKey, time: endH + ":" + endM },
    allDay: false,
    color: "#0284c7"
  };

  calManualFeedEnsure();
  if (!calData["cal_manual"]) calData["cal_manual"] = [];
  calData["cal_manual"].push(demoEvent);
  calPersist();
  calCloseSettingsModal();
  calSelectedKey = todayKey;
  calViewFocusKey = todayKey;
  calRenderFeedList();
  calRenderCalendar();
  calRenderLiveMeetingBanner();

  const msg = window.i18n ? window.i18n.t("cal_toast_demo_created") : "Đã tạo cuộc họp mẫu! Xem banner Vào phòng họp ngay phía trên.";
  showToast(msg, "success");
}

function calManualInit() {
  const form = document.getElementById("cal-manual-form");
  if (!form) return;
  const toggle = document.getElementById("btn-cal-manual-toggle");
  const g = function (id) { return document.getElementById(id); };
  calBuildColorSwatches();
  if (toggle) {
    toggle.addEventListener("click", function () {
      const on = form.style.display !== "none";
      form.style.display = on ? "none" : "block";
      toggle.classList.toggle("active", !on);
    });
  }
  const syncEndInputs = function () {
    const mode = g("cal-manual-end").value;
    const hasFreq = g("cal-manual-freq").value !== "none";
    g("cal-manual-until").style.display = (hasFreq && mode === "until") ? "block" : "none";
    g("cal-manual-count").style.display = (hasFreq && mode === "count") ? "block" : "none";
    g("cal-manual-end").disabled = !hasFreq;
  };
  g("cal-manual-freq").addEventListener("change", syncEndInputs);
  g("cal-manual-end").addEventListener("change", syncEndInputs);
  const alldayEl = g("cal-manual-allday");
  const syncAllDay = function () {
    const disabled = alldayEl.checked;
    g("cal-manual-start-time").disabled = disabled;
    g("cal-manual-end-time").disabled = disabled;
  };
  alldayEl.addEventListener("change", syncAllDay);
  syncEndInputs();

  const rgb = g("cal-manual-color-rgb");
  if (rgb) {
    rgb.value = calManualColor || "#38bdf8";
    rgb.addEventListener("input", function () {
      calManualColor = rgb.value.toUpperCase();
      calSyncColorUI();
    });
  }

  const save = g("btn-cal-manual-save");
  if (save) {
    save.addEventListener("click", calAddManualEvent);
    g("cal-manual-title").addEventListener("keydown", function (e) {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        calAddManualEvent();
      }
    });
  }

  document.querySelectorAll(".cal-preset-link-chip").forEach(function (chip) {
    chip.addEventListener("click", function () {
      const link = chip.getAttribute("data-link");
      const locInput = g("cal-manual-loc");
      if (locInput && link) {
        locInput.value = link;
        locInput.focus();
      }
    });
  });

  const today = calTodayKey();
  if (!g("cal-manual-start-date").value) g("cal-manual-start-date").value = today;
  if (!g("cal-manual-until").value) g("cal-manual-until").value = today;
  if (!calManualColor) calManualColor = CAL_PICKER_PALETTE[0];
}

function calInit() {
  const input = document.getElementById("cal-feed-input");
  const btnAdd = document.getElementById("btn-cal-add");
  if (btnAdd && input) {
    const addFeed = function () {
      let url = input.value.trim();
      if (!/^https?:\/\//i.test(url)) {
        showToast(window.i18n ? window.i18n.t("cal_toast_invalid_url") : "⚠️ Please enter a valid URL", "error");
        input.focus();
        return;
      }
      // Auto-normalize GitHub Gist page URL to raw ICS URL
      const gistWeb = /^https:\/\/gist\.github\.com\/([^\/]+)\/([a-f0-9]+)(?:\/raw.*)?$/i.exec(url);
      if (gistWeb) {
        url = "https://gist.githubusercontent.com/" + gistWeb[1] + "/" + gistWeb[2] + "/raw/";
      }
      if (calFeeds.some(function (f) { return f.url === url; })) {
        showToast(window.i18n ? window.i18n.t("cal_toast_exists") : "⚠️ This calendar is already added", "error");
        input.value = "";
        return;
      }
      let name = url;
      try { name = new URL(url).hostname.replace(/^www\./, ""); } catch (e) { name = url; }
      const feed = { id: "cal_" + Date.now() + "_" + Math.floor(Math.random() * 100000), url: url, name: name };
      calFeeds.push(feed);
      calPersist();
      input.value = "";
      calRenderFeedList();
      calRefreshFeed(feed.id);
    };
    btnAdd.addEventListener("click", addFeed);
    input.addEventListener("keydown", function (e) { if (e.key === "Enter") addFeed(); });
  }

  document.querySelectorAll(".cal-view-btn").forEach(function (btn) {
    btn.addEventListener("click", function () {
      calViewMode = btn.getAttribute("data-mode") || "month";
      if (calViewMode !== "month") {
        if (!calViewFocusKey) calViewFocusKey = calSelectedKey || calTodayKey();
      }
      calRenderCalendar();
    });
  });

  const prev = document.getElementById("btn-cal-prev");
  const next = document.getElementById("btn-cal-next");
  const today = document.getElementById("btn-cal-today");
  const calStep = function (dir) {
    if (calViewMode === "week") {
      calShiftFocus(dir * 7);
    } else {
      calViewYear = calViewYear + dir;
      if (calViewMonth + dir < 0) {
        calViewMonth = 11;
        calViewYear = calViewYear - 1;
      } else if (calViewMonth + dir > 11) {
        calViewMonth = 0;
        calViewYear = calViewYear + 1;
      } else {
        calViewMonth = calViewMonth + dir;
      }
      calSetFocusToMonth();
    }
    calRenderCalendar();
  };
  if (prev) prev.addEventListener("click", function () { calStep(-1); });
  if (next) next.addEventListener("click", function () { calStep(1); });
  if (today) {today.addEventListener("click", function () {
    const n = new Date();
    calViewYear = n.getFullYear();
    calViewMonth = n.getMonth();
    calViewFocusKey = calTodayKey();
    calSelectedKey = calTodayKey();
    calRenderCalendar();
  });}

  const refreshAll = document.getElementById("btn-cal-refresh-all");
  if (refreshAll) {refreshAll.addEventListener("click", function () {
    if (!calFeeds.length) {
      showToast(window.i18n ? window.i18n.t("cal_toast_no_feeds") : "⚠️ No calendars added yet", "error");
      return;
    }
    calFeeds.forEach(function (f) { if (f.url) calRefreshFeed(f.id, true); });
    showToast(window.i18n ? window.i18n.t("cal_toast_refreshing") : "🔄 Updating all calendars...", "success");
  });}

  // Event Modal handlers
  const btnAddEventQuick = document.getElementById("btn-cal-add-event-quick");
  const btnAddToDay = document.getElementById("btn-cal-add-to-day");
  const btnCloseEvent = document.getElementById("btn-close-cal-event");
  const eventModal = document.getElementById("cal-event-modal");

  if (btnAddEventQuick) btnAddEventQuick.addEventListener("click", function () { calOpenEventModal(calSelectedKey); });
  if (btnAddToDay) btnAddToDay.addEventListener("click", function () { calOpenEventModal(calSelectedKey); });
  if (btnCloseEvent) btnCloseEvent.addEventListener("click", calCloseEventModal);
  if (eventModal) {
    eventModal.addEventListener("click", function (e) {
      if (e.target === eventModal) calCloseEventModal();
    });
  }

  // Settings Modal handlers
  const btnSettingsOpen = document.getElementById("btn-cal-settings-open");
  const btnCloseSettings = document.getElementById("btn-close-cal-settings");
  const settingsModal = document.getElementById("cal-settings-modal");
  const btnGoogleInModal = document.getElementById("btn-cal-google-sync-in-modal");

  if (btnSettingsOpen) btnSettingsOpen.addEventListener("click", calOpenSettingsModal);
  if (btnCloseSettings) btnCloseSettings.addEventListener("click", calCloseSettingsModal);
  if (settingsModal) {
    settingsModal.addEventListener("click", function (e) {
      if (e.target === settingsModal) calCloseSettingsModal();
    });
  }
  if (btnGoogleInModal) {
    btnGoogleInModal.addEventListener("click", function () {
      calCloseSettingsModal();
      calOpenGoogleModal();
    });
  }

  const btnCreateDemo = document.getElementById("btn-cal-create-demo-meeting");
  if (btnCreateDemo) {
    btnCreateDemo.addEventListener("click", calCreateDemoMeeting);
  }

  // Weather Modal & Controls
  const btnWeatherPill = document.getElementById("btn-cal-weather-pill");
  const btnOpenWeatherDetail = document.getElementById("btn-cal-open-weather-detail");
  const btnCloseWeather = document.getElementById("btn-close-cal-weather");
  const weatherModal = document.getElementById("cal-weather-modal");
  const citySelect = document.getElementById("cal-weather-city-select");
  const btnWeatherRefresh = document.getElementById("btn-cal-weather-refresh");

  const headerWeather = document.getElementById("sf-header-weather");
  if (headerWeather) headerWeather.addEventListener("click", calOpenWeatherModal);

  if (btnWeatherPill) btnWeatherPill.addEventListener("click", calOpenWeatherModal);
  if (btnOpenWeatherDetail) btnOpenWeatherDetail.addEventListener("click", calOpenWeatherModal);
  if (btnCloseWeather) btnCloseWeather.addEventListener("click", calCloseWeatherModal);
  if (weatherModal) {
    weatherModal.addEventListener("click", function (e) {
      if (e.target === weatherModal) calCloseWeatherModal();
    });
  }

  const calLoadWeatherFromCity = function (silent) {
    if (!citySelect) return;
    const parts = (citySelect.value || "21.0285,105.8542").split(",");
    const lat = parseFloat(parts[0]);
    const lon = parseFloat(parts[1]);
    storSet({ sf_cal_weather_coords: citySelect.value });
    calFetchWeather(lat, lon, silent);
  };

  if (citySelect) {
    storGet(["sf_cal_weather_coords", "sf_cal_weather_cache"], function (res) {
      if (res && res.sf_cal_weather_coords) {
        citySelect.value = res.sf_cal_weather_coords;
      }
      if (res && res.sf_cal_weather_cache && res.sf_cal_weather_cache.data) {
        const cache = res.sf_cal_weather_cache;
        calWeatherData = cache.data;
        calRenderWeatherUI();
        if (Date.now() - cache.fetchedAt < 30 * 60 * 1000) {
          return;
        }
      }
      calLoadWeatherFromCity(true);
    });

    citySelect.addEventListener("change", function () {
      calLoadWeatherFromCity(false);
    });
  }

  if (btnWeatherRefresh) {
    btnWeatherRefresh.addEventListener("click", function () {
      calLoadWeatherFromCity(false);
    });
  }

  // Google Calendar Sync Modal handlers
  const btnGoogleSync = document.getElementById("btn-cal-google-sync");
  const btnCloseGoogle = document.getElementById("btn-close-cal-google");
  const googleModal = document.getElementById("cal-google-modal");
  const inputGoogle = document.getElementById("cal-google-input");
  const btnGoogleSubmit = document.getElementById("btn-cal-google-submit");
  const btnOpenGcal = document.getElementById("btn-cal-open-gcal");

  const calOpenGoogleModal = function () {
    if (googleModal) {
      googleModal.style.display = "flex";
      if (inputGoogle) inputGoogle.focus();
    }
  };

  const calCloseGoogleModal = function () {
    if (googleModal) googleModal.style.display = "none";
  };

  if (btnGoogleSync) btnGoogleSync.addEventListener("click", calOpenGoogleModal);
  if (btnCloseGoogle) btnCloseGoogle.addEventListener("click", calCloseGoogleModal);
  if (googleModal) {
    googleModal.addEventListener("click", function (e) {
      if (e.target === googleModal) calCloseGoogleModal();
    });
  }
  if (btnOpenGcal) {
    btnOpenGcal.addEventListener("click", function () {
      window.open("https://calendar.google.com", "_blank");
    });
  }

  const handleGoogleSubmit = function () {
    if (!inputGoogle) return;
    let val = (inputGoogle.value || "").trim();
    if (!val) {
      showToast(window.i18n ? window.i18n.t("cal_toast_invalid_url") : "⚠️ Vui lòng nhập link iCal Google Calendar", "error");
      inputGoogle.focus();
      return;
    }
    if (val.startsWith("webcal://")) {
      val = "https://" + val.slice(9);
    }
    if (!/^https?:\/\//i.test(val)) {
      showToast(window.i18n ? window.i18n.t("cal_toast_invalid_url") : "⚠️ Link không hợp lệ (cần bắt đầu bằng https://)", "error");
      inputGoogle.focus();
      return;
    }

    const feed = {
      id: "cal_gcal_" + Date.now(),
      name: "Google Calendar",
      url: val,
      color: "#4285F4",
      isGoogle: true
    };
    calFeeds.push(feed);
    calPersist();
    calRefreshFeed(feed.id);
    calRenderFeedList();
    calCloseGoogleModal();
    inputGoogle.value = "";
    showToast(window.i18n ? window.i18n.t("cal_google_sync_success") : "✓ Đã kết nối Google Calendar thành công!", "success");
  };

  if (btnGoogleSubmit) btnGoogleSubmit.addEventListener("click", handleGoogleSubmit);
  if (inputGoogle) {
    inputGoogle.addEventListener("keydown", function (e) {
      if (e.key === "Enter") {
        e.preventDefault();
        handleGoogleSubmit();
      }
    });
  }

  if (!window._calMeetingInterval) {
    window._calMeetingInterval = setInterval(function () {
      calRenderLiveMeetingBanner();
    }, 45000);
  }

  const now = new Date();
  if (!calViewYear) { calViewYear = now.getFullYear(); calViewMonth = now.getMonth(); }
  if (!calSelectedKey) calSelectedKey = calTodayKey();
  if (!calViewFocusKey) calViewFocusKey = calSelectedKey;

  calManualInit();

  if (!calFeedsLoaded) {
    calFeedsLoaded = true;
    calLoad();
  } else {
    calRenderCalendar();
  }
}

onReady(function () {
  calInit();
});

window.addEventListener("app-language-changed", function () {
  calRenderFeedList();
  calRenderCalendar();
  if (typeof calRenderLiveMeetingBanner === "function") {
    calRenderLiveMeetingBanner();
  }
});
