// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/tabs/capture.js
// Tab 3: smart screenshot, element/table capture, marquee snip
// Extracted from js/sidebar.js (lines 4270-4907) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Tab 3: Smart Screenshot Controller (Fixes Duplicate Sticky Headers)
// ----------------------------------------------------------------------------
let screenshotSettings = {
  autoCopy: true,
  format: "png",
  delay: 0
};

function loadScreenshotSettings() {
  storGet("super_screenshot_settings", (res) => {
    if (res && res.super_screenshot_settings) {
      screenshotSettings = { ...screenshotSettings, ...res.super_screenshot_settings };
    }
    const autoCopyCheck = document.getElementById("cap-pref-autocopy");
    const formatSelect = document.getElementById("cap-pref-format");
    const delaySelect = document.getElementById("cap-pref-delay");
    if (autoCopyCheck) autoCopyCheck.checked = screenshotSettings.autoCopy !== false;
    if (formatSelect) formatSelect.value = screenshotSettings.format || "png";
    if (delaySelect) delaySelect.value = (screenshotSettings.delay || 0).toString();
  });
}

function saveScreenshotSettings() {
  const autoCopyCheck = document.getElementById("cap-pref-autocopy");
  const formatSelect = document.getElementById("cap-pref-format");
  const delaySelect = document.getElementById("cap-pref-delay");

  screenshotSettings.autoCopy = autoCopyCheck ? autoCopyCheck.checked : true;
  screenshotSettings.format = formatSelect ? formatSelect.value : "png";
  screenshotSettings.delay = delaySelect ? parseInt(delaySelect.value, 10) || 0 : 0;

  storSet({ super_screenshot_settings: screenshotSettings }, () => {
    const statusEl = document.getElementById("cap-settings-status");
    if (statusEl) {
      statusEl.textContent = window.i18n ? window.i18n.t("toast_settings_saved") : "✓ Đã lưu cài đặt!";
      statusEl.style.color = "#38bdf8";
      setTimeout(() => {
        statusEl.textContent = window.i18n ? window.i18n.t("toast_autosave") : "💾 Tự động lưu";
        statusEl.style.color = "#10b981";
      }, 1500);
    }
  });
}

function getVisibleTabDataUrl(windowId = null) {
  return new Promise((resolve) => {
    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : ((typeof chrome !== "undefined" && chrome.tabs) ? chrome.tabs : null);
    const runtimeApi = (typeof browser !== "undefined" && browser.runtime) ? browser.runtime : ((typeof chrome !== "undefined" && chrome.runtime) ? chrome.runtime : null);

    const fallbackToBackground = () => {
      if (!runtimeApi || typeof runtimeApi.sendMessage !== "function") {
        return resolve(null);
      }
      const sendCb = (res) => resolve(res?.dataUrl || null);
      try {
        if (runtimeApi.sendMessage.length >= 2) {
          runtimeApi.sendMessage({ action: "CAPTURE_VISIBLE_TAB", windowId }, sendCb);
        } else {
          Promise.resolve(runtimeApi.sendMessage({ action: "CAPTURE_VISIBLE_TAB", windowId })).then(sendCb).catch(() => resolve(null));
        }
      } catch (e) {
        resolve(null);
      }
    };

    if (tabsApi && typeof tabsApi.captureVisibleTab === "function") {
      try {
        const captureResult = tabsApi.captureVisibleTab(windowId || null, { format: "png" });
        if (captureResult && typeof captureResult.then === "function") {
          captureResult.then((dataUrl) => resolve(dataUrl || null)).catch(() => fallbackToBackground());
          return;
        }

        if (typeof tabsApi.captureVisibleTab === "function") {
          tabsApi.captureVisibleTab(windowId || null, { format: "png" }, (dataUrl) => {
            if (dataUrl) return resolve(dataUrl);
            fallbackToBackground();
          });
          return;
        }
      } catch (e) {
        // Fall through to background fallback
      }
    }

    fallbackToBackground();
  });
}

async function captureVisibleScreen() {
  const delaySec = screenshotSettings.delay || 0;
  if (delaySec > 0) {
    showToast("toast_screenshot_timer", "success", [delaySec]);
    await new Promise(r => setTimeout(r, delaySec * 1000));
  }
  const dataUrl = await getVisibleTabDataUrl();
  if (dataUrl) {
    if (screenshotSettings.format === "jpeg") {
      const img = await loadImage(dataUrl);
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      const jpegUrl = canvas.toDataURL("image/jpeg", 0.9);
      displayScreenshotResult(jpegUrl);
    } else {
      displayScreenshotResult(dataUrl);
    }
    if (!screenshotSettings.autoCopy) {
      showToast("✓ Đã chụp ảnh màn hình!");
    }
  } else {
    showToast("err_004", "error");
  }
}

async function scrollTabTo(targetY, durationMs = 120) {
  try {
    const scriptingApi = (typeof browser !== "undefined" && browser.scripting)
      ? browser.scripting
      : ((typeof chrome !== "undefined" && chrome.scripting) ? chrome.scripting : null);
    if (!scriptingApi || !scriptingApi.executeScript) return null;
    const res = await scriptingApi.executeScript({
      target: { tabId: activeTabId },
      func: (targetY, duration) => {
        return new Promise((resolve) => {
          const doc = document.documentElement;
          const body = document.body;
          const getMaxScroll = () => {
            const totalH = Math.max(
              body?.scrollHeight || 0, doc?.scrollHeight || 0,
              body?.offsetHeight || 0, doc?.offsetHeight || 0,
              body?.clientHeight || 0, doc?.clientHeight || 0
            );
            return Math.max(0, totalH - window.innerHeight);
          };

          const startY = window.scrollY || window.pageYOffset || 0;
          const maxScroll = getMaxScroll();
          const clampedTarget = Math.max(0, Math.min(targetY, maxScroll));
          const distance = clampedTarget - startY;

          if (Math.abs(distance) < 2 || duration <= 0) {
            window.scrollTo({ top: clampedTarget, left: 0, behavior: "instant" });
            return resolve({
              scrollY: Math.round(window.scrollY || window.pageYOffset || 0),
              maxScrollY: maxScroll
            });
          }

          const startTime = performance.now();
          function step(now) {
            const elapsed = now - startTime;
            const progress = Math.min(1, elapsed / duration);
            // Cubic ease-out for silky smooth visual movement
            const ease = 1 - Math.pow(1 - progress, 3);
            window.scrollTo({ top: Math.round(startY + distance * ease), left: 0, behavior: "instant" });

            if (progress < 1) {
              requestAnimationFrame(step);
            } else {
              window.scrollTo({ top: clampedTarget, left: 0, behavior: "instant" });
              requestAnimationFrame(() => {
                requestAnimationFrame(() => {
                  setTimeout(() => {
                    resolve({
                      scrollY: Math.round(window.scrollY || window.pageYOffset || 0),
                      maxScrollY: getMaxScroll()
                    });
                  }, 50);
                });
              });
            }
          }
          requestAnimationFrame(step);
        });
      },
      args: [targetY, durationMs]
    });
    return (res && res[0] && res[0].result) ? res[0].result : { scrollY: targetY, maxScrollY: targetY };
  } catch (e) {
    return { scrollY: targetY, maxScrollY: targetY };
  }
}

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

async function captureFullPageSmart() {
  const delaySec = screenshotSettings.delay || 0;
  if (delaySec > 0) {
    showToast("toast_screenshot_full_timer", "success", [delaySec]);
    await new Promise(r => setTimeout(r, delaySec * 1000));
  }
  showToast("⏳ Đang chuẩn bị chụp toàn trang...");
  sendTabMessage({ action: "PREPARE_FULLPAGE_SCROLL" }, async (info) => {
    if (!info) {
      return captureVisibleScreen(); // Fallback
    }

    const { totalHeight, viewportHeight, viewportWidth } = info;

    // Step 0: Ensure scrolled to top (instant)
    await scrollTabTo(0, 0);
    await new Promise(r => setTimeout(r, 140));

    // Capture slice 0 (includes top header/branding naturally)
    const firstDataUrl = await getVisibleTabDataUrl();
    if (!firstDataUrl) {
      return showToast("err_004", "error");
    }

    const firstImg = await loadImage(firstDataUrl);
    const scaleX = firstImg.width / viewportWidth;
    const scaleY = firstImg.height / viewportHeight;

    const canvasW = firstImg.width;
    const initialCanvasH = Math.max(firstImg.height, Math.round(totalHeight * scaleY));

    let currentCanvas = document.createElement("canvas");
    currentCanvas.width = canvasW;
    currentCanvas.height = initialCanvasH;
    let currentCtx = currentCanvas.getContext("2d");

    // Draw slice 0
    currentCtx.drawImage(firstImg, 0, 0);

    let lastDrawnDocY = viewportHeight; // in logical document pixels

    // Hide sticky and fixed elements for all subsequent slices so they never duplicate
    await new Promise(r => sendTabMessage({ action: "HIDE_FIXED_ELEMENTS" }, r));

    let sliceIndex = 1;
    const maxSlices = 60;

    while (lastDrawnDocY < totalHeight && sliceIndex < maxSlices) {
      // Scroll so that lastDrawnDocY is positioned at the top of the viewport
      const scrollResult = await scrollTabTo(Math.round(lastDrawnDocY), 120);
      const actualScrollY = typeof scrollResult.scrollY === "number" ? scrollResult.scrollY : Math.round(lastDrawnDocY);
      const maxScrollY = typeof scrollResult.maxScrollY === "number" ? scrollResult.maxScrollY : totalHeight;

      // Small pause for GPU compositor to settle
      await new Promise(r => setTimeout(r, 70));

      const sliceDataUrl = await getVisibleTabDataUrl();
      if (!sliceDataUrl) break;

      const sliceImg = await loadImage(sliceDataUrl);

      // Where does our unpainted content start in this sliceImg?
      // In sliceImg, y=0 is at document actualScrollY.
      // We need content starting at lastDrawnDocY.
      const srcDocY = Math.max(0, lastDrawnDocY - actualScrollY);
      const srcY = Math.round(srcDocY * scaleY);

      if (srcY >= sliceImg.height) {
        // Reached end of document or no new content revealed
        break;
      }

      const srcH = sliceImg.height - srcY;
      const destY = Math.round(lastDrawnDocY * scaleY);

      // Expand canvas if page grew dynamically during scroll
      if (destY + srcH > currentCanvas.height) {
        const expanded = document.createElement("canvas");
        expanded.width = currentCanvas.width;
        expanded.height = destY + srcH + Math.round(viewportHeight * scaleY);
        const expCtx = expanded.getContext("2d");
        expCtx.drawImage(currentCanvas, 0, 0);
        currentCanvas = expanded;
        currentCtx = expCtx;
      }

      currentCtx.drawImage(
        sliceImg,
        0, srcY, sliceImg.width, srcH,
        0, destY, sliceImg.width, srcH
      );

      lastDrawnDocY += (srcH / scaleY);
      sliceIndex++;

      // If we reached max possible scroll, bottom is reached
      if (actualScrollY >= Math.floor(maxScrollY) - 1) {
        break;
      }
    }

    // Restore fixed elements & smooth scroll back to top
    await new Promise(r => sendTabMessage({ action: "RESTORE_FIXED_ELEMENTS" }, r));
    await scrollTabTo(0, 180);

    // Crop canvas to exact drawn height to eliminate any trailing blank space
    const finalHeight = Math.max(1, Math.round(lastDrawnDocY * scaleY));
    const finalCanvas = document.createElement("canvas");
    finalCanvas.width = currentCanvas.width;
    finalCanvas.height = finalHeight;
    const fctx = finalCanvas.getContext("2d");
    fctx.drawImage(
      currentCanvas,
      0, 0, currentCanvas.width, finalHeight,
      0, 0, currentCanvas.width, finalHeight
    );

    const isJpeg = screenshotSettings.format === "jpeg";
    const fullDataUrl = finalCanvas.toDataURL(isJpeg ? "image/jpeg" : "image/png", 0.92);
    displayScreenshotResult(fullDataUrl);
    if (!screenshotSettings.autoCopy) {
      showToast("✔ Chụp toàn bộ trang hoàn tất, không bị chồng chữ!");
    }
  });
}

function displayScreenshotResult(dataUrl) {
  lastCapturedDataUrl = dataUrl;
  const box = document.getElementById("screenshot-preview-box");
  const img = document.getElementById("screenshot-img");
  if (img) img.src = dataUrl;
  if (box) {
    box.style.display = "block";
    box.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }

  // Notify webpage of success
  sendTabMessage({ action: "SHOW_PAGE_TOAST", text: "✔ Đã chụp đối tượng thành công!" });

  // Auto-copy to clipboard if enabled
  if (screenshotSettings.autoCopy && dataUrl) {
    try {
      fetch(dataUrl)
        .then(res => res.blob())
        .then(blob => {
          navigator.clipboard.write([new ClipboardItem({ [blob.type]: blob })]).then(() => {
            showToast("✔ Đã chụp & tự động chép vào Clipboard!");
          }).catch(() => {});
        }).catch(() => {});
    } catch (e) {}
  }
}

// ----------------------------------------------------------------------------
// Element & Table Capture Engine (Scrollable Containers & Tall Tables)
// ----------------------------------------------------------------------------
async function captureChosenElement(info) {
  if (!info) return;

  try {
    const tab = await ensureActiveTab();
    if (!tab || !tab.id) {
      showToast("❌ Không tìm thấy tab hoạt động!");
      return;
    }

    // Delay countdown if user set in screenshot settings
    const delaySec = parseInt(screenshotSettings.delay, 10) || 0;
    if (delaySec > 0) {
      for (let i = delaySec; i > 0; i--) {
        showToast("toast_capture_countdown", "info", [i]);
        await new Promise(r => setTimeout(r, 1000));
      }
    }

    showToast("📸 Đang tối ưu và chụp thẻ đối tượng...");

    // 1. Gently ensure element is visible in viewport and retrieve fresh dimensions
    const viewRes = await new Promise(r => sendTabMessage({ action: "SCROLL_ELEMENT_INTO_VIEW" }, r));
    await new Promise(r => setTimeout(r, 100));

    const rect = viewRes?.rect || { left: info.left, top: info.top, width: info.width, height: info.height };
    const vpW = viewRes?.viewportWidth || info.viewportWidth || window.innerWidth;
    const vpH = viewRes?.viewportHeight || info.viewportHeight || window.innerHeight;

    // Case A: Container has internal scrollbars (e.g. table with overflow: auto/scroll)
    // Only enter Case A if element has genuine internal scrollbars and is not the entire viewport/page!
    const hasGenuineScrollX = (info.hasScrollX || viewRes?.hasScrollX) && (info.scrollWidth > info.clientWidth + 15) && (info.clientWidth < vpW * 0.98);
    const hasGenuineScrollY = (info.hasScrollY || viewRes?.hasScrollY) && (info.scrollHeight > info.clientHeight + 15) && (info.clientHeight < vpH * 0.95);

    if (hasGenuineScrollX || hasGenuineScrollY) {
      const totalW = info.scrollWidth;
      const totalH = info.scrollHeight;
      const clientW = info.clientWidth;
      const clientH = info.clientHeight;

      const firstDataUrl = await getVisibleTabDataUrl(tab.windowId);
      if (!firstDataUrl) throw new Error("Không thể chụp khung nhìn trình duyệt");
      const firstImg = await loadImage(firstDataUrl);

      const scaleX = firstImg.width / vpW;
      const scaleY = firstImg.height / vpH;

      const masterCanvas = document.createElement("canvas");
      masterCanvas.width = Math.max(1, Math.round(totalW * scaleX));
      masterCanvas.height = Math.max(1, Math.round(totalH * scaleY));
      const mctx = masterCanvas.getContext("2d");

      const stepX = Math.max(60, clientW - 24);
      const stepY = Math.max(60, clientH - 24);

      for (let curY = 0; curY < totalH; curY += stepY) {
        for (let curX = 0; curX < totalW; curX += stepX) {
          const scrollRes = await new Promise(r => sendTabMessage({
            action: "SCROLL_CAPTURE_TARGET",
            scrollLeft: curX,
            scrollTop: curY,
            hideScrollbars: true
          }, r));

          await new Promise(r => setTimeout(r, 60));

          const sliceDataUrl = await getVisibleTabDataUrl(tab.windowId);
          if (!sliceDataUrl) continue;
          const sliceImg = await loadImage(sliceDataUrl);

          const curRect = scrollRes?.rect || rect;
          const actualX = scrollRes?.actualScrollLeft ?? curX;
          const actualY = scrollRes?.actualScrollTop ?? curY;

          const sliceW = Math.min(clientW, totalW - actualX);
          const sliceH = Math.min(clientH, totalH - actualY);

          // Clamped safe source bounds
          const srcX = Math.max(0, Math.min(sliceImg.width - 1, Math.round(curRect.left * scaleX)));
          const srcY = Math.max(0, Math.min(sliceImg.height - 1, Math.round(curRect.top * scaleY)));
          const srcW = Math.max(1, Math.min(sliceImg.width - srcX, Math.round(sliceW * scaleX)));
          const srcH = Math.max(1, Math.min(sliceImg.height - srcY, Math.round(sliceH * scaleY)));

          const destX = Math.round(actualX * scaleX);
          const destY = Math.round(actualY * scaleY);

          mctx.drawImage(sliceImg, srcX, srcY, srcW, srcH, destX, destY, srcW, srcH);

          if (actualX + clientW >= totalW) break;
        }
        if (curY + clientH >= totalH) break;
      }

      await new Promise(r => sendTabMessage({
        action: "RESTORE_CAPTURE_TARGET",
        origScrollLeft: info.origScrollLeft,
        origScrollTop: info.origScrollTop
      }, r));

      const isJpeg = screenshotSettings.format === "jpeg";
      const dataUrl = masterCanvas.toDataURL(isJpeg ? "image/jpeg" : "image/png", 0.92);
      displayScreenshotResult(dataUrl);
      if (!screenshotSettings.autoCopy) {
        showToast("✔ Đã chụp hoàn chỉnh bảng có thanh cuộn!");
      }
      return;
    }

    // Case B: Tall element spanning beyond viewport on the webpage (e.g. table > 1.2x viewport height)
    if (info.height > vpH * 1.2 && info.height > 600) {
      await new Promise(r => sendTabMessage({ action: "HIDE_FIXED_ELEMENTS" }, r));

      const firstDataUrl = await getVisibleTabDataUrl(tab.windowId);
      if (!firstDataUrl) throw new Error("Không thể chụp khung nhìn trình duyệt");
      const firstImg = await loadImage(firstDataUrl);

      const scaleX = firstImg.width / vpW;
      const scaleY = firstImg.height / vpH;

      const totalH = info.height;
      const masterCanvas = document.createElement("canvas");
      masterCanvas.width = Math.max(1, Math.round(rect.width * scaleX));
      masterCanvas.height = Math.max(1, Math.round(totalH * scaleY));
      const mctx = masterCanvas.getContext("2d");

      let drawnH = 0;
      const stepY = Math.round(vpH * 0.7);
      const baseDocTop = typeof viewRes?.docTop === "number" ? viewRes.docTop : (typeof info.docTop === "number" ? info.docTop : ((rect.top || 0) + (info.origScrollTop || 0)));

      while (drawnH < totalH) {
        await scrollTabTo(baseDocTop + drawnH, 150);
        await new Promise(r => setTimeout(r, 70));

        const sliceDataUrl = await getVisibleTabDataUrl(tab.windowId);
        if (!sliceDataUrl) break;
        const sliceImg = await loadImage(sliceDataUrl);

        const curRectRes = await new Promise(r => sendTabMessage({ action: "GET_CAPTURE_TARGET_RECT" }, r));
        const curRect = curRectRes?.rect || rect;

        const visibleTop = Math.max(0, curRect.top);
        const visibleBottom = Math.min(vpH, curRect.top + curRect.height);
        const visibleH = Math.max(0, visibleBottom - visibleTop);

        if (visibleH > 0) {
          const srcX = Math.max(0, Math.min(sliceImg.width - 1, Math.round(curRect.left * scaleX)));
          const srcY = Math.max(0, Math.min(sliceImg.height - 1, Math.round(visibleTop * scaleY)));
          const srcW = Math.max(1, Math.min(sliceImg.width - srcX, Math.round(curRect.width * scaleX)));
          const srcH = Math.max(1, Math.min(sliceImg.height - srcY, Math.round(visibleH * scaleY)));
          const destY = Math.round(drawnH * scaleY);

          mctx.drawImage(sliceImg, srcX, srcY, srcW, srcH, 0, destY, srcW, srcH);
          drawnH += visibleH;
        } else {
          break;
        }

        if (drawnH >= totalH) break;
      }

      await new Promise(r => sendTabMessage({ action: "RESTORE_FIXED_ELEMENTS" }, r));
      await new Promise(r => sendTabMessage({ action: "RESTORE_CAPTURE_TARGET" }, r));

      const isJpeg = screenshotSettings.format === "jpeg";
      const dataUrl = masterCanvas.toDataURL(isJpeg ? "image/jpeg" : "image/png", 0.92);
      displayScreenshotResult(dataUrl);
      if (!screenshotSettings.autoCopy) {
        showToast("✔ Đã chụp hoàn chỉnh bảng dài vượt trang!");
      }
      return;
    }

    // Case C: Standard element (fits or visible inside viewport) - Clamped safe crop
    const captureDataUrl = await getVisibleTabDataUrl(tab.windowId);
    if (!captureDataUrl) {
      showToast("❌ Không thể chụp hình ảnh màn hình!");
      return;
    }

    const baseImg = await loadImage(captureDataUrl);
    const scaleX = baseImg.width / vpW;
    const scaleY = baseImg.height / vpH;

    // Guaranteed safe bounds within source image
    const sx = Math.max(0, Math.min(baseImg.width - 1, Math.round(rect.left * scaleX)));
    const sy = Math.max(0, Math.min(baseImg.height - 1, Math.round(rect.top * scaleY)));
    const sw = Math.max(1, Math.min(baseImg.width - sx, Math.round(rect.width * scaleX)));
    const sh = Math.max(1, Math.min(baseImg.height - sy, Math.round(rect.height * scaleY)));

    const cropCanvas = document.createElement("canvas");
    cropCanvas.width = sw;
    cropCanvas.height = sh;
    const cctx = cropCanvas.getContext("2d");

    cctx.drawImage(baseImg, sx, sy, sw, sh, 0, 0, sw, sh);

    await new Promise(r => sendTabMessage({ action: "RESTORE_CAPTURE_TARGET" }, r));

    const isJpeg = screenshotSettings.format === "jpeg";
    const finalDataUrl = cropCanvas.toDataURL(isJpeg ? "image/jpeg" : "image/png", 0.92);
    displayScreenshotResult(finalDataUrl);
    if (!screenshotSettings.autoCopy) {
      showToast("✔ Đã chụp thành công đối tượng!");
    }
  } catch (err) {
    console.error("captureChosenElement error:", err);
    showToast("err_004", "error");
  }
}

// ----------------------------------------------------------------------------
// Interactive 2-in-1 Snip & Element Marquee Capture
// ----------------------------------------------------------------------------
async function captureSnipRect(msg) {
  if (!msg || !msg.rect) return;

  try {
    const tab = await ensureActiveTab();
    if (!tab || !tab.id) {
      showToast("❌ Không tìm thấy tab hoạt động!");
      return;
    }

    // Delay countdown if user set in screenshot settings
    const delaySec = parseInt(screenshotSettings.delay, 10) || 0;
    if (delaySec > 0) {
      for (let i = delaySec; i > 0; i--) {
        showToast("toast_capture_countdown", "info", [i]);
        await new Promise(r => setTimeout(r, 1000));
      }
    }

    showToast("📸 Đang tối ưu và xuất ảnh vùng chọn...");
    await new Promise(r => setTimeout(r, 60));
    const dataUrl = await getVisibleTabDataUrl(tab.windowId);
    if (!dataUrl) throw new Error("Không thể chụp khung nhìn trình duyệt!");

    const baseImg = await loadImage(dataUrl);
    const vpW = msg.viewportWidth || window.innerWidth;
    const vpH = msg.viewportHeight || window.innerHeight;
    const scaleX = baseImg.width / vpW;
    const scaleY = baseImg.height / vpH;

    const sx = Math.max(0, Math.min(baseImg.width - 1, Math.round(msg.rect.left * scaleX)));
    const sy = Math.max(0, Math.min(baseImg.height - 1, Math.round(msg.rect.top * scaleY)));
    const sw = Math.max(1, Math.min(baseImg.width - sx, Math.round(msg.rect.width * scaleX)));
    const sh = Math.max(1, Math.min(baseImg.height - sy, Math.round(msg.rect.height * scaleY)));

    const canvas = document.createElement("canvas");
      canvas.width = sw;
      canvas.height = sh;
      const ctx = canvas.getContext("2d");

      if (msg.borderRadius && msg.borderRadius !== "0px" && ctx.roundRect) {
        let br = 0;
        const match = msg.borderRadius.match(/(\d+(?:\.\d+)?)(px|%)/);
        if (match) {
          const val = parseFloat(match[1]);
          if (match[2] === "%") {
            br = (val / 100) * Math.min(sw, sh);
          } else {
            br = val * scaleX; 
          }
        }
        if (br > 0) {
          ctx.beginPath();
          ctx.roundRect(0, 0, sw, sh, br);
          ctx.clip();
        }
      }

      ctx.drawImage(baseImg, sx, sy, sw, sh, 0, 0, sw, sh);

    const isJpeg = screenshotSettings.format === "jpeg";
    const finalDataUrl = canvas.toDataURL(isJpeg ? "image/jpeg" : "image/png", 0.92);
    displayScreenshotResult(finalDataUrl);

    if (!screenshotSettings.autoCopy) {
      showToast("✔ Đã chụp thành công vùng chọn!");
    }
  } catch (err) {
    console.error("captureSnipRect error:", err);
    showToast("err_004", "error");
  }
}

