// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/tabs/dual-tabs.js
// Dual-web quick switcher (2 linked tabs)
// Extracted from js/sidebar.js (lines 4044-4156) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Dual-Web Quick Switcher (2-Page Linked Tabs Controller)
// ----------------------------------------------------------------------------
let currentTabObj = null; // Tab A
let linkedTabObj = null;  // Tab B
let isDualTabDropdownOpen = false;

function updateDualTabsUI() {
  const tabATitle = document.getElementById("tab-a-title");
  const tabBTitle = document.getElementById("tab-b-title");
  const pillB = document.getElementById("pill-tab-b");

  if (tabATitle) {
    const titleA = (currentTabObj && currentTabObj.title) ? currentTabObj.title : (window.i18n ? window.i18n.t("tab_a_title") : "Trang hiện tại");
    tabATitle.textContent = titleA;
    tabATitle.title = titleA;
  }

  if (tabBTitle) {
    if (linkedTabObj && linkedTabObj.title) {
      tabBTitle.textContent = linkedTabObj.title;
      if (pillB) {
        const tipTemplate = window.i18n ? window.i18n.t("switch_to_tab") : "Chuyển sang: {title} (Phím tắt: Alt + Q)";
        pillB.title = tipTemplate.replace("{title}", linkedTabObj.title);
      }
    } else {
      const emptyLabel = window.i18n ? window.i18n.t("tab_b_empty") : "Chưa có trang phụ";
      tabBTitle.textContent = `${emptyLabel} (Alt+Q)`;
      if (pillB) {
        pillB.title = window.i18n ? window.i18n.t("tab_b_empty_tip") : "Bấm ▼ để chọn trang liên kết hoặc mở tab mới";
      }
    }
  }
}

async function swapDualTabs() {
  const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
  if (!tabsApi) return;

  if (linkedTabObj && linkedTabObj.id && currentTabObj && linkedTabObj.id !== currentTabObj.id) {
    try {
      const targetTab = await tabsApi.get(linkedTabObj.id);
      if (targetTab) {
        await tabsApi.update(targetTab.id, { active: true });
        const switchedTemplate = window.i18n ? window.i18n.t("switched_to_tab") : "Đã chuyển sang: {title}...";
        showToast(`⇄ ${switchedTemplate.replace("{title}", (targetTab.title || "Tab liên kết").slice(0, 24))}`);
        return;
      }
    } catch (e) {
      linkedTabObj = null;
    }
  }

  // If no linked tab yet, try finding another open tab in current window
  try {
    const allTabs = await tabsApi.query({ currentWindow: true });
    const candidateTabs = (allTabs || []).filter(t => t.id !== activeTabId && !t.url?.startsWith("chrome://") && !t.url?.startsWith("about:"));
    if (candidateTabs.length > 0) {
      const nextTab = candidateTabs[0];
      linkedTabObj = currentTabObj;
      await tabsApi.update(nextTab.id, { active: true });
      const switchedTemplate = window.i18n ? window.i18n.t("switched_to_tab") : "Đã chuyển sang: {title}...";
      showToast(`⇄ ${switchedTemplate.replace("{title}", (nextTab.title || "Tab mới").slice(0, 24))}`);
    } else {
      showToast(window.i18n ? window.i18n.t("open_another_tab_hint") : "💡 Hãy mở thêm 1 tab trang web khác để chuyển đổi qua lại!");
    }
  } catch (err) {
    console.warn("swapDualTabs failed:", err);
  }
}

async function populateDualTabDropdown() {
  const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
  const select = document.getElementById("select-linked-tab");
  if (!tabsApi || !select) return;

  while (select.firstChild) {
    select.removeChild(select.firstChild);
  }

  const defaultOpt = document.createElement("option");
  defaultOpt.value = "";
  defaultOpt.textContent = window.i18n ? window.i18n.t("select_linked_tab_opt") : "-- Chọn trang web để liên kết qua lại --";
  select.appendChild(defaultOpt);

  try {
    const allTabs = await tabsApi.query({ currentWindow: true });
    (allTabs || []).forEach(t => {
      if (t.id !== activeTabId && !t.url?.startsWith("chrome://") && !t.url?.startsWith("about:")) {
        const opt = document.createElement("option");
        opt.value = t.id.toString();
        opt.textContent = (t.title || t.url || "Tab").slice(0, 48);
        if (linkedTabObj && linkedTabObj.id === t.id) {
          opt.selected = true;
        }
        select.appendChild(opt);
      }
    });
  } catch (e) {
    console.warn("Could not query tabs for dropdown:", e);
  }
}

function toggleDualTabDropdown() {
  const dropdownBox = document.getElementById("dual-tab-dropdown-box");
  if (!dropdownBox) return;
  isDualTabDropdownOpen = !isDualTabDropdownOpen;
  dropdownBox.style.display = isDualTabDropdownOpen ? "block" : "none";
  if (isDualTabDropdownOpen) {
    populateDualTabDropdown();
  }
}

