// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/authors.js
// Multi-author parsing & formatting for IEEE/APA/Harvard/MLA/BibTeX
// Extracted from js/sidebar.js (lines 572-1006) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
function makeInitials(first) {
  if (!first) return "";
  first = first.trim();
  if (/^[A-Z]\.(\s*[A-Z]\.)*$/i.test(first)) {
    return first.split(/\s+/).join(" ");
  }
  const parts = first.split(/\s+/).filter(Boolean);
  return parts.map(p => {
    if (p.length <= 2 && p.endsWith(".")) return p.toUpperCase();
    const ch = p[0];
    return ch ? ch.toUpperCase() + "." : "";
  }).filter(Boolean).join(" ");
}

function parseAuthorParts(name) {
  name = cleanAuthorName(name);
  if (!name) return null;
  if (isOrganization(name)) {
    return { raw: name, first: "", last: name, initials: "", isOrg: true };
  }
  if (name.includes(",")) {
    const p = name.split(",");
    const last = p[0].trim();
    const first = p.slice(1).join(",").trim();
    const initials = makeInitials(first);
    const lastLow = removeVietnameseDiacritics(last).toLowerCase();
    const isVn = VIETNAMESE_SURNAMES.has(last.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastLow);
    const raw = isVn ? `${last} ${first}`.trim() : `${first} ${last}`.trim();
    return { raw, first, last, initials, isOrg: false, isVietnamese: isVn };
  }
  const words = name.split(/\s+/).filter(Boolean);
  if (words.length <= 1) {
    return { raw: name, first: "", last: words[0] || "", initials: "", isOrg: false };
  }
  const firstWordLow = removeVietnameseDiacritics(words[0]).toLowerCase();
  const isVnSurname = VIETNAMESE_SURNAMES.has(words[0].toLowerCase()) || VIETNAMESE_SURNAMES.has(firstWordLow);
  if (isVnSurname && words.length >= 2) {
    const last = words[0];
    const first = words.slice(1).join(" ");
    const initials = makeInitials(first);
    return { raw: name, first, last, initials, isOrg: false, isVietnamese: true };
  }
  const last = words[words.length - 1];
  const first = words.slice(0, words.length - 1).join(" ");
  const initials = makeInitials(first);
  return { raw: name, first, last, initials, isOrg: false };
}

function parseAuthorsList(raw) {
  if (!raw) return [];
  if (Array.isArray(raw)) {
    raw = raw.filter(Boolean).map(x => typeof x === "string" ? x : (x?.name || "")).join("; ");
  }
  if (typeof raw !== "string") {
    raw = String(raw || "");
  }
  raw = raw.trim();
  if (!raw) return [];
  if (isOrganization(raw)) {
    return [{ raw, first: "", last: raw, initials: "", isOrg: true }];
  }

  // If already semicolon or newline delimited
  if (raw.includes(";") || raw.includes("\n")) {
    const sep = raw.includes(";") ? ";" : "\n";
    return raw.split(sep)
      .map(s => s.replace(/^\s*(?:and|và|&)\s+/i, "").trim())
      .map(cleanAuthorName)
      .filter(Boolean)
      .map(parseAuthorParts)
      .filter(Boolean);
  }

  // Handle 'and' / 'và' / '&'
  let cleanStr = raw.replace(/\s*&\s*/g, " and ").replace(/\s*&amp;\s*/g, " and ").replace(/\s+và\s+/gi, " and ");

  // If there are exactly two authors joined by 'and' without Oxford comma:
  // e.g. 'Vaswani, Ashish and Shazeer, Noam' or 'Ashish Vaswani and Noam Shazeer'
  if (/\s+and\s+/i.test(cleanStr) && !/,\s+and\s+/i.test(cleanStr)) {
    const andParts = cleanStr.split(/\s+and\s+/i);
    if (andParts.length === 2 && !andParts[0].includes(";") && (andParts[0].split(",").length <= 2)) {
      return andParts.map(s => cleanAuthorName(s)).filter(Boolean).map(parseAuthorParts).filter(Boolean);
    }
  }

  // Normalise ', and ' -> ', '
  const withCommas = cleanStr.replace(/,\s+and\s+/gi, ", ").replace(/\s+and\s+/gi, ", ").trim();
  const parts = withCommas.split(",").map(s => s.trim()).filter(Boolean);

  if (parts.length <= 1) {
    return parts.map(cleanAuthorName).filter(Boolean).map(parseAuthorParts).filter(Boolean);
  }

  // Check if parts are pairs: Last, First, Last, First...
  let isPairs = parts.length >= 4 && parts.length % 2 === 0;
  if (isPairs) {
    let allHaveMultipleWords = parts.every(p => p.trim().split(/\s+/).length >= 2);
    if (allHaveMultipleWords) {
      const oddAreInitials = parts.filter((_, idx) => idx % 2 === 1).every(p => /^[A-Z]\.(\s*[A-Z]\.)*$/i.test(p.trim()));
      if (!oddAreInitials) {
        isPairs = false;
      }
    }
  }

  if (isPairs) {
    const authors = [];
    for (let i = 0; i < parts.length; i += 2) {
      authors.push(parseAuthorParts(cleanAuthorName(parts[i] + ", " + parts[i + 1])));
    }
    return authors.filter(Boolean);
  }

  return parts.map(cleanAuthorName).filter(Boolean).map(parseAuthorParts).filter(Boolean);
}

function formatSingleAuthor(author, style, formatType) {
  if (!author) return "";
  if (author.isOrg) return author.last;

  let raw = author.raw;
  let first = author.first;
  let last = author.last;
  let initials = author.initials || author.first || "";

  if (citationSettings.removeDiacritics) {
    raw = removeVietnameseDiacritics(raw);
    first = removeVietnameseDiacritics(first);
    last = removeVietnameseDiacritics(last);
    initials = removeVietnameseDiacritics(initials);
  }

  if (formatType === "ieee") {
    if (citationSettings.authorStyle === "uppercase-all") {
      return `${removeVietnameseDiacritics(initials)} ${removeVietnameseDiacritics(last)}`.toUpperCase().trim();
    }
    if (citationSettings.authorStyle === "uppercase-last") {
      return initials ? `${initials} ${last.toUpperCase()}` : last.toUpperCase();
    }
    return initials ? `${initials} ${last}` : last;
  }

  if (citationSettings.authorStyle === "original") return raw;
  if (citationSettings.authorStyle === "uppercase-all") return removeVietnameseDiacritics(raw).toUpperCase();
  if (citationSettings.authorStyle === "full") {
    return author.isVietnamese ? `${last} ${first}` : `${first} ${last}`.trim();
  }

  const isUpperLast = citationSettings.authorStyle === "uppercase-last";
  const isLastFirst = citationSettings.authorStyle === "last-first";
  const finalLast = isUpperLast ? last.toUpperCase() : last;

  if (isLastFirst || isUpperLast) {
    return initials ? `${finalLast}, ${initials}` : finalLast;
  }

  if (formatType === "apa") {
    return initials ? `${finalLast}, ${initials}` : finalLast;
  } else if (formatType === "harvard") {
    const hInitials = initials.replace(/\s+/g, "");
    return hInitials ? `${finalLast}, ${hInitials}` : finalLast;
  } else if (formatType === "mla") {
    const fullFirst = first || initials;
    return fullFirst ? `${finalLast}, ${fullFirst}` : finalLast;
  } else if (formatType === "bibtex") {
    const fullFirst = first || initials;
    return fullFirst ? `${finalLast}, ${fullFirst}` : finalLast;
  }
  return initials ? `${initials} ${finalLast}` : finalLast;
}

function formatIeeeAuthors(raw) {
  const authors = parseAuthorsList(raw);
  if (authors.length === 0) return "";
  if (authors.length === 1) return formatSingleAuthor(authors[0], citationSettings.authorStyle, "ieee");
  if (authors.length === 2) {
    return `${formatSingleAuthor(authors[0], citationSettings.authorStyle, "ieee")} and ${formatSingleAuthor(authors[1], citationSettings.authorStyle, "ieee")}`;
  }
  if (authors.length <= 6) {
    const list = authors.map(a => formatSingleAuthor(a, citationSettings.authorStyle, "ieee"));
    return `${list.slice(0, -1).join(", ")}, and ${list[list.length - 1]}`;
  }
  return `${formatSingleAuthor(authors[0], citationSettings.authorStyle, "ieee")} et al.`;
}

function formatApaAuthors(raw) {
  const authors = parseAuthorsList(raw);
  if (authors.length === 0) return "";
  if (authors.length === 1) return formatSingleAuthor(authors[0], citationSettings.authorStyle, "apa");
  if (authors.length === 2) {
    return `${formatSingleAuthor(authors[0], citationSettings.authorStyle, "apa")} & ${formatSingleAuthor(authors[1], citationSettings.authorStyle, "apa")}`;
  }
  if (authors.length <= 20) {
    const list = authors.map(a => formatSingleAuthor(a, citationSettings.authorStyle, "apa"));
    return `${list.slice(0, -1).join(", ")}, & ${list[list.length - 1]}`;
  }
  const first19 = authors.slice(0, 19).map(a => formatSingleAuthor(a, citationSettings.authorStyle, "apa"));
  const lastAuthor = formatSingleAuthor(authors[authors.length - 1], citationSettings.authorStyle, "apa");
  return `${first19.join(", ")}, ... ${lastAuthor}`;
}

function formatHarvardAuthors(raw) {
  const authors = parseAuthorsList(raw);
  if (authors.length === 0) return "";
  if (authors.length === 1) return formatSingleAuthor(authors[0], citationSettings.authorStyle, "harvard");
  if (authors.length === 2) {
    return `${formatSingleAuthor(authors[0], citationSettings.authorStyle, "harvard")} and ${formatSingleAuthor(authors[1], citationSettings.authorStyle, "harvard")}`;
  }
  if (authors.length === 3) {
    const list = authors.map(a => formatSingleAuthor(a, citationSettings.authorStyle, "harvard"));
    return `${list[0]}, ${list[1]} and ${list[2]}`;
  }
  return `${formatSingleAuthor(authors[0], citationSettings.authorStyle, "harvard")} et al.`;
}

function formatMlaAuthors(raw) {
  const authors = parseAuthorsList(raw);
  if (authors.length === 0) return "";
  if (authors.length === 1) return formatSingleAuthor(authors[0], citationSettings.authorStyle, "mla");
  if (authors.length === 2) {
    const a1 = formatSingleAuthor(authors[0], citationSettings.authorStyle, "mla");
    const a2 = authors[1].isOrg ? authors[1].last : `${authors[1].first || authors[1].initials} ${authors[1].last}`.trim();
    return `${a1}, and ${a2}`;
  }
  return `${formatSingleAuthor(authors[0], citationSettings.authorStyle, "mla")}, et al.`;
}

function formatBibtexAuthors(raw) {
  const authors = parseAuthorsList(raw);
  if (authors.length === 0) return "";
  return authors.map(a => {
    if (a.isOrg) return `{${a.last}}`;
    return formatSingleAuthor(a, "standard", "bibtex");
  }).join(" and ");
}

function parseComprehensiveDate(raw) {
  if (!raw) return "";
  let s = raw.toString().trim();
  if (!s) return "";

  // 0. Unix timestamp (seconds: 10 digits, or millis: 13 digits)
  if (/^\d{10}$/.test(s)) {
    const d = new Date(parseInt(s, 10) * 1000);
    if (!isNaN(d.getTime()) && d.getFullYear() >= 1990 && d.getFullYear() <= 2035) {
      return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
    }
  }
  if (/^\d{13}$/.test(s)) {
    const d = new Date(parseInt(s, 10));
    if (!isNaN(d.getTime()) && d.getFullYear() >= 1990 && d.getFullYear() <= 2035) {
      return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
    }
  }

  // Check if string contains multiple dates with explicit "published" vs "updated" labels
  const pubSectionMatch = s.match(/(?:ngày\s*đăng|đăng\s*(?:ngày|lúc)?|xuất\s*bản|công\s*bố|published\s*(?:on|at)?|posted\s*(?:on|at)?|дата\s*публикации|опубликовано|发布时间|发布于|公開日|更新日|release\s*date)\s*[:\-–,]?\s*([^|\n–—]+?)(?=(?:\s*[-–—|•]\s*(?:cập\s*nhật|updated|modified|last\s*modified|last\s*updated))|\s*$)/i);
  if (pubSectionMatch) {
    s = pubSectionMatch[1].trim();
  }

  // 1. Full ISO timestamp (e.g. "2009-10-24T23:57:33-07:00" or "2026-09-05T22:57:50Z" or "2024/05/18")
  const isoYmdMatch = s.match(/\b(19\d\d|20\d\d)[-/.](\d{1,2})[-/.](\d{1,2})(?:T|\s|$|[^\d])/);
  if (isoYmdMatch) {
    const y = isoYmdMatch[1];
    const m = isoYmdMatch[2].padStart(2, "0");
    const d = isoYmdMatch[3].padStart(2, "0");
    if (parseInt(m, 10) >= 1 && parseInt(m, 10) <= 12 && parseInt(d, 10) >= 1 && parseInt(d, 10) <= 31) {
      return `${y}-${m}-${d}`;
    }
  }

  // 2. Remove prefixes in Vietnamese, English, French, Spanish, Russian, Chinese, Japanese
  s = s.replace(/^(?:updated\s*(?:on|at)?|published\s*(?:on|at)?|posted\s*(?:on|at)?|modified\s*(?:on|at)?|uploaded\s*on|streamed\s*live\s*(?:on)?|streamed\s*(?:on)?|premiered\s*(?:on)?|đã\s*công\s*chiếu\s*(?:vào)?|đã\s*phát\s*trực\s*tiếp\s*(?:vào)?|công\s*chiếu\s*(?:vào)?|phát\s*trực\s*tiếp\s*(?:vào)?|đã\s*tải\s*lên\s*(?:vào)?|xuất bản|ngày đăng|đăng lúc|cập nhật|thứ\s+[a-z0-9]+|chủ nhật|monday|tuesday|wednesday|thursday|friday|saturday|sunday|mon|tue|wed|thu|fri|sat|sun|опубликовано|дата\s*публикации|发布时间|发布于|公開日)\s*[:\-–,]?\s*/i, "").trim();

  // 3. Relative dates
  const now = new Date();
  if (/(\d+)\s*(?:giờ|phút|giây|hours?|mins?|minutes?|secs?|seconds?|часов?|минут?|小时|分钟|分前|時間前)\s*(?:trước|ago|назад|前)/i.test(s) || /vừa xong|just now|только что|刚刚/i.test(s)) {
    return now.toISOString().split("T")[0];
  }
  const relDayMatch = s.match(/(\d+)\s*(?:ngày\s*trước|days?\s*ago|дней\s*назад|дня\s*назад|день\s*назад|天前|日前)/i);
  if (relDayMatch) {
    const d = new Date(now.getTime() - parseInt(relDayMatch[1], 10) * 86400000);
    return d.toISOString().split("T")[0];
  }
  const relWeekMatch = s.match(/(\d+)\s*(?:tuần\s*trước|weeks?\s*ago|недел[ьия]\s*назад|周前|週間前)/i);
  if (relWeekMatch) {
    const d = new Date(now.getTime() - parseInt(relWeekMatch[1], 10) * 7 * 86400000);
    return d.toISOString().split("T")[0];
  }
  const relMonthMatch = s.match(/(\d+)\s*(?:tháng\s*trước|months?\s*ago|месяц(?:ев|а)?\s*назад|个月前|ヶ月前)/i);
  if (relMonthMatch) {
    const d = new Date(now.getFullYear(), now.getMonth() - parseInt(relMonthMatch[1], 10), now.getDate());
    return d.toISOString().split("T")[0];
  }
  const relYearMatch = s.match(/(\d+)\s*(?:năm\s*trước|years?\s*ago|лет\s*назад|года?\s*назад|年前)/i);
  if (relYearMatch) {
    const yr = now.getFullYear() - parseInt(relYearMatch[1], 10);
    return `${yr}`;
  }
  if (/hôm qua|yesterday|вчера|昨天|昨日/i.test(s)) {
    const d = new Date(now.getTime() - 86400000);
    return d.toISOString().split("T")[0];
  }

  // 4. Chinese & Japanese: 2024年5月18日 or 2024年05月
  const cjMatch = s.match(/\b(19\d\d|20\d\d)\s*年\s*(\d{1,2})\s*月(?:\s*(\d{1,2})\s*日)?/);
  if (cjMatch) {
    const y = cjMatch[1];
    const m = cjMatch[2].padStart(2, "0");
    if (cjMatch[3]) {
      const d = cjMatch[3].padStart(2, "0");
      return `${y}-${m}-${d}`;
    }
    return `${y}-${m}`;
  }

  // 5. Vietnamese phrase: "ngày 06 tháng 09 năm 2026", "16 thg 8, 2026", "tháng ba, 2024"
  const vnWordMonths = {
    "một": "01", "giêng": "01", "hai": "02", "ba": "03", "bốn": "04", "tư": "04",
    "năm": "05", "sáu": "06", "bảy": "07", "tám": "08", "chín": "09",
    "mười": "10", "mười một": "11", "mười hai": "12", "chạp": "12"
  };
  const vnPhraseMatch = s.match(/(?:ngày\s+)?(\d{1,2})\s+(?:tháng|thg)\s+(\d{1,2}|một|giêng|hai|ba|bốn|tư|năm|sáu|bảy|tám|chín|mười|mười\s+một|mười\s+hai)(?:,?\s+năm|\s*,)?\s+(19\d\d|20\d\d)/i);
  if (vnPhraseMatch) {
    const d = vnPhraseMatch[1].padStart(2, "0");
    const rawM = vnPhraseMatch[2].toLowerCase().trim();
    const m = vnWordMonths[rawM] || rawM.padStart(2, "0");
    const y = vnPhraseMatch[3];
    return `${y}-${m}-${d}`;
  }
  const vnMonthYear = s.match(/(?:tháng|thg)\s+(\d{1,2}|một|giêng|hai|ba|bốn|tư|năm|sáu|bảy|tám|chín|mười|mười\s+một|mười\s+hai)(?:,?\s+năm|\s*,)?\s+(19\d\d|20\d\d)/i);
  if (vnMonthYear) {
    const rawM = vnMonthYear[1].toLowerCase().trim();
    const m = vnWordMonths[rawM] || rawM.padStart(2, "0");
    const y = vnMonthYear[2];
    return `${y}-${m}`;
  }

  // 6. Multi-language Month Names (English, Russian, French, German, Spanish/Portuguese)
  const allMonths = {
    jan: "01", january: "01", feb: "02", february: "02", mar: "03", march: "03", apr: "04", april: "04",
    may: "05", jun: "06", june: "06", jul: "07", july: "07", aug: "08", august: "08", sep: "09", sept: "09",
    september: "09", oct: "10", october: "10", nov: "11", november: "11", dec: "12", december: "12",
    "января": "01", "январь": "01", "янв": "01",
    "февраля": "02", "февраль": "02", "фев": "02",
    "марта": "03", "март": "03", "мар": "03",
    "апреля": "04", "апрель": "04", "апр": "04",
    "мая": "05", "май": "05",
    "июня": "06", "июнь": "06", "июн": "06",
    "июля": "07", "июль": "07", "июл": "07",
    "августа": "08", "август": "08", "авг": "08",
    "сентября": "09", "сентябрь": "09", "сен": "09", "сент": "09",
    "октября": "10", "октябрь": "10", "окт": "10",
    "ноября": "11", "ноябрь": "11", "ноя": "11",
    "декабря": "12", "декабрь": "12", "дек": "12",
    "janvier": "01", "enero": "01", "janeiro": "01", "januar": "01",
    "février": "02", "febrero": "02", "fevereiro": "02", "februar": "02",
    "mars": "03", "marzo": "03", "março": "03", "märz": "03",
    "avril": "04", "abril": "04",
    "mai": "05", "mayo": "05", "maio": "05",
    "juin": "06", "junio": "06", "junho": "06", "juni": "06",
    "juillet": "07", "julio": "07", "julho": "07", "juli": "07",
    "août": "08", "agosto": "08",
    "septembre": "09", "setiembre": "09", "setembro": "09",
    "octobre": "10", "octubre": "10", "outubro": "10", "oktober": "10",
    "novembre": "11", "noviembre": "11", "novembro": "11",
    "décembre": "12", "diciembre": "12", "dezembro": "12", "dezember": "12"
  };

  const monthKeysRegex = Object.keys(allMonths).sort((a, b) => b.length - a.length).join("|");

  // Format: "Month DD, YYYY" (e.g. September 12, 2026)
  const mMatch1 = s.match(new RegExp(`\\b(${monthKeysRegex})\\.?\\s+(\\d{1,2})(?:st|nd|rd|th)?,?\\s+(19\\d\\d|20\\d\\d)\\b`, "i"));
  if (mMatch1) {
    const m = allMonths[mMatch1[1].toLowerCase().replace(".", "")];
    const d = mMatch1[2].padStart(2, "0");
    const y = mMatch1[3];
    if (m) return `${y}-${m}-${d}`;
  }

  // Format: "DD Month YYYY" or "DD de Month de YYYY" (e.g. 18 мая 2024, 18 de mayo de 2024, 12 Sep 2026)
  const mMatch2 = s.match(new RegExp(`\\b(\\d{1,2})(?:st|nd|rd|th)?\\s*(?:de|d[\x27\x60])?\\s*(${monthKeysRegex})\\.?\\s*(?:de|,)?\\s+(19\\d\\d|20\\d\\d)\\b`, "i"));
  if (mMatch2) {
    const d = mMatch2[1].padStart(2, "0");
    const m = allMonths[mMatch2[2].toLowerCase().replace(".", "")];
    const y = mMatch2[3];
    if (m) return `${y}-${m}-${d}`;
  }

  // Format: "YYYY, Month DD" or "YYYY Month DD"
  const mMatchYmd = s.match(new RegExp(`\\b(19\\d\\d|20\\d\\d),?\\s+(${monthKeysRegex})\\.?\\s+(\\d{1,2})(?:st|nd|rd|th)?\\b`, "i"));
  if (mMatchYmd) {
    const y = mMatchYmd[1];
    const m = allMonths[mMatchYmd[2].toLowerCase().replace(".", "")];
    const d = mMatchYmd[3].padStart(2, "0");
    if (m) return `${y}-${m}-${d}`;
  }

  // Format: Month + Year: "September 2026" or "мая 2024"
  const mMatch3 = s.match(new RegExp(`\\b(${monthKeysRegex})\\.?\\s*,?\\s+(19\\d\\d|20\\d\\d)\\b`, "i"));
  if (mMatch3) {
    const m = allMonths[mMatch3[1].toLowerCase().replace(".", "")];
    const y = mMatch3[2];
    if (m) return `${y}-${m}`;
  }

  // 7. Day-Month-Year: "06/09/2026", "6.9.2026", "06-09-2026"
  const dmyMatch = s.match(/\b(\d{1,2})[./-](\d{1,2})[./-](19\d\d|20\d\d)\b/);
  if (dmyMatch) {
    const d = dmyMatch[1].padStart(2, "0");
    const m = dmyMatch[2].padStart(2, "0");
    const y = dmyMatch[3];
    if (parseInt(m, 10) >= 1 && parseInt(m, 10) <= 12 && parseInt(d, 10) >= 1 && parseInt(d, 10) <= 31) {
      return `${y}-${m}-${d}`;
    }
  }

  // 8. Year-Month: "2024-05", "2024/05", "2024.05"
  const ymMatch = s.match(/\b(19\d\d|20\d\d)[-/.](\d{1,2})\b/);
  if (ymMatch) {
    const y = ymMatch[1];
    const m = ymMatch[2].padStart(2, "0");
    if (parseInt(m, 10) >= 1 && parseInt(m, 10) <= 12) {
      return `${y}-${m}`;
    }
  }

  // 9. Year only fallback
  const yMatch = s.match(/\b(19\d\d|20\d\d)\b/);
  if (yMatch) return yMatch[1];

  return "";
}

