// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/builders.js
// IEEE/APA/Harvard/MLA/BibTeX/in-text citation builders
// Extracted from js/sidebar.js (lines 1473-2024) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
function extractYear(raw) {
  if (!raw) return "";
  const parsed = parseComprehensiveDate(raw);
  const m = (parsed || raw || "").match(/\b(19\d\d|20\d\d)\b/);
  return m ? m[0] : "";
}

function generateBibtexKey(authors, date, title) {
  const auths = parseAuthorsList(authors);
  const a = (auths[0]?.last || (authors ? authors.split(/[,;\s]/)[0] : "") || "ref").toLowerCase().replace(/[^a-z0-9]/g, "");
  const y = extractYear(date) || new Date().getFullYear().toString();
  const w = (title || "").toLowerCase().split(/[^a-z0-9]+/).filter(x => x.length > 2 && !["the", "and", "for"].includes(x))[0] || "article";
  return `${a}${y}${w}`;
}

function buildIeeeCitation(meta) {
  const a = formatIeeeAuthors(meta.authors);
  let cleanTitle = (meta.title || "Untitled").trim()
    .replace(/^(?:Frontiers|Nature|Science|Springer|Elsevier|Wiley|PLOS|ACM|IEEE)\s*\|\s*/i, "")
    .replace(/[,\.]+$/, "");
  const y = extractYear(meta.date) || (meta.date ? meta.date.trim() : "n.d.");
  const dateIeee = meta.date ? formatCitationDate(meta.date, "ieee") : y;
  const dateIeeeMonthYear = citationSettings.dateStyle === "full" ? dateIeee : dateIeee.replace(/\s\d{1,2},/, "");
  
  let prefix = "";
  if (a && a.toLowerCase() !== cleanTitle.toLowerCase()) {
    prefix = `${a}, `;
  }

  switch (meta.sourceType) {
    case "academic":
      let resAcad = `${prefix}"${cleanTitle}," `;
      if (meta.container) resAcad += `*${meta.container.trim()}*, `;
      if (meta.pages) {
        let p = meta.pages.trim().replace(/[,\.]+$/, "");
        if (/^\d+(?:[-–]\d+)?$/.test(p)) p = `pp. ${p}`;
        resAcad += `${p}, `;
      }
      resAcad += `${dateIeeeMonthYear}`;
      if (meta.doi) {
        resAcad += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url) {
        resAcad += `. [Online]. Available: ${meta.url}.`;
        if (citationSettings.accessedDate) resAcad += ` [${t('i18n_accessed')}: ${meta.accessed || getTodayIeee()}].`;
      } else {
        resAcad += `.`;
      }
      return resAcad;

    case "conference":
      let resConf = `${prefix}"${cleanTitle}," in *${meta.container ? meta.container.trim() : "Proc. Conference"}*, ${dateIeeeMonthYear}`;
      if (meta.pages) {
        let p = meta.pages.trim().replace(/[,\.]+$/, "");
        if (/^\d+(?:[-–]\d+)?$/.test(p)) p = `pp. ${p}`;
        resConf += `, ${p}`;
      }
      if (meta.doi) {
        resConf += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url) {
        resConf += `. [Online]. Available: ${meta.url}.`;
        if (citationSettings.accessedDate) resConf += ` [${t('i18n_accessed')}: ${meta.accessed || getTodayIeee()}].`;
      } else {
        resConf += `.`;
      }
      return resConf;

    case "book":
      let resBook = `${prefix}*${cleanTitle}*`;
      if (meta.pages && meta.pages.toLowerCase().includes("ed")) resBook += `, ${meta.pages.trim()}`;
      if (meta.container) resBook += `. ${meta.container.trim()}`;
      resBook += `, ${dateIeee}`;
      if (meta.doi) {
        resBook += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else {
        resBook += `.`;
      }
      return resBook;

    case "pdf":
      let repLabel = "Tech. Rep.";
      if (meta.pages) {
        const pTrim = meta.pages.trim();
        if (/^(?:rep|tr|no|báo cáo|report)\b/i.test(pTrim)) {
          repLabel = pTrim;
        } else if (/^\d+[-\d]*$/.test(pTrim) || /^pp\./i.test(pTrim)) {
          repLabel = `Tech. Rep., ${pTrim.startsWith("pp.") ? pTrim : "pp. " + pTrim}`;
        } else {
          repLabel = `Rep. ${pTrim}`;
        }
      }
      let resRep = `${prefix}"${cleanTitle}," ${meta.container ? meta.container.trim() + ", " : ""}${repLabel}, ${dateIeee}`;
      if (meta.doi) {
        resRep += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        resRep += `. [Online]. Available: ${meta.url}.`;
        if (citationSettings.accessedDate) {
          resRep += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
        }
      } else {
        resRep += `.`;
      }
      return resRep;

    case "software":
      let ver = meta.pages ? `version ${meta.pages.trim()}, ` : "";
      let resSoft = `${prefix}*${cleanTitle}*, ${ver}${meta.container ? meta.container.trim() + ", " : ""}${dateIeee}. [Online]. Available: ${meta.url}`;
      if (citationSettings.accessedDate) resSoft += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
      return resSoft;

    case "video":
      const vDateIeee = meta.date ? formatCitationDate(meta.date, "ieee") : y;
      let resVid = `${prefix}"${cleanTitle}," *${meta.container || "YouTube"}*, ${vDateIeee}. [Online Video]. Available: ${meta.url}`;
      if (citationSettings.accessedDate) resVid += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
      return resVid;

    default:
      let resWeb = `${prefix}"${cleanTitle}," `;
      if (meta.container && meta.container.trim() !== cleanTitle) resWeb += `*${meta.container.trim()}*, `;
      const wDateIeee = meta.date ? formatCitationDate(meta.date, "ieee") : y;
      resWeb += `${wDateIeee}. [Online]. Available: ${meta.url}.`;
      if (citationSettings.accessedDate) {
        resWeb += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
      }
      return resWeb;
  }
}

function buildApaCitation(meta) {
  const a = formatApaAuthors(meta.authors) || meta.container || "Author";
  const y = extractYear(meta.date) || "n.d.";
  const isWebOrMedia = ["webpage", "video", "software"].includes(meta.sourceType);
  const formattedDate = isWebOrMedia && meta.date ? formatCitationDate(meta.date, "apa") : y;
  const d = `(${formattedDate || y})`;
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");

  let out = `${a} ${d}. `;

  switch (meta.sourceType) {
    case "academic":
      out += `${cleanTitle}. `;
      if (meta.container) out += `*${meta.container.trim()}*`;
      if (meta.pages) out += `, ${meta.pages.trim()}`;
      out += `. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "conference":
      out += `${cleanTitle}. In *${meta.container || "Conference Proceedings"}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      out += `. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "book":
      out += `*${cleanTitle}*`;
      if (meta.pages && meta.pages.toLowerCase().includes("ed")) out += ` (${meta.pages.trim()})`;
      out += `. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "pdf":
      out += `*${cleanTitle}*`;
      if (meta.pages) {
        const pTrim = meta.pages.trim();
        out += ` (${/^(?:report|rep|no|white\s*paper)\b/i.test(pTrim) ? pTrim : "Report No. " + pTrim})`;
      } else {
        out += ` [PDF]`;
      }
      out += `. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) {
        out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        out += meta.url;
        if (citationSettings.accessedDate) {
          out += ` (Retrieved ${meta.accessed || getTodayApa()}, from ${meta.url})`;
        }
      }
      break;

    case "software":
      out += `*${cleanTitle}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      out += ` [Computer software]. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.url) out += meta.url;
      break;

    case "video":
      out += `*${cleanTitle}* [Video]. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.url) out += meta.url;
      break;

    default:
      out += `*${cleanTitle}*. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      out += meta.url;
      if (citationSettings.accessedDate) {
        out += ` (Retrieved ${meta.accessed || getTodayApa()}, from ${meta.url})`;
      }
      break;
  }
  return out.trim();
}

function buildHarvardCitation(meta) {
  const a = formatHarvardAuthors(meta.authors) || meta.container || "Author";
  const y = extractYear(meta.date) || "n.d.";
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");

  let out = `${a} (${y}) `;

  switch (meta.sourceType) {
    case "academic":
      out += `'${cleanTitle}', *${meta.container || "Journal"}*`;
      if (meta.pages) out += `, ${meta.pages.trim()}`;
      out += `.`;
      if (meta.doi) out += ` Available at: https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      break;

    case "conference":
      out += `'${cleanTitle}', in *${meta.container || "Conference Proceedings"}*`;
      if (meta.pages) out += `, pp. ${meta.pages.trim()}`;
      out += `.`;
      break;

    case "book":
      out += `*${cleanTitle}*. `;
      if (meta.container) out += `${meta.container.trim()}.`;
      break;

    case "pdf":
      out += `*${cleanTitle}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      out += ` [PDF]. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) {
        out += `Available at: https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        out += `Available at: ${meta.url}`;
        if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
        out += `.`;
      }
      break;

    case "software":
      out += `*${cleanTitle}* [Computer program]. Available at: ${meta.url}`;
      if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
      out += `.`;
      break;

    case "video":
      out += `'${cleanTitle}' [Online video]. Available at: ${meta.url}`;
      if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
      out += `.`;
      break;

    default:
      out += `*${cleanTitle}*, ${meta.container || "Website"}. Available at: ${meta.url}`;
      if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
      out += `.`;
      break;
  }
  return out.trim();
}

function buildMlaCitation(meta) {
  const a = formatMlaAuthors(meta.authors);
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");
  const y = extractYear(meta.date);

  let out = a ? (a.endsWith(".") ? `${a} ` : `${a}. `) : "";

  switch (meta.sourceType) {
    case "academic":
      out += `"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container.trim()}*, `;
      if (meta.pages) out += `${meta.pages.trim()}, `;
      out += `${y}. `;
      if (meta.doi) out += `doi:${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      else if (meta.url) out += `${meta.url}.`;
      break;

    case "conference":
      out += `"${cleanTitle}." *${meta.container || "Conference Proceedings"}*, ${y}`;
      if (meta.pages) out += `, pp. ${meta.pages.trim()}`;
      out += `.`;
      break;

    case "book":
      out += `*${cleanTitle}*. `;
      if (meta.container) out += `${meta.container.trim()}, `;
      out += `${y}.`;
      break;

    case "pdf":
      out += `*${cleanTitle}*. `;
      if (meta.pages) out += `${meta.pages.trim()}, `;
      if (meta.container) out += `${meta.container.trim()}, `;
      out += `${y}, `;
      if (meta.doi) {
        out += `doi:${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        out += `${meta.url}.`;
        if (citationSettings.accessedDate) {
          out += ` Accessed ${meta.accessed || getTodayIeee()}.`;
        }
      } else {
        out = out.replace(/,\s*$/, ".");
      }
      break;

    case "video":
      const vDateMla = meta.date ? formatCitationDate(meta.date, "mla") : y;
      return `${out}"${cleanTitle}." *${meta.container || "YouTube"}*, ${vDateMla}, ${meta.url}.`;

    default:
      out += `"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container.trim()}*, `;
      const wDateMla = meta.date ? formatCitationDate(meta.date, "mla") : y;
      out += `${wDateMla}, `;
      out += `${meta.url}.`;
      if (citationSettings.accessedDate) {
        out += ` Accessed ${meta.accessed || getTodayIeee()}.`;
      }
      break;
  }
  return out.trim();
}

function buildBibtexCitation(meta) {
  const key = generateBibtexKey(meta.authors, meta.date, meta.title);
  const y = extractYear(meta.date);
  const authorField = formatBibtexAuthors(meta.authors);

  let type = "misc";
  switch (meta.sourceType) {
    case "academic": type = "article"; break;
    case "conference": type = "inproceedings"; break;
    case "book": type = "book"; break;
    case "pdf": type = "techreport"; break;
    case "software": type = "software"; break;
    default: type = "misc"; break;
  }

  let lines = [`@${type}{${key},`];
  if (authorField) {
    lines.push(`  author = {${authorField}},`);
  }
  const cleanTitle = (meta.title || "Untitled").trim().replace(/^(?:Frontiers|Nature|Science|Springer|Elsevier|Wiley|PLOS|ACM|IEEE)\s*\|\s*/i, "");
  lines.push(`  title = {{${cleanTitle}}},`);

  if (type === "article") {
    if (meta.container) lines.push(`  journal = {${meta.container}},`);
        if (meta.pages) {
       let vol = "", num = "", pp = meta.pages;
       const vMatch = pp.match(/vol\.?\s*(\d+)/i);
       const nMatch = pp.match(/(?:no\.?|issue)\s*(\d+)/i);
       if (vMatch) {
           vol = vMatch[1];
           pp = pp.replace(vMatch[0], "");
       }
       if (nMatch) {
           num = nMatch[1];
           pp = pp.replace(nMatch[0], "");
       }
       pp = pp.replace(/[^0-9\-–]/g, "").trim();
       if (vol) lines.push(`  volume = {${vol}},`);
       if (num) lines.push(`  number = {${num}},`);
       if (pp) lines.push(`  pages = {${pp}},`);
    }
  } else if (type === "inproceedings") {
    if (meta.container) lines.push(`  booktitle = {${meta.container}},`);
        if (meta.pages) {
       let vol = "", num = "", pp = meta.pages;
       const vMatch = pp.match(/vol\.?\s*(\d+)/i);
       const nMatch = pp.match(/(?:no\.?|issue)\s*(\d+)/i);
       if (vMatch) {
           vol = vMatch[1];
           pp = pp.replace(vMatch[0], "");
       }
       if (nMatch) {
           num = nMatch[1];
           pp = pp.replace(nMatch[0], "");
       }
       pp = pp.replace(/[^0-9\-–]/g, "").trim();
       if (vol) lines.push(`  volume = {${vol}},`);
       if (num) lines.push(`  number = {${num}},`);
       if (pp) lines.push(`  pages = {${pp}},`);
    }
  } else if (type === "book") {
    if (meta.container) lines.push(`  publisher = {${meta.container}},`);
  } else if (type === "techreport") {
    if (meta.container) lines.push(`  institution = {${meta.container}},`);
    if (meta.pages) lines.push(`  number = {${meta.pages}},`);
    lines.push(`  type = {Technical Report},`);
  } else if (type === "software") {
    if (meta.pages) lines.push(`  version = {${meta.pages}},`);
  } else {
    if (meta.container) lines.push(`  howpublished = {${meta.container}},`);
  }

  const parsedDate = parseComprehensiveDate(meta.date);
  const mYmd = (parsedDate || meta.date || "").match(/^(?:19\d\d|20\d\d)-(\d{1,2})/);
  if (mYmd) {
    const bibMonths = ["", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
    const mIdx = parseInt(mYmd[1], 10);
    if (mIdx >= 1 && mIdx <= 12) {
      lines.push(`  month = {${bibMonths[mIdx]}},`);
    }
  }

  lines.push(`  year = {${y}},`);
  if (meta.doi) lines.push(`  doi = {${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}},`);
  if (meta.url && !meta.url.startsWith("file://")) {
    lines.push(`  url = {${meta.url}},`);
  }
  if (meta.notes) {
    lines.push(`  note = {${meta.notes.replace(/[\r\n]+/g, " ").trim()}},`);
  }
  if (meta.tag) {
    lines.push(`  keywords = {${meta.tag.trim()}},`);
  }
  // Trim trailing comma from last field line
  if (lines.length > 1) {
    const lastIdx = lines.length - 1;
    lines[lastIdx] = lines[lastIdx].replace(/,$/, "");
  }
  lines.push(`}`);
  return lines.join("\n");
}

function buildIntextCitation(meta) {
  const authors = parseAuthorsList(meta.authors);
  const y = extractYear(meta.date);

  let a1 = "";
  let ieeeAuthorInText = "";
  let apaParenthetical = "";
  let apaNarrative = "";

  if (authors.length === 0) {
    const site = meta.container || "Tác giả";
    ieeeAuthorInText = site;
    apaParenthetical = `(${site}, ${y})`;
    apaNarrative = `${site} (${y})`;
  } else if (authors.length === 1) {
    a1 = authors[0].isOrg ? authors[0].last : authors[0].last;
    ieeeAuthorInText = a1;
    apaParenthetical = `(${a1}, ${y})`;
    apaNarrative = `${a1} (${y})`;
  } else if (authors.length === 2) {
    a1 = authors[0].last;
    const a2 = authors[1].last;
    ieeeAuthorInText = `${a1} and ${a2}`;
    apaParenthetical = `(${a1} & ${a2}, ${y})`;
    apaNarrative = `${a1} và ${a2} (${y})`;
  } else {
    a1 = authors[0].last;
    ieeeAuthorInText = `${a1} et al.`;
    apaParenthetical = `(${a1} et al., ${y})`;
    apaNarrative = `${a1} et al. (${y})`;
  }

  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  if (lang === "en") {
    return `IEEE STANDARD (Numbered [1]):
• Direct Citation: "...as previously reported in [1]."
• Narrative Citation: "According to ${ieeeAuthorInText} [1], this approach..."
• Multiple Sources: "...consistent findings were documented in [1], [2], [4]–[6]."

───────────────────────────────────
APA 7th EDITION (Author-Date):
• Parenthetical: "...demonstrating the viability of the approach ${apaParenthetical}."
• Narrative: "${apaNarrative} demonstrated that the algorithm achieves high accuracy."

───────────────────────────────────
Multiple Authors Rule:
• 1 author: (${a1}, ${y})
• 2 authors: (${a1} & ${authors[1]?.last || "Author"}, ${y})
• ≥ 3 authors: (${a1} et al., ${y}) used from the very first citation.`;
  } else if (lang === "zh") {
    return `IEEE 国际标准（序号引用 [1]）：
• 句末直接引用：“...正如文献 [1] 中所阐明的那样。”
• 叙述性文内引用：“根据 ${ieeeAuthorInText} [1] 的研究，该模型表现优异...”
• 多个连续文献引用：“...在文献 [1], [2], [4]–[6] 中均得出了类似结论。”

───────────────────────────────────
APA 第 7 版标准（著者-出版年）：
• 括号内引用（Parenthetical）：“...证明了该算法的有效性 ${apaParenthetical}。”
• 叙述性引用（Narrative）：“${apaNarrative} 指出该深度神经网络达到了极高的识别精度。”

───────────────────────────────────
多著者引用规范：
• 1 位作者：(${a1}, ${y})
• 2 位作者：(${a1} & ${authors[1]?.last || "李四"}, ${y})
• ≥ 3 位作者：(${a1} et al., ${y}) 首次提及即可直接使用。`;
  } else if (lang === "ru") {
    return `СТАНДАРТ IEEE (Нумерация [1]):
• Прямая ссылка: «...как было показано в исследовании [1].»
• В повествовании: «Согласно исследованию ${ieeeAuthorInText} [1], данная модель...»
• Несколько источников: «...аналогичные результаты приведены в [1], [2], [4]–[6].»

───────────────────────────────────
СТАНДАРТ APA 7-е издание (Автор-Год):
• В скобках (Parenthetical): «...что подтверждает эффективность предложенного метода ${apaParenthetical}.»
• В повествовании (Narrative): «${apaNarrative} установили высокую точность алгоритма.»

───────────────────────────────────
Правила для нескольких авторов:
• 1 автор: (${a1}, ${y})
• 2 автора: (${a1} & ${authors[1]?.last || "Иванов"}, ${y})
• ≥ 3 авторов: (${a1} et al., ${y}) используется с первого упоминания.`;
  } else if (lang === "ja") {
    return `IEEE 国際標準 (番号順 [1]):
• 文末直接引用: 「...文献 [1] で報告されているように。」
• 本文記述 (Narrative): 「${ieeeAuthorInText} [1] の研究によれば、この手法は...」
• 複数文献の連続引用: 「...同様の結果が [1], [2], [4]–[6] でも報告されている。」

───────────────────────────────────
APA 第7版標準 (著者-刊行年):
• 括弧内引用 (Parenthetical): 「...本手法の有効性が示された ${apaParenthetical}。」
• 本文記述 (Narrative): 「${apaNarrative} は、提案アルゴリズムが高い精度を達成することを実証した。」

───────────────────────────────────
複数著者の表記規則:
• 著者1名: (${a1}, ${y})
• 著者2名: (${a1} & ${authors[1]?.last || "佐藤"}, ${y})
• 著者3名以上: (${a1} et al., ${y}) 初回言及時から即座に使用。`;
  }

  return `CHUẨN IEEE (Số thứ tự [1]):
• Cuối câu (Trực tiếp): "...như đã được công bố trong tài liệu [1]."
• Mạch văn (Narrative): "Theo nghiên cứu của ${ieeeAuthorInText} [1], mô hình này..."
• Nhiều nguồn liên tiếp: "...các kết quả tương tự cũng được tìm thấy trong [1], [2], [4]–[6]."

───────────────────────────────────
CHUẨN APA 7th (Tác giả - Năm):
• Trong ngoặc (Parenthetical): "...đã chứng minh được tính khả thi của giải pháp ${apaParenthetical}."
• Tường thuật (Narrative): "${apaNarrative} đã chỉ ra rằng thuật toán đạt độ chính xác cao."

───────────────────────────────────
Quy tắc nhiều tác giả:
• 1 tác giả: (${a1}, ${y})
• 2 tác giả: (${a1} & ${authors[1]?.last || "Trần"}, ${y})
• ≥ 3 tác giả: (${a1} et al., ${y}) dùng ngay từ lần trích đầu tiên.`;
}

