// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/builders.js
// IEEE/APA/Harvard/MLA/BibTeX/in-text citation builders
// Extracted from js/sidebar.js (lines 1473-2024) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
function extractYear(raw) {
  if (!raw) return "";
  const parsed = parseComprehensiveDate(raw);
  const m = (parsed || raw || "").match(/\b(19\d\d|20\d\d)\b/);
  return m ? m[0] : "";
}

function generateBibtexKey(authors, date, title) {
  const auths = parseAuthorsList(authors);
  const a = (auths[0]?.last || (authors ? authors.split(/[,;\s]/)[0] : "") || "ref").toLowerCase().replace(/[^a-z0-9]/g, "");
  const y = extractYear(date) || new Date().getFullYear().toString();
  const w = (title || "").toLowerCase().split(/[^a-z0-9]+/).filter(x => x.length > 2 && !["the", "and", "for"].includes(x))[0] || "article";
  return `${a}${y}${w}`;
}

// Parse a free-form "pages" field (e.g. "vol. 45, no. 9, pp. 123-130") into
// structured { vol, no, pp } parts used by the IEEE journal format.
function parsePagesParts(pages) {
  const s = String(pages || "").trim();
  const out = { vol: "", no: "", pp: "" };
  if (!s) return out;
  const vMatch = s.match(/(?:vol\.?|tập)\s*[:\s]?\s*(\d+)/i);
  if (vMatch) out.vol = vMatch[1];
  const nMatch = s.match(/(?:no\.?|issue|iss\.?|số)\s*[:\s]?\s*(\d+)/i);
  if (nMatch) out.no = nMatch[1];
  const pMatch = s.match(/pp?\.?\s*[:\s]?\s*(\d+(?:\s*[-–—]\s*\d+)?)/i);
  if (pMatch) {
    out.pp = pMatch[1].replace(/\s+/g, "");
  } else if (/^\d+\s*[-–—]\s*\d+$/.test(s)) {
    out.pp = s.replace(/\s+/g, "");
  }
  return out;
}

function buildIeeeCitation(meta) {
  const a = formatIeeeAuthors(meta.authors);
  let cleanTitle = (meta.title || "Untitled").trim()
    .replace(/^(?:Frontiers|Nature|Science|Springer|Elsevier|Wiley|PLOS|ACM|IEEE)\s*\|\s*/i, "")
    .replace(/[,\.]+$/, "");
  const y = extractYear(meta.date) || (meta.date ? meta.date.trim() : "n.d.");
  const dateIeee = meta.date ? formatCitationDate(meta.date, "ieee") : y;
  const dateIeeeMonthYear = citationSettings.dateStyle === "full" ? dateIeee : dateIeee.replace(/\s\d{1,2},/, "");
  
  let prefix = "";
  if (a && a.toLowerCase() !== cleanTitle.toLowerCase()) {
    prefix = `${a}, `;
  }

  switch (meta.sourceType) {
    case "academic": {
      let resAcad = `${prefix}"${cleanTitle}," `;
      if (meta.container) resAcad += `*${meta.container.trim()}*, `;
      const parts = parsePagesParts(meta.pages);
      if (parts.vol) resAcad += `vol. ${parts.vol}, `;
      if (parts.no) resAcad += `no. ${parts.no}, `;
      if (parts.pp) resAcad += `pp. ${parts.pp}, `;
      resAcad += `${dateIeeeMonthYear}`;
      if (meta.doi) {
        resAcad += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url) {
        resAcad += `. [Online]. Available: ${meta.url}.`;
        if (citationSettings.accessedDate) resAcad += ` [${t('i18n_accessed')}: ${meta.accessed || getTodayIeee()}].`;
      } else {
        resAcad += `.`;
      }
      return resAcad;
    }

    case "conference": {
      let resConf = `${prefix}"${cleanTitle}," in *${meta.container ? meta.container.trim() : "Proc. Conference"}*`;
      if (meta.publisher) resConf += `, ${meta.publisher.trim()}`;
      resConf += `, ${extractYear(meta.date) || dateIeeeMonthYear}`;
      const cparts = parsePagesParts(meta.pages);
      if (cparts.pp) resConf += `, pp. ${cparts.pp}`;
      else if (meta.pages) {
        let p = meta.pages.trim().replace(/[,\.]+$/, "");
        if (/^\d+(?:[-–]\d+)?$/.test(p)) p = `pp. ${p}`;
        resConf += `, ${p}`;
      }
      if (meta.doi) {
        resConf += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url) {
        resConf += `. [Online]. Available: ${meta.url}.`;
        if (citationSettings.accessedDate) resConf += ` [${t('i18n_accessed')}: ${meta.accessed || getTodayIeee()}].`;
      } else {
        resConf += `.`;
      }
      return resConf;
    }

    case "thesis": {
      let resTh = `${prefix}"${cleanTitle}," `;
      if (meta.pages && /(?:ph\.?d|m\.?s|b\.?s|dissertation|thesis|luận|đồ án)/i.test(meta.pages)) {
        resTh += `${meta.pages.trim()}, `;
      } else {
        resTh += "Ph.D. dissertation, ";
      }
      if (meta.container) resTh += `${meta.container.trim()}, `;
      if (meta.publisher) resTh += `${meta.publisher.trim()}, `;
      resTh += `${extractYear(meta.date) || "n.d."}`;
      if (meta.doi) {
        resTh += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        resTh += `. [Online]. Available: ${meta.url}.`;
      } else {
        resTh += `.`;
      }
      return resTh;
    }

    case "book":
      let resBook = `${prefix}*${cleanTitle}*`;
      if (meta.pages && /\d/.test(meta.pages) && /(?:ed\.?|edition|lần|ấn bản)/i.test(meta.pages)) resBook += `, ${meta.pages.trim()}`;
      if (meta.publisher) resBook += `. ${meta.publisher.trim()}`;
      else if (meta.container) resBook += `. ${meta.container.trim()}`;
      resBook += `, ${extractYear(meta.date) || "n.d."}`;
      if (meta.doi) {
        resBook += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else {
        resBook += `.`;
      }
      return resBook;

    case "book-chapter":
      let resChap = `${prefix}"${cleanTitle}," in *${meta.container ? meta.container.trim() : "Book"}*`;
      if (meta.publisher) resChap += `, ${meta.publisher.trim()}`;
      resChap += `, ${extractYear(meta.date) || "n.d."}`;
      if (meta.pages) {
        let cp = meta.pages.trim().replace(/[,\.]+$/, "");
        if (/^\d+(?:[-–]\d+)?$/.test(cp)) cp = `pp. ${cp}`;
        resChap += `, ${cp}`;
      }
      if (meta.doi) {
        resChap += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else {
        resChap += `.`;
      }
      return resChap;

    case "pdf":
      let repLabel = "Tech. Rep.";
      if (meta.pages) {
        const pTrim = meta.pages.trim();
        if (/^(?:tech\.?\s*rep|rep(?:ort)?\.?|tr\b|no\.?|báo cáo|report)\b/i.test(pTrim)) {
          repLabel = /^tr[-.]?\d/i.test(pTrim) ? `Tech. Rep. ${pTrim}` : pTrim;
        } else if (/^\d+[-\d]*$/.test(pTrim) || /^pp\./i.test(pTrim)) {
          repLabel = `Tech. Rep., ${pTrim.startsWith("pp.") ? pTrim : "pp. " + pTrim}`;
        } else {
          repLabel = `Rep. ${pTrim}`;
        }
      }
      let resRep = `${prefix}"${cleanTitle}," ${meta.container ? meta.container.trim() + ", " : ""}`;
      if (meta.publisher) resRep += `${meta.publisher.trim()}, `;
      resRep += `${repLabel}, ${extractYear(meta.date) || "n.d."}`;
      if (meta.doi) {
        resRep += `, doi: ${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        resRep += `. [Online]. Available: ${meta.url}.`;
        if (citationSettings.accessedDate) {
          resRep += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
        }
      } else {
        resRep += `.`;
      }
      return resRep;

    case "software": {
      let softVer = "";
      if (meta.pages) {
        const v = meta.pages.trim().replace(/^v(?:ersion)?\.?\s*/i, "");
        softVer = v ? ` (Version ${v})` : "";
      }
      let resSoft = `${prefix}*${cleanTitle}*${softVer}. ${extractYear(meta.date) || "n.d."}. [Software]. Available: ${meta.url}`;
      if (citationSettings.accessedDate) resSoft += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
      return resSoft;
    }

    case "video":
      const vDateIeee = meta.date ? formatCitationDate(meta.date, "ieee") : y;
      let resVid = `${prefix}"${cleanTitle}," *${meta.container || "YouTube"}*, ${vDateIeee}. [Online Video]. Available: ${meta.url}`;
      if (citationSettings.accessedDate) resVid += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
      return resVid;

    default:
      let resWeb = `${prefix}"${cleanTitle}," `;
      if (meta.container && meta.container.trim() !== cleanTitle) resWeb += `*${meta.container.trim()}*, `;
      const wDateIeee = meta.date ? formatCitationDate(meta.date, "ieee") : y;
      resWeb += `${wDateIeee}. [Online]. Available: ${meta.url}.`;
      if (citationSettings.accessedDate) {
        resWeb += ` [Accessed: ${meta.accessed || getTodayIeee()}].`;
      }
      return resWeb;
  }
}

function buildApaCitation(meta) {
  const a = formatApaAuthors(meta.authors) || meta.container || "Author";
  const y = extractYear(meta.date) || "n.d.";
  const isWebOrMedia = ["webpage", "video", "software"].includes(meta.sourceType);
  const formattedDate = isWebOrMedia && meta.date ? formatCitationDate(meta.date, "apa") : y;
  const d = `(${formattedDate || y})`;
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");

  let out = `${a} ${d}. `;

  switch (meta.sourceType) {
    case "academic":
      out += `${cleanTitle}. `;
      if (meta.container) out += `*${meta.container.trim()}*`;
      if (meta.pages) out += `, ${meta.pages.trim()}`;
      out += `. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "conference":
      out += `${cleanTitle}. In *${meta.container || "Conference Proceedings"}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      out += `. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "book":
      out += `*${cleanTitle}*`;
      if (meta.pages && meta.pages.toLowerCase().includes("ed")) out += ` (${meta.pages.trim()})`;
      out += `. `;
      if (meta.publisher) out += `${meta.publisher.trim()}. `;
      else if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "book-chapter":
      out += `${cleanTitle}. In `;
      if (meta.container) out += `*${meta.container.trim()}*`;
      if (meta.pages) out += ` (pp. ${meta.pages.trim().replace(/^pp\.\s*/i, "")})`;
      out += `. `;
      if (meta.publisher) out += `${meta.publisher.trim()}. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "thesis":
      out += `*${cleanTitle}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      else out += ` [Doctoral dissertation]`;
      out += `. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      else if (meta.url) out += meta.url;
      break;

    case "pdf":
      out += `*${cleanTitle}*`;
      if (meta.pages) {
        const pTrim = meta.pages.trim();
        out += ` (${/^(?:report|rep|no|white\s*paper)\b/i.test(pTrim) ? pTrim : "Report No. " + pTrim})`;
      } else {
        out += ` [PDF]`;
      }
      out += `. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) {
        out += `https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        out += meta.url;
        if (citationSettings.accessedDate) {
          out += ` (Retrieved ${meta.accessed || getTodayApa()}, from ${meta.url})`;
        }
      }
      break;

    case "software":
      out += `*${cleanTitle}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      out += ` [Computer software]. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.url) out += meta.url;
      break;

    case "video":
      out += `*${cleanTitle}* [Video]. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.url) out += meta.url;
      break;

    default:
      out += `*${cleanTitle}*. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      out += meta.url;
      if (citationSettings.accessedDate) {
        out += ` (Retrieved ${meta.accessed || getTodayApa()}, from ${meta.url})`;
      }
      break;
  }
  return out.trim();
}

function buildHarvardCitation(meta) {
  const a = formatHarvardAuthors(meta.authors) || meta.container || "Author";
  const y = extractYear(meta.date) || "n.d.";
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");

  let out = `${a} (${y}) `;

  switch (meta.sourceType) {
    case "academic":
      out += `'${cleanTitle}', *${meta.container || "Journal"}*`;
      if (meta.pages) out += `, ${meta.pages.trim()}`;
      out += `.`;
      if (meta.doi) out += ` Available at: https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      break;

    case "conference":
      out += `'${cleanTitle}', in *${meta.container || "Conference Proceedings"}*`;
      if (meta.pages) out += `, pp. ${meta.pages.trim()}`;
      out += `.`;
      break;

    case "book":
      out += `*${cleanTitle}*. `;
      if (meta.publisher) out += `${meta.publisher.trim()}.`;
      else if (meta.container) out += `${meta.container.trim()}.`;
      break;

    case "book-chapter":
      out += `'${cleanTitle}', in *${meta.container || "Book"}*`;
      if (meta.publisher) out += `, ${meta.publisher.trim()}`;
      if (meta.pages) out += `, pp. ${meta.pages.trim().replace(/^pp\.\s*/i, "")}`;
      out += `.`;
      if (meta.doi) out += ` Available at: https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      break;

    case "thesis":
      out += `*${cleanTitle}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      else out += ` [Doctoral thesis]`;
      out += `. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) out += `Available at: https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      else if (meta.url && !meta.url.startsWith("file://")) out += `Available at: ${meta.url}.`;
      break;

    case "pdf":
      out += `*${cleanTitle}*`;
      if (meta.pages) out += ` (${meta.pages.trim()})`;
      out += ` [PDF]. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      if (meta.doi) {
        out += `Available at: https://doi.org/${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        out += `Available at: ${meta.url}`;
        if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
        out += `.`;
      }
      break;

    case "software":
      out += `*${cleanTitle}* [Computer program]. Available at: ${meta.url}`;
      if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
      out += `.`;
      break;

    case "video":
      out += `'${cleanTitle}' [Online video]. Available at: ${meta.url}`;
      if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
      out += `.`;
      break;

    default:
      out += `*${cleanTitle}*, ${meta.container || "Website"}. Available at: ${meta.url}`;
      if (citationSettings.accessedDate) out += ` (Accessed: ${meta.accessed || getTodayIeee()})`;
      out += `.`;
      break;
  }
  return out.trim();
}

function buildMlaCitation(meta) {
  const a = formatMlaAuthors(meta.authors);
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");
  const y = extractYear(meta.date);

  let out = a ? (a.endsWith(".") ? `${a} ` : `${a}. `) : "";

  switch (meta.sourceType) {
    case "academic":
      out += `"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container.trim()}*, `;
      if (meta.pages) out += `${meta.pages.trim()}, `;
      out += `${y}. `;
      if (meta.doi) out += `doi:${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      else if (meta.url) out += `${meta.url}.`;
      break;

    case "conference":
      out += `"${cleanTitle}." *${meta.container || "Conference Proceedings"}*, ${y}`;
      if (meta.pages) out += `, pp. ${meta.pages.trim()}`;
      out += `.`;
      break;

    case "book":
      out += `*${cleanTitle}*. `;
      if (meta.publisher) out += `${meta.publisher.trim()}, `;
      else if (meta.container) out += `${meta.container.trim()}, `;
      out += `${y}.`;
      break;

    case "book-chapter":
      out += `"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container.trim()}*, `;
      if (meta.publisher) out += `${meta.publisher.trim()}, `;
      if (meta.pages) out += `pp. ${meta.pages.trim().replace(/^pp\.\s*/i, "")}, `;
      out += `${y}.`;
      break;

    case "thesis":
      out += `*${cleanTitle}*. `;
      if (meta.pages) out += `${meta.pages.trim()}, `;
      if (meta.container) out += `${meta.container.trim()}, `;
      out += `${y}.`;
      break;

    case "pdf":
      out += `*${cleanTitle}*. `;
      if (meta.pages) out += `${meta.pages.trim()}, `;
      if (meta.container) out += `${meta.container.trim()}, `;
      out += `${y}, `;
      if (meta.doi) {
        out += `doi:${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}.`;
      } else if (meta.url && !meta.url.startsWith("file://")) {
        out += `${meta.url}.`;
        if (citationSettings.accessedDate) {
          out += ` Accessed ${meta.accessed || getTodayIeee()}.`;
        }
      } else {
        out = out.replace(/,\s*$/, ".");
      }
      break;

    case "video":
      const vDateMla = meta.date ? formatCitationDate(meta.date, "mla") : y;
      return `${out}"${cleanTitle}." *${meta.container || "YouTube"}*, ${vDateMla}, ${meta.url}.`;

    default:
      out += `"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container.trim()}*, `;
      const wDateMla = meta.date ? formatCitationDate(meta.date, "mla") : y;
      out += `${wDateMla}, `;
      out += `${meta.url}.`;
      if (citationSettings.accessedDate) {
        out += ` Accessed ${meta.accessed || getTodayIeee()}.`;
      }
      break;
  }
  return out.trim();
}

function buildBibtexCitation(meta) {
  const key = generateBibtexKey(meta.authors, meta.date, meta.title);
  const y = extractYear(meta.date);
  const authorField = formatBibtexAuthors(meta.authors);

  let type = "misc";
  switch (meta.sourceType) {
    case "academic": type = "article"; break;
    case "conference": type = "inproceedings"; break;
    case "book": type = "book"; break;
    case "book-chapter": type = "incollection"; break;
    case "thesis": type = "phdthesis"; break;
    case "pdf": type = "techreport"; break;
    case "software": type = "software"; break;
    default: type = "misc"; break;
  }

  let lines = [`@${type}{${key},`];
  if (authorField) {
    lines.push(`  author = {${authorField}},`);
  }
  const cleanTitle = (meta.title || "Untitled").trim().replace(/^(?:Frontiers|Nature|Science|Springer|Elsevier|Wiley|PLOS|ACM|IEEE)\s*\|\s*/i, "");
  lines.push(`  title = {{${cleanTitle}}},`);

  if (type === "article") {
    if (meta.container) lines.push(`  journal = {${meta.container}},`);
        if (meta.pages) {
       let vol = "", num = "", pp = meta.pages;
       const vMatch = pp.match(/vol\.?\s*(\d+)/i);
       const nMatch = pp.match(/(?:no\.?|issue)\s*(\d+)/i);
       if (vMatch) {
           vol = vMatch[1];
           pp = pp.replace(vMatch[0], "");
       }
       if (nMatch) {
           num = nMatch[1];
           pp = pp.replace(nMatch[0], "");
       }
       pp = pp.replace(/[^0-9\-–]/g, "").trim();
       if (vol) lines.push(`  volume = {${vol}},`);
       if (num) lines.push(`  number = {${num}},`);
       if (pp) lines.push(`  pages = {${pp}},`);
    }
  } else if (type === "inproceedings") {
    if (meta.container) lines.push(`  booktitle = {${meta.container}},`);
        if (meta.pages) {
       let vol = "", num = "", pp = meta.pages;
       const vMatch = pp.match(/vol\.?\s*(\d+)/i);
       const nMatch = pp.match(/(?:no\.?|issue)\s*(\d+)/i);
       if (vMatch) {
           vol = vMatch[1];
           pp = pp.replace(vMatch[0], "");
       }
       if (nMatch) {
           num = nMatch[1];
           pp = pp.replace(nMatch[0], "");
       }
       pp = pp.replace(/[^0-9\-–]/g, "").trim();
       if (vol) lines.push(`  volume = {${vol}},`);
       if (num) lines.push(`  number = {${num}},`);
       if (pp) lines.push(`  pages = {${pp}},`);
    }
  } else if (type === "book") {
    if (meta.publisher) lines.push(`  publisher = {${meta.publisher}},`);
    else if (meta.container) lines.push(`  publisher = {${meta.container}},`);
  } else if (type === "incollection") {
    if (meta.container) lines.push(`  booktitle = {${meta.container}},`);
    if (meta.publisher) lines.push(`  publisher = {${meta.publisher}},`);
    if (meta.pages) lines.push(`  pages = {${meta.pages.trim().replace(/[^0-9\-–]/g, "")}},`);
  } else if (type === "phdthesis") {
    if (meta.container) lines.push(`  school = {${meta.container}},`);
    if (meta.publisher) lines.push(`  address = {${meta.publisher}},`);
  } else if (type === "techreport") {
    if (meta.container) lines.push(`  institution = {${meta.container}},`);
    if (meta.pages) lines.push(`  number = {${meta.pages}},`);
    lines.push(`  type = {Technical Report},`);
  } else if (type === "software") {
    if (meta.pages) lines.push(`  version = {${meta.pages}},`);
  } else {
    if (meta.container) lines.push(`  howpublished = {${meta.container}},`);
  }

  const parsedDate = parseComprehensiveDate(meta.date);
  const mYmd = (parsedDate || meta.date || "").match(/^(?:19\d\d|20\d\d)-(\d{1,2})/);
  if (mYmd) {
    const bibMonths = ["", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
    const mIdx = parseInt(mYmd[1], 10);
    if (mIdx >= 1 && mIdx <= 12) {
      lines.push(`  month = {${bibMonths[mIdx]}},`);
    }
  }

  lines.push(`  year = {${y}},`);
  if (meta.doi) lines.push(`  doi = {${meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "")}},`);
  if (meta.url && !meta.url.startsWith("file://")) {
    lines.push(`  url = {${meta.url}},`);
  }
  if (meta.notes) {
    lines.push(`  note = {${meta.notes.replace(/[\r\n]+/g, " ").trim()}},`);
  }
  if (meta.tag) {
    lines.push(`  keywords = {${meta.tag.trim()}},`);
  }
  // Trim trailing comma from last field line
  if (lines.length > 1) {
    const lastIdx = lines.length - 1;
    lines[lastIdx] = lines[lastIdx].replace(/,$/, "");
  }
  lines.push(`}`);
  return lines.join("\n");
}

function buildVancouverCitation(meta) {
  const a = formatVancouverAuthors(meta.authors);
  const y = extractYear(meta.date) || "n.d.";
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");
  const doiClean = meta.doi ? meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "") : "";
  const pagesV = meta.pages ? meta.pages.trim().replace(/[,\.]+$/, "").replace(/[–—]/, "-") : "";

  switch (meta.sourceType) {
    case "academic": {
      let out = `${a}. ${cleanTitle}. `;
      if (meta.container) out += `*${meta.container.trim()}*. `;
      out += `${y}`;
      if (pagesV) out += `;${pagesV}`;
      out += `.`;
      if (doiClean) out += ` doi: ${doiClean}.`;
      else if (meta.url && !meta.url.startsWith("file://")) {
        out += ` Available from: ${meta.url}.`;
        if (citationSettings.accessedDate) out += ` [Accessed ${meta.accessed || getTodayIeee()}].`;
      }
      return out;
    }
    case "conference": {
      let out = `${a}. ${cleanTitle}. In: *${meta.container || "Conference Proceedings"}*. `;
      out += `${y}`;
      if (pagesV) out += `;${pagesV}`;
      out += `.`;
      if (doiClean) out += ` doi: ${doiClean}.`;
      else if (meta.url && !meta.url.startsWith("file://")) out += ` Available from: ${meta.url}.`;
      return out;
    }
    case "book":
      return `${a}. *${cleanTitle}*.${meta.publisher ? ` ${meta.publisher.trim()};` : (meta.container ? ` ${meta.container.trim()};` : "")} ${y}.`;
    case "book-chapter": {
      let out = `${a}. ${cleanTitle}. In: *${meta.container || "Book"}*.`;
      if (meta.publisher) out += ` ${meta.publisher.trim()};`;
      out += ` ${y}`;
      if (pagesV) out += `;${pagesV}`;
      out += `.`;
      if (doiClean) out += ` doi: ${doiClean}.`;
      else if (meta.url && !meta.url.startsWith("file://")) out += ` Available from: ${meta.url}.`;
      return out;
    }
    case "thesis": {
      let out = `${a}. ${cleanTitle}`;
      if (meta.pages) out += ` (${meta.pages.trim().replace(/[,\.]+$/, "")})`;
      out += `.`;
      if (meta.container) out += ` ${meta.container.trim()};`;
      out += ` ${y}.`;
      if (doiClean) out += ` doi: ${doiClean}.`;
      else if (meta.url && !meta.url.startsWith("file://")) out += ` Available from: ${meta.url}.`;
      return out;
    }
    case "pdf": {
      let out = `${a}. ${cleanTitle}.`;
      if (meta.pages) out += ` (${meta.pages.trim().replace(/[,\.]+$/, "")})`;
      if (meta.container) out += ` ${meta.container.trim()};`;
      out += ` ${y}.`;
      if (doiClean) out += ` doi: ${doiClean}.`;
      else if (meta.url && !meta.url.startsWith("file://")) out += ` Available from: ${meta.url}.`;
      return out;
    }
    case "software":
      return `${a}. *${cleanTitle}* [Computer software].${meta.container ? ` ${meta.container.trim()};` : ""} ${y}.${meta.url && !meta.url.startsWith("file://") ? ` Available from: ${meta.url}.` : ""}`;
    case "video":
      return `${a}. ${cleanTitle} [Video].${meta.container ? ` ${meta.container.trim()};` : ""} ${y}.${meta.url ? ` Available from: ${meta.url}.` : ""}`;
    default: {
      let out = `${a}. ${cleanTitle}. `;
      if (meta.container && meta.container.trim() !== cleanTitle) out += `${meta.container.trim()}. `;
      out += `${y}.`;
      if (meta.url && !meta.url.startsWith("file://")) {
        out += ` Available from: ${meta.url}.`;
        if (citationSettings.accessedDate) out += ` [Accessed ${meta.accessed || getTodayIeee()}].`;
      }
      return out;
    }
  }
}

function buildChicagoCitation(meta) {
  const a = formatChicagoAuthors(meta.authors);
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");
  const y = extractYear(meta.date);
  const dateChicago = meta.date ? formatCitationDate(meta.date, "chicago") : (y || "n.d.");
  const doiClean = meta.doi ? meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "") : "";
  const urlChicago = meta.url && !meta.url.startsWith("file://") ? meta.url : "";

  switch (meta.sourceType) {
    case "academic": {
      let out = `${a ? a + ". " : ""}"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container.trim()}*`;
      out += `${y ? ` (${y})` : ""}`;
      if (meta.pages) out += `: ${meta.pages.trim().replace(/[,\.]+$/, "")}`;
      out += `.`;
      if (doiClean) out += ` https://doi.org/${doiClean}.`;
      else if (urlChicago) out += ` ${urlChicago}.`;
      return out;
    }
    case "conference": {
      let out = `${a ? a + ". " : ""}"${cleanTitle}." `;
      if (meta.container) out += `*${meta.container || "Conference Proceedings"}*, `;
      if (meta.pages) out += `${meta.pages.trim().replace(/[,\.]+$/, "")}, `;
      out += `${y || "n.d."}.`;
      return out;
    }
    case "book":
      return `${a ? a + ". " : ""}*${cleanTitle}*. ${meta.publisher ? meta.publisher.trim() + ", " : (meta.container ? meta.container.trim() + ", " : "")}${y || "n.d."}.`;
    case "book-chapter": {
      let out = `${a ? a + ". " : ""}"${cleanTitle}." In *${meta.container || "Book"}*`;
      if (meta.publisher) out += `, ${meta.publisher.trim()}`;
      if (meta.pages) out += `, ${meta.pages.trim().replace(/[,\.]+$/, "")}`;
      out += `, ${y || "n.d."}.`;
      if (doiClean) out += ` https://doi.org/${doiClean}.`;
      else if (urlChicago) out += ` ${urlChicago}.`;
      return out;
    }
    case "thesis": {
      let out = `${a ? a + ". " : ""}*${cleanTitle}*. `;
      if (meta.pages) out += `${meta.pages.trim().replace(/[,\.]+$/, "")}. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      out += `${y || "n.d."}.`;
      if (urlChicago) out += ` ${urlChicago}.`;
      return out.trim();
    }
    case "pdf": {
      let out = `${a ? a + ". " : ""}*${cleanTitle}*. `;
      if (meta.pages) out += `${meta.pages.trim().replace(/[,\.]+$/, "")}. `;
      if (meta.container) out += `${meta.container.trim()}. `;
      out += `${y || "n.d."}. `;
      if (doiClean) out += `https://doi.org/${doiClean}.`;
      else if (urlChicago) out += `${urlChicago}.`;
      return out.trim();
    }
    case "software":
      return `${a ? a + ". " : ""}*${cleanTitle}*. ${meta.pages ? meta.pages.trim() + ". " : ""}${meta.container ? meta.container.trim() + ", " : ""}${y || "n.d."}.${meta.url ? ` ${meta.url}.` : ""}`.trim();
    case "video":
      return `${a ? a + ". " : ""}"${cleanTitle}." ${meta.container || "YouTube"}, ${dateChicago}, ${meta.url || ""}.`; 
    default: {
      let out = `${a ? a + ". " : ""}"${cleanTitle}." `;
      if (meta.container && meta.container.trim() !== cleanTitle) out += `${meta.container.trim()}. `;
      out += `${y ? y + ". " : ""}`;
      if (citationSettings.accessedDate) out += `Accessed ${meta.accessed || dateChicago}. `;
      if (urlChicago) out += `${urlChicago}.`;
      return out.trim();
    }
  }
}

function buildAcsCitation(meta) {
  const a = formatAcsAuthors(meta.authors);
  const aDot = a ? (a.endsWith(".") ? a : a + ".") : "";
  const y = extractYear(meta.date) || "n.d.";
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");
  const doiClean = meta.doi ? meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "") : "";
  const urlAcs = meta.url && !meta.url.startsWith("file://") ? meta.url : "";

  switch (meta.sourceType) {
    case "academic": {
      let out = `${aDot} ${cleanTitle}. `;
      if (meta.container) out += `*${meta.container.trim()}*`;
      out += ` ${y}`;
      if (meta.pages) out += `, ${meta.pages.trim().replace(/[,\.]+$/, "")}`;
      out += `.`;
      if (doiClean) out += ` https://doi.org/${doiClean}.`;
      else if (urlAcs) out += ` ${urlAcs}.`;
      return out;
    }
    case "book":
      return `${aDot} ${cleanTitle}. ${meta.publisher ? meta.publisher.trim() + ", " : (meta.container ? meta.container.trim() + ", " : "")}${y}.`;
    case "book-chapter":
      return `${aDot} ${cleanTitle}. In ${meta.container ? meta.container.trim() + ", " : ""}${meta.publisher ? meta.publisher.trim() + ", " : ""}${y}${meta.pages ? `, pp. ${meta.pages.trim().replace(/^pp\.\s*/i, "")}` : ""}.`;
    case "thesis":
      return `${aDot} ${cleanTitle}. ${meta.pages ? meta.pages.trim() + ". " : ""}${meta.container ? meta.container.trim() + ", " : ""}${y}.`;
    default: {
      let out = `${aDot} ${cleanTitle}. `;
      if (meta.container && meta.container.trim() !== cleanTitle) out += `${meta.container.trim()}. `;
      out += `${y}.`;
      if (urlAcs) out += ` ${urlAcs}.`;
      return out;
    }
  }
}

function buildAmaCitation(meta) {
  const a = formatAmaAuthors(meta.authors);
  const y = extractYear(meta.date) || "n.d.";
  const cleanTitle = (meta.title || "Untitled").trim().replace(/[,\.]+$/, "");
  const doiClean = meta.doi ? meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "") : "";
  const urlAma = meta.url && !meta.url.startsWith("file://") ? meta.url : "";

  switch (meta.sourceType) {
    case "academic": {
      let out = `${a}. ${cleanTitle}. `;
      if (meta.container) out += `*${meta.container.trim()}*. `;
      out += `${y}`;
      if (meta.pages) out += `;${meta.pages.trim().replace(/[,\.]+$/, "")}`;
      out += `.`;
      if (doiClean) out += ` doi:${doiClean}`;
      else if (urlAma) out += ` ${urlAma}`;
      return out;
    }
    case "book":
      return `${a}. ${cleanTitle}. ${meta.publisher ? meta.publisher.trim() + " " : (meta.container ? meta.container.trim() + " " : "")}${y}.`;
    case "book-chapter":
      return `${a}. ${cleanTitle}. In ${meta.container ? meta.container.trim() + ". " : ""}${meta.publisher ? meta.publisher.trim() + " " : ""}${y}${meta.pages ? `;${meta.pages.trim().replace(/[,\.]+$/, "")}` : ""}.`;
    case "thesis":
      return `${a}. ${cleanTitle}. ${meta.pages ? meta.pages.trim() + ". " : ""}${meta.container ? meta.container.trim() + " " : ""}${y}.`;
    default: {
      let out = `${a}. ${cleanTitle}. `;
      if (meta.container && meta.container.trim() !== cleanTitle) out += `${meta.container.trim()}. `;
      out += `${y}.`;
      if (urlAma) out += ` ${urlAma}.`;
      return out;
    }
  }
}

function buildIntextCitation(meta) {
  const authors = parseAuthorsList(meta.authors);
  const y = extractYear(meta.date);

  let a1 = "";
  let ieeeAuthorInText = "";
  let apaParenthetical = "";
  let apaNarrative = "";

  if (authors.length === 0) {
    const site = meta.container || "Tác giả";
    ieeeAuthorInText = site;
    apaParenthetical = `(${site}, ${y})`;
    apaNarrative = `${site} (${y})`;
  } else if (authors.length === 1) {
    a1 = authors[0].isOrg ? authors[0].last : authors[0].last;
    ieeeAuthorInText = a1;
    apaParenthetical = `(${a1}, ${y})`;
    apaNarrative = `${a1} (${y})`;
  } else if (authors.length === 2) {
    a1 = authors[0].last;
    const a2 = authors[1].last;
    ieeeAuthorInText = `${a1} and ${a2}`;
    apaParenthetical = `(${a1} & ${a2}, ${y})`;
    apaNarrative = `${a1} và ${a2} (${y})`;
  } else {
    a1 = authors[0].last;
    ieeeAuthorInText = `${a1} et al.`;
    apaParenthetical = `(${a1} et al., ${y})`;
    apaNarrative = `${a1} et al. (${y})`;
  }

  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  if (lang === "en") {
    return `IEEE STANDARD (Numbered [1]):
• Direct Citation: "...as previously reported in [1]."
• Narrative Citation: "According to ${ieeeAuthorInText} [1], this approach..."
• Multiple Sources: "...consistent findings were documented in [1], [2], [4]–[6]."

───────────────────────────────────
APA 7th EDITION (Author-Date):
• Parenthetical: "...demonstrating the viability of the approach ${apaParenthetical}."
• Narrative: "${apaNarrative} demonstrated that the algorithm achieves high accuracy."

───────────────────────────────────
Multiple Authors Rule:
• 1 author: (${a1}, ${y})
• 2 authors: (${a1} & ${authors[1]?.last || "Author"}, ${y})
• ≥ 3 authors: (${a1} et al., ${y}) used from the very first citation.`;
  } else if (lang === "zh") {
    return `IEEE 国际标准（序号引用 [1]）：
• 句末直接引用：“...正如文献 [1] 中所阐明的那样。”
• 叙述性文内引用：“根据 ${ieeeAuthorInText} [1] 的研究，该模型表现优异...”
• 多个连续文献引用：“...在文献 [1], [2], [4]–[6] 中均得出了类似结论。”

───────────────────────────────────
APA 第 7 版标准（著者-出版年）：
• 括号内引用（Parenthetical）：“...证明了该算法的有效性 ${apaParenthetical}。”
• 叙述性引用（Narrative）：“${apaNarrative} 指出该深度神经网络达到了极高的识别精度。”

───────────────────────────────────
多著者引用规范：
• 1 位作者：(${a1}, ${y})
• 2 位作者：(${a1} & ${authors[1]?.last || "李四"}, ${y})
• ≥ 3 位作者：(${a1} et al., ${y}) 首次提及即可直接使用。`;
  } else if (lang === "ru") {
    return `СТАНДАРТ IEEE (Нумерация [1]):
• Прямая ссылка: «...как было показано в исследовании [1].»
• В повествовании: «Согласно исследованию ${ieeeAuthorInText} [1], данная модель...»
• Несколько источников: «...аналогичные результаты приведены в [1], [2], [4]–[6].»

───────────────────────────────────
СТАНДАРТ APA 7-е издание (Автор-Год):
• В скобках (Parenthetical): «...что подтверждает эффективность предложенного метода ${apaParenthetical}.»
• В повествовании (Narrative): «${apaNarrative} установили высокую точность алгоритма.»

───────────────────────────────────
Правила для нескольких авторов:
• 1 автор: (${a1}, ${y})
• 2 автора: (${a1} & ${authors[1]?.last || "Иванов"}, ${y})
• ≥ 3 авторов: (${a1} et al., ${y}) используется с первого упоминания.`;
  } else if (lang === "ja") {
    return `IEEE 国際標準 (番号順 [1]):
• 文末直接引用: 「...文献 [1] で報告されているように。」
• 本文記述 (Narrative): 「${ieeeAuthorInText} [1] の研究によれば、この手法は...」
• 複数文献の連続引用: 「...同様の結果が [1], [2], [4]–[6] でも報告されている。」

───────────────────────────────────
APA 第7版標準 (著者-刊行年):
• 括弧内引用 (Parenthetical): 「...本手法の有効性が示された ${apaParenthetical}。」
• 本文記述 (Narrative): 「${apaNarrative} は、提案アルゴリズムが高い精度を達成することを実証した。」

───────────────────────────────────
複数著者の表記規則:
• 著者1名: (${a1}, ${y})
• 著者2名: (${a1} & ${authors[1]?.last || "佐藤"}, ${y})
• 著者3名以上: (${a1} et al., ${y}) 初回言及時から即座に使用。`;
  }

  return `CHUẨN IEEE (Số thứ tự [1]):
• Cuối câu (Trực tiếp): "...như đã được công bố trong tài liệu [1]."
• Mạch văn (Narrative): "Theo nghiên cứu của ${ieeeAuthorInText} [1], mô hình này..."
• Nhiều nguồn liên tiếp: "...các kết quả tương tự cũng được tìm thấy trong [1], [2], [4]–[6]."

───────────────────────────────────
CHUẨN APA 7th (Tác giả - Năm):
• Trong ngoặc (Parenthetical): "...đã chứng minh được tính khả thi của giải pháp ${apaParenthetical}."
• Tường thuật (Narrative): "${apaNarrative} đã chỉ ra rằng thuật toán đạt độ chính xác cao."

───────────────────────────────────
Quy tắc nhiều tác giả:
• 1 tác giả: (${a1}, ${y})
• 2 tác giả: (${a1} & ${authors[1]?.last || "Trần"}, ${y})
• ≥ 3 tác giả: (${a1} et al., ${y}) dùng ngay từ lần trích đầu tiên.`;
}

// ── CSL-JSON (Citation Style Language) — dùng cho Zotero/Mendeley/citeproc ──
const CSL_TYPE_MAP = {
  academic: "article-journal",
  conference: "paper-conference",
  book: "book",
  "book-chapter": "chapter",
  thesis: "thesis",
  pdf: "report",
  software: "software",
  video: "motion_picture",
  webpage: "webpage"
};

function buildCslJsonCitation(meta) {
  const csl = {
    id: meta.id || ("item-" + Date.now() + "-" + Math.random().toString(36).substr(2, 4)),
    type: CSL_TYPE_MAP[meta.sourceType] || "webpage",
    title: (meta.title || "Untitled").trim()
  };
  if (meta.container) csl["container-title"] = meta.container.trim();
  if (meta.publisher) csl.publisher = meta.publisher.trim();
  if (meta.authors) {
    const authors = parseAuthorsList(meta.authors);
    if (authors.length) {
      csl.author = authors.map(a => {
        if (a.isOrg) return { literal: a.last };
        const o = {};
        if (a.last) o.family = a.last;
        if (a.first) o.given = a.first;
        return o;
      });
    }
  }
  const y = extractYear(meta.date);
  if (y) csl.issued = { "date-parts": [[parseInt(y, 10)]] };
  if (meta.pages) csl.page = meta.pages.trim().replace(/[,\.]+$/, "");
  if (meta.doi) csl.DOI = meta.doi.trim().replace(/^https?:\/\/doi\.org\//, "");
  if (meta.url && !meta.url.startsWith("file://")) csl.URL = meta.url;
  if (meta.tag) csl.keyword = meta.tag.trim();
  if (meta.notes) csl.note = meta.notes.trim();
  return JSON.stringify(csl, null, 2);
}

// ── EndNote XML (.xml) — dùng cho EndNote/Reference Manager ──
const ENDNOTE_REF_TYPE_MAP = {
  academic: { name: "Journal Article", num: 17 },
  conference: { name: "Conference Paper", num: 47 },
  book: { name: "Book", num: 6 },
  "book-chapter": { name: "Book Section", num: 5 },
  thesis: { name: "Thesis", num: 32 },
  pdf: { name: "Report", num: 27 },
  software: { name: "Computer Program", num: 20 },
  video: { name: "Web Page", num: 12 },
  webpage: { name: "Web Page", num: 12 }
};

function buildEndnoteXmlCitation(meta) {
  const rt = ENDNOTE_REF_TYPE_MAP[meta.sourceType] || { name: "Web Page", num: 12 };
  const esc = s => String(s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  let xml = "  <record>\n";
  xml += `    <ref-type name="${rt.name}">${rt.num}</ref-type>\n`;
  if (meta.authors) {
    const authors = parseAuthorsList(meta.authors);
    if (authors.length) {
      xml += "    <contributors><authors>\n";
      authors.forEach(a => {
        const name = a.isOrg ? a.last : (a.last ? `${a.last}, ${a.first || a.initials || ""}`.trim() : (a.first || a.raw || ""));
        if (name) xml += `      <author>${esc(name)}</author>\n`;
      });
      xml += "    </authors></contributors>\n";
    }
  }
  xml += "    <titles>\n";
  xml += `      <title>${esc(meta.title || "Untitled")}</title>\n`;
  if (meta.container) xml += `      <secondary-title>${esc(meta.container)}</secondary-title>\n`;
  xml += "    </titles>\n";
  const y = extractYear(meta.date);
  if (y) xml += `    <dates><year>${y}</year></dates>\n`;
  if (meta.publisher) xml += `    <publisher>${esc(meta.publisher)}</publisher>\n`;
  if (meta.pages) xml += `    <pages>${esc(meta.pages.trim())}</pages>\n`;
  if (meta.doi) xml += `    <electronic-resource-num>${esc(meta.doi.trim())}</electronic-resource-num>\n`;
  if (meta.url && !meta.url.startsWith("file://")) xml += `    <urls><related-urls><url>${esc(meta.url)}</url></related-urls></urls>\n`;
  if (meta.tag) {
    xml += "    <keywords>\n";
    meta.tag.split(",").forEach(t => { if (t.trim()) xml += `      <keyword>${esc(t.trim())}</keyword>\n`; });
    xml += "    </keywords>\n";
  }
  if (meta.notes) xml += `    <notes>${esc(meta.notes.replace(/\n/g, " ").trim())}</notes>\n`;
  xml += "  </record>";
  return xml;
}

