// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/dates.js
// Comprehensive date parsing + citation date formatting
// Extracted from js/sidebar.js (lines 1007-1052) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
function formatCitationDate(rawDate, style = "ieee") {
  if (!rawDate) return "";
  if (citationSettings.dateStyle === "year") {
    const yM = rawDate.match(/\b(19\d\d|20\d\d)\b/);
    return yM ? yM[1] : rawDate;
  }
  let effectiveStyle = style;
  if (citationSettings.dateStyle === "full") {
    effectiveStyle = style; // we handle "full" below by avoiding month-year truncation
  }
  const parsed = parseComprehensiveDate(rawDate);
  const s = parsed || rawDate.trim();

  // Try matching YYYY-MM-DD
  const mYmd = s.match(/^(19\d\d|20\d\d)-(\d{1,2})-(\d{1,2})$/);
  if (mYmd) {
    const y = mYmd[1];
    const m = parseInt(mYmd[2], 10);
    const d = parseInt(mYmd[3], 10);
    if (m >= 1 && m <= 12) {
      if (style === "ieee") return `${MONTHS_IEEE[m]} ${d}, ${y}`;
      if (style === "apa") return `${y}, ${MONTHS_FULL[m]} ${d}`;
      if (style === "mla") return `${d} ${MONTHS_IEEE[m]} ${y}`;
      if (style === "year") return y;
    }
  }

  // Try matching YYYY-MM
  const mYm = s.match(/^(19\d\d|20\d\d)-(\d{1,2})$/);
  if (mYm) {
    const y = mYm[1];
    const m = parseInt(mYm[2], 10);
    if (m >= 1 && m <= 12) {
      if (style === "ieee") return `${MONTHS_IEEE[m]} ${y}`;
      if (style === "apa") return `${y}, ${MONTHS_FULL[m]}`;
      if (style === "mla") return `${MONTHS_IEEE[m]} ${y}`;
      if (style === "year") return y;
    }
  }

  // Fallback if 4-digit year exists
  const mY = s.match(/\b(19\d\d|20\d\d)\b/);
  if (style === "year" && mY) return mY[0];
  return s;
}

