// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/selects.js
// Custom select dropdown rendering/sync
// Extracted from js/sidebar.js (lines 2403-2488) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Citation Customization Settings & Bibliography Manager
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Custom Select Dropdown Synchronization (Author Style & Default Citation Style)
// ----------------------------------------------------------------------------
function syncCustomSelects() {
  // 1. Author Style dropdown sync
  const authorSel = document.getElementById("cite-pref-author-style");
  const authorLabel = document.getElementById("label-author-style");
  const authorMenu = document.getElementById("menu-author-style");
  if (authorSel && authorLabel && authorMenu) {
    const val = authorSel.value || "standard";
    const activeItem = authorMenu.querySelector(`.custom-select-item[data-value="${val}"]`);
    if (activeItem) {
      authorLabel.textContent = activeItem.textContent;
      authorMenu.querySelectorAll(".custom-select-item").forEach(it => it.classList.toggle("selected", it === activeItem));
    }
  }

  // 2. Date Style dropdown sync
  const dateSyncSel = document.getElementById("cite-pref-date-style");
  const dateSyncLabel = document.getElementById("label-date-style");
  const dateSyncMenu = document.getElementById("menu-date-style");
  if (dateSyncSel && dateSyncLabel && dateSyncMenu) {
    const val = dateSyncSel.value || "auto";
    const activeItem = dateSyncMenu.querySelector(`.custom-select-item[data-value="${val}"]`);
    if (activeItem) {
      dateSyncLabel.textContent = activeItem.textContent;
      dateSyncMenu.querySelectorAll(".custom-select-item").forEach(it => it.classList.toggle("selected", it === activeItem));
    }
  }
}

function initCustomSelects() {
  const binds = [
    { wrapId: "wrap-author-style", triggerId: "btn-author-style", menuId: "menu-author-style", selectId: "cite-pref-author-style", labelId: "label-author-style" },
    { wrapId: "wrap-date-style", triggerId: "btn-date-style", menuId: "menu-date-style", selectId: "cite-pref-date-style", labelId: "label-date-style" }
  ];

  binds.forEach(({ wrapId, triggerId, menuId, selectId, labelId }) => {
    const wrap = document.getElementById(wrapId);
    const trigger = document.getElementById(triggerId);
    const menu = document.getElementById(menuId);
    const select = document.getElementById(selectId);
    const label = document.getElementById(labelId);
    if (!wrap || !trigger || !menu || !select || !label) return;

    trigger.addEventListener("click", (e) => {
      e.stopPropagation();
      const isOpen = wrap.classList.contains("open");
      document.querySelectorAll(".custom-dropdown-wrap.open, .custom-select-wrap.open").forEach(el => el.classList.remove("open"));
      if (!isOpen) wrap.classList.add("open");
    });

    menu.querySelectorAll(".custom-select-item").forEach(item => {
      item.addEventListener("click", (e) => {
        e.stopPropagation();
        const val = item.dataset.value;
        if (val) {
          select.value = val;
          label.textContent = item.textContent;
          menu.querySelectorAll(".custom-select-item").forEach(it => it.classList.toggle("selected", it === item));
          wrap.classList.remove("open");
          select.dispatchEvent(new Event("change", { bubbles: true }));
        }
      });
    });
  });

  // Global close listener for all custom dropdowns & custom selects
  document.addEventListener("click", (e) => {
    if (!e.target.closest(".custom-dropdown-wrap") && !e.target.closest(".custom-select-wrap")) {
      document.querySelectorAll(".custom-dropdown-wrap.open, .custom-select-wrap.open").forEach(el => el.classList.remove("open"));
    }
  });

  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") {
      document.querySelectorAll(".custom-dropdown-wrap.open, .custom-select-wrap.open").forEach(el => el.classList.remove("open"));
    }
  });

  syncCustomSelects();
}

