// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/state.js
// Citation settings + bibliography/capture state
// Extracted from js/sidebar.js (lines 228-240) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// Citation Management & Customization State
let savedBibliographies = [];
let citationSettings = {
  accessedDate: true,
  authorStyle: "standard", // standard | last-first | uppercase-last | uppercase-all | original
  removeDiacritics: false,
  dateStyle: "auto",
  autoCopy: false
};
let currentModalTab = "ieee";
let currentModalFilter = "";
let isElementCapturePicking = false;

