// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/citation/ui.js
// Citation display updates, input sync, source badges, toast engine
// Extracted from js/sidebar.js (lines 2025-2339) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// UI Updates
// ----------------------------------------------------------------------------
function updateCitationDisplay() {
  const box = document.getElementById("citation-text");
  const labelEl = document.getElementById("citation-box-style-label");
  if (!box) return;

  const activeNotes = (document.getElementById("f-notes")?.value || currentMeta.notes || "").trim();
  currentMeta.notes = activeNotes;

  updateSourceBadges(currentMeta.sourceType, currentMeta.container);

  box.classList.remove("bibtex-code");

  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  const localizedStyleLabels = {
    vi: {
      ieee: "Định dạng: IEEE (Kỹ thuật & CNTT)",
      apa: "Định dạng: APA 7th (Khoa học & Đồ án)",
      harvard: "Định dạng: Harvard (Kinh tế & Quản trị)",
      bibtex: "Định dạng: BibTeX (LaTeX / Overleaf)",
      mla: "Định dạng: MLA 9th (Ngôn ngữ & Nhân văn)",
      intext: "Định dạng: Trích dẫn trong bài"
    },
    en: {
      ieee: "Format: IEEE (Engineering & CS)",
      apa: "Format: APA 7th (Science & Thesis)",
      harvard: "Format: Harvard (Economics & Business)",
      bibtex: "Format: BibTeX (LaTeX / Overleaf)",
      mla: "Format: MLA 9th (Humanities & Arts)",
      intext: "Format: In-Text Citation"
    },
    zh: {
      ieee: "格式：IEEE (工程与计算机)",
      apa: "格式：APA 第7版 (学术论文)",
      harvard: "格式：Harvard (经管学术)",
      bibtex: "格式：BibTeX (LaTeX / Overleaf)",
      mla: "格式：MLA 第9版 (人文社科)",
      intext: "格式：正文内引用"
    },
    ru: {
      ieee: "Формат: IEEE (Техника и IT)",
      apa: "Формат: APA 7-е изд. (Наука и статьи)",
      harvard: "Формат: Harvard (Экономика и бизнес)",
      bibtex: "Формат: BibTeX (LaTeX / Overleaf)",
      mla: "Формат: MLA 9-е изд. (Гуманитарные науки)",
      intext: "Формат: Внутритекстовая ссылка"
    },
    ja: {
      ieee: "形式: IEEE (工学・情報科学)",
      apa: "形式: APA 第7版 (心理学・社会科学)",
      harvard: "形式: Harvard (経済・ビジネス)",
      bibtex: "形式: BibTeX (LaTeX / Overleaf)",
      mla: "形式: MLA 第9版 (人文学・文学)",
      intext: "形式: 本文内引用"
    }
  };
  const activeStyleDict = localizedStyleLabels[lang] || localizedStyleLabels.en;
  if (labelEl) {
    labelEl.textContent = activeStyleDict[currentCitationTab] || activeStyleDict.ieee;
  }

  let formattedCite = getFormattedCitationByStyle(currentMeta, currentCitationTab, 1);
  if (currentCitationTab !== "ieee" && currentCitationTab !== "apa" && currentCitationTab !== "harvard" && currentCitationTab !== "mla" && currentCitationTab !== "intext" && currentCitationTab !== "bibtex") {
    formattedCite = buildIeeeCitation(currentMeta);
  }
  
  if (currentCitationTab === "bibtex") {
    box.classList.add("bibtex-code");
    box.style.fontFamily = "ui-monospace, monospace";
    box.style.whiteSpace = "pre-wrap";
    box.style.color = "#a5f3fc";
    box.textContent = formattedCite;
  } else {
    box.style.fontFamily = "";
    box.style.whiteSpace = "";
    box.style.color = "";
    box.textContent = "";
    appendFormattedText(box, formattedCite);
    if (activeNotes) box.appendChild(createResearchNoteNode(activeNotes, lang));
  }
}

function getSourceBadgeLabel(sourceType, container) {
  const lang = window.i18n ? window.i18n.getLanguage() : "vi";
  const dict = {
    vi: {
      webpage: "Trang Web",
      web: "Trang Web",
      academic: "Học thuật",
      conference: "Hội thảo",
      pdf: "Tài liệu PDF",
      software: "Phần mềm",
      video: "Video",
      youtube: "YouTube",
      book: "Sách / Luận văn",
      news: "Báo chí"
    },
    en: {
      webpage: "Web Page",
      web: "Web Page",
      academic: "Academic",
      conference: "Conference",
      pdf: "PDF / Report",
      software: "Software",
      video: "Video",
      youtube: "YouTube",
      book: "Book / Thesis",
      news: "News"
    },
    zh: {
      webpage: "网页",
      web: "网页",
      academic: "学术论文",
      conference: "学术会议",
      pdf: "PDF 文档",
      software: "开源软件",
      video: "在线视频",
      youtube: "YouTube",
      book: "图书/论文",
      news: "新闻报道"
    },
    ru: {
      webpage: "Веб-страница",
      web: "Веб-страница",
      academic: "Научная статья",
      conference: "Конференция",
      pdf: "PDF / Отчёт",
      software: "ПО / Код",
      video: "Онлайн-видео",
      youtube: "YouTube",
      book: "Книга / Дис.",
      news: "Новости"
    },
    ja: {
      webpage: "Webページ",
      web: "Webページ",
      academic: "学術論文",
      conference: "学会・会議",
      pdf: "PDF / 報告書",
      software: "ソフトウェア",
      video: "オンライン動画",
      youtube: "YouTube",
      book: "書籍・論文",
      news: "ニュース"
    }
  };
  const lDict = dict[lang] || dict.en;
  let key = (sourceType || "webpage").toLowerCase();
  if (key.includes("web")) key = "webpage";
  else if (key.includes("acad") || key.includes("journal")) key = "academic";
  else if (key.includes("conf")) key = "conference";
  else if (key.includes("pdf")) key = "pdf";
  else if (key.includes("soft") || key.includes("git")) key = "software";
  else if (key.includes("youtu")) key = "youtube";
  else if (key.includes("vid")) key = "video";
  else if (key.includes("book") || key.includes("thesis")) key = "book";
  else if (key.includes("news")) key = "news";
  return lDict[key] || lDict.webpage || "Web";
}

function updateSourceBadges(type, container) {
  const label = getSourceBadgeLabel(type, container);
  const headerBadge = document.getElementById("source-badge");
  if (headerBadge) {
    headerBadge.textContent = label;
    headerBadge.title = `Source: ${container || type || "Web"}`;
  }
  const boxBadge = document.getElementById("citation-box-source-badge");
  if (boxBadge) {
    boxBadge.textContent = label;
    boxBadge.title = `Source: ${container || type || "Web"}`;
  }
  const metricsBadge = document.getElementById("citation-box-metrics-badge");
  if (metricsBadge) {
    if (currentMeta && typeof currentMeta.cited_by_count === 'number') {
      const count = currentMeta.cited_by_count;
      const countFormatted = count.toLocaleString ? count.toLocaleString() : count;
      const badgeText = (window.i18n && typeof window.i18n.t === "function") 
        ? window.i18n.t("metrics_citations_count", null, { count: countFormatted }) 
        : `🔄 ${countFormatted} trích dẫn`;
      const badgeTitle = (window.i18n && typeof window.i18n.t === "function") 
        ? window.i18n.t("metrics_citations_tooltip", null, { count: countFormatted }) 
        : `Số lượt trích dẫn học thuật quốc tế (OpenAlex): ${countFormatted}`;
      metricsBadge.textContent = badgeText;
      metricsBadge.title = badgeTitle;
      metricsBadge.style.display = "inline-flex";
      metricsBadge.style.alignItems = "center";
    } else {
      metricsBadge.style.display = "none";
    }
  }
}

function syncInputs() {
  const elSourceType = document.getElementById("f-source-type");
  const elAuthors = document.getElementById("f-authors");
  const elTitle = document.getElementById("f-title");
  const elDate = document.getElementById("f-date");
  const elContainer = document.getElementById("f-container");
  const elDoi = document.getElementById("f-doi");
  const elPages = document.getElementById("f-pages");
  const elUrl = document.getElementById("f-url");
  const elTag = document.getElementById("f-tag");
  const elNotes = document.getElementById("f-notes");

  if (elSourceType) elSourceType.value = currentMeta.sourceType || "webpage";
  if (elAuthors) elAuthors.value = currentMeta.authors || "";
  if (elTitle) elTitle.value = currentMeta.title || "";
  if (elDate) elDate.value = currentMeta.date || "";
  if (elContainer) elContainer.value = currentMeta.container || "";
  if (elDoi) elDoi.value = currentMeta.doi || "";
  if (elPages) elPages.value = currentMeta.pages || "";
  if (elUrl) elUrl.value = currentMeta.url || "";
  if (elTag) elTag.value = currentMeta.tag || "";
  if (elNotes) elNotes.value = currentMeta.notes || "";

  updateNotesClearButton();

  updateSourceBadges(currentMeta.sourceType, currentMeta.container);

  // Contextual placeholders based on source type
  if (currentMeta.sourceType === "pdf") {
    if (elContainer) elContainer.placeholder = "Tổ chức / Viện nghiên cứu (Vd: OpenAI, WHO, Viện Hàn lâm, Bộ TT&TT...)";
    if (elPages) elPages.placeholder = "Mã báo cáo / Số trang (Vd: Tech. Rep. 102, hoặc pp. 1-45)";
  } else if (currentMeta.sourceType === "academic") {
    if (elContainer) elContainer.placeholder = "Tên tạp chí (Vd: Tạp chí KH&CN ĐH Đà Nẵng, IEEE, Nature...)";
    if (elPages) elPages.placeholder = "Trang (Vd: pp. 127-131), Tập / Số";
  } else if (currentMeta.sourceType === "software") {
    if (elContainer) elContainer.placeholder = "Kho lưu trữ (Vd: GitHub, GitLab)";
    if (elPages) elPages.placeholder = "Phiên bản (Vd: v1.0.0)";
  } else if (currentMeta.sourceType === "video") {
    if (elContainer) elContainer.placeholder = "Kênh / Nền tảng (Vd: YouTube, TED Talks)";
    if (elPages) elPages.placeholder = "Thời lượng hoặc Timestamp (Vd: 14:20)";
  } else {
    if (elContainer) elContainer.placeholder = "Tên website / Nhà xuất bản...";
    if (elPages) elPages.placeholder = "Trang (pp.) / Số báo / Phiên bản";
  }
}

function syncMetaFromInputs() {
  try {
    currentMeta.sourceType = document.getElementById("f-source-type")?.value || currentMeta.sourceType || "webpage";
    currentMeta.authors = document.getElementById("f-authors")?.value || "";
    currentMeta.title = document.getElementById("f-title")?.value || "";
    const rawDate = document.getElementById("f-date")?.value || "";
    currentMeta.date = (typeof parseComprehensiveDate === "function" ? parseComprehensiveDate(rawDate) : null) || rawDate;
    currentMeta.container = document.getElementById("f-container")?.value || "";
    currentMeta.doi = document.getElementById("f-doi")?.value || "";
    currentMeta.pages = document.getElementById("f-pages")?.value || "";
    currentMeta.url = document.getElementById("f-url")?.value || "";
    currentMeta.tag = document.getElementById("f-tag")?.value || "";
    currentMeta.notes = document.getElementById("f-notes")?.value || "";

    updateSourceBadges(currentMeta.sourceType, currentMeta.container);

    const elContainer = document.getElementById("f-container");
    const elPages = document.getElementById("f-pages");
    if (currentMeta.sourceType === "pdf") {
      if (elContainer) elContainer.placeholder = "Tổ chức / Viện nghiên cứu (Vd: OpenAI, WHO, Viện Hàn lâm, Bộ TT&TT...)";
      if (elPages) elPages.placeholder = "Mã báo cáo / Số trang (Vd: Tech. Rep. 102, hoặc pp. 1-45)";
    }

    updateCitationDisplay();
    saveDraft();
  } catch (err) {
    console.warn("syncMetaFromInputs error:", err);
    updateCitationDisplay();
  }
}

function showToast(msgKey, type = 'success', variables = []) {
  const t = document.getElementById('notify');
  if (!t) return;
  
  // Reset classes
  t.className = 'notify';
  if (type) t.classList.add('notify-' + type);
  
  // Get translation from i18n
  let msg = msgKey;
  if (window.i18n && typeof window.i18n.t === "function") {
    const curLang = (typeof window.i18n.getCurrentLanguage === "function") ? window.i18n.getCurrentLanguage() : (window.i18n.getLanguage ? window.i18n.getLanguage() : "vi");
    const tr = window.i18n.t(msgKey, curLang);
    if (tr && tr !== msgKey) {
      msg = tr;
    } else {
      const dataObj = window.I18N_DATA || (window.i18n && window.i18n.DATA) || (typeof I18N_DATA !== "undefined" ? I18N_DATA : null);
      if (dataObj && dataObj[curLang] && dataObj[curLang][msgKey]) {
        msg = dataObj[curLang][msgKey];
      }
    }
  }
  
  // Replace variables like {0}, {1} if any
  if (Array.isArray(variables)) {
    variables.forEach((val, i) => {
      msg = msg.split('{' + i + '}').join(val !== undefined && val !== null ? val : "");
    });
  } else if (variables && typeof variables === "object") {
    for (const [k, v] of Object.entries(variables)) {
      msg = msg.split('{' + k + '}').join(v !== undefined && v !== null ? v : "");
    }
  }
  
  t.textContent = msg;
  t.classList.add('show');
  
  setTimeout(() => {
    t.classList.remove('show');
  }, 3000);
}


