// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/init.js
// DOM-ready bootstrap + full event wiring for every tab
// Extracted from js/sidebar.js (lines 5310-7493) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Initialization
// ----------------------------------------------------------------------------
function onReady(fn) {
  if (document.readyState !== "loading") {
    fn();
  } else {
    document.addEventListener("DOMContentLoaded", fn);
  }
}

onReady(() => {
  // Main Tabs navigation
  document.querySelectorAll(".main-nav-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".main-nav-btn").forEach(b => b.classList.remove("active"));
      document.querySelectorAll(".tab-section").forEach(s => s.classList.remove("active"));
      btn.classList.add("active");
      const target = btn.dataset.target;
      const sec = document.getElementById(target);
      if (sec) sec.classList.add("active");
      const navWrap = document.getElementById("nav-wrapper");
      if (navWrap) {
        const btnLeft = btn.offsetLeft;
        const btnWidth = btn.offsetWidth;
        const wrapWidth = navWrap.clientWidth;
        navWrap.scrollTo({
          left: btnLeft - (wrapWidth / 2) + (btnWidth / 2),
          behavior: "smooth"
        });
      }
      if (target === "tab-cookie") {
        updateCookieTabUI();
      }
      if (target === "tab-cal") {
        calRenderCalendar();
      }
    });
  });

  // Citation Sub-Tabs (Tab 1 only)
  document.querySelectorAll("#tab-cite .sub-tab-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll("#tab-cite .sub-tab-btn").forEach(b => b.classList.remove("active"));
      btn.classList.add("active");
      currentCitationTab = btn.dataset.tab;
      updateCitationDisplay();
      if (citationSettings.autoCopy) {
        const txt = document.getElementById("citation-text")?.textContent || "";
        if (navigator.clipboard?.writeText) {
          navigator.clipboard.writeText(txt).then(() => showToast("✓ Đã tự động sao chép!")).catch(() => {});
        }
      }
    });
  });

  // Live input sync
  ["f-source-type", "f-authors", "f-title", "f-date", "f-container", "f-doi", "f-pages", "f-url", "f-tag", "f-notes"].forEach(id => {
    const el = document.getElementById(id);
    if (el) {
      el.addEventListener("input", syncMetaFromInputs);
      el.addEventListener("change", syncMetaFromInputs);
      if (id === "f-notes" || id === "f-title") {
        el.addEventListener("keyup", syncMetaFromInputs);
        el.addEventListener("paste", () => setTimeout(syncMetaFromInputs, 20));
      }
      if (id === "f-authors") {
        el.addEventListener("blur", () => {
          if (el.value && (el.value.includes(",") || el.value.includes(";"))) {
            const norm = normalizeAuthorsString(el.value);
            if (norm && norm !== el.value) {
              el.value = norm;
              currentMeta.authors = norm;
              updateCitationDisplay();
              saveDraft();
            }
          }
        });
      }
    }
  });

  // Clear research notes with trash button
  const notesClearBtn = document.getElementById("btn-clear-notes");
  const notesInputEl = document.getElementById("f-notes");
  if (notesClearBtn && notesInputEl) {
    notesInputEl.addEventListener("input", updateNotesClearButton);
    notesInputEl.addEventListener("keyup", updateNotesClearButton);
    notesClearBtn.addEventListener("click", () => {
      notesInputEl.value = "";
      updateNotesClearButton();
      notesAutoResize();
      notesUpdatePreview();
      currentMeta.notes = "";
      updateCitationDisplay();
      saveDraft();
      notesInputEl.focus();
    });
    updateNotesClearButton();
    notesInputEl.addEventListener("click", () => { notesAutoResize(); });
    notesInitToolbar();
  }

  // Copy citation with instant visual button feedback & Rich Text support (Italics for Word/Docs)
  document.getElementById("btn-copy-cite")?.addEventListener("click", () => {
    const box = document.getElementById("citation-text");
    const btn = document.getElementById("btn-copy-cite");

    let formattedCite = getFormattedCitationByStyle(currentMeta, currentCitationTab, 1);
    if (currentCitationTab !== "ieee" && currentCitationTab !== "apa" && currentCitationTab !== "harvard" && currentCitationTab !== "mla" && currentCitationTab !== "intext" && currentCitationTab !== "bibtex") {
      formattedCite = buildIeeeCitation(currentMeta);
    }
    const lang = window.i18n ? window.i18n.getLanguage() : "vi";
    const activeNotes = (document.getElementById("f-notes")?.value || currentMeta.notes || "").trim();
    const notePlain = activeNotes ? formatResearchNote(activeNotes, lang, false) : "";
    const noteHtml = activeNotes ? formatResearchNote(activeNotes, lang, true) : "";
    
    let htmlCite = formattedCite
       .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
       .replace(/\*([^\*]+)\*/g, "<i>$1</i>");
    const richHtml = htmlCite + noteHtml;
    const txt = currentCitationTab === "bibtex" ? formattedCite : (formattedCite + notePlain);

    const onCopySuccess = () => {
      if (btn) {
        const savedChildren = Array.from(btn.childNodes).map((n) => n.cloneNode(true));
        btn.textContent = "";
        const checkIcon = document.createElement("span");
        checkIcon.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>';
        const checkLabel = document.createElement("span");
        checkLabel.textContent = window.i18n ? window.i18n.t("btn_copied") : "Đã sao chép";
        btn.appendChild(checkIcon);
        btn.appendChild(checkLabel);
        btn.style.background = "linear-gradient(135deg, #10b981 0%, #059669 100%)";
        setTimeout(() => {
          btn.textContent = "";
          savedChildren.forEach((n) => btn.appendChild(n));
          btn.style.background = "";
        }, 1400);
      }
      showToast("toast_citation_copied_style", "success", [(currentCitationTab || "").toUpperCase()]);
    };

    if (currentCitationTab !== "bibtex" && typeof ClipboardItem !== "undefined" && navigator.clipboard?.write && richHtml) {
      const blobText = new Blob([txt], { type: "text/plain" });
      const blobHtml = new Blob([richHtml], { type: "text/html" });
      navigator.clipboard.write([
        new ClipboardItem({
          "text/plain": blobText,
          "text/html": blobHtml
        })
      ]).then(onCopySuccess).catch(() => {
        navigator.clipboard.writeText(txt).then(onCopySuccess).catch(() => showToast("⚠️ Không thể sao chép"));
      });
    } else if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(txt).then(onCopySuccess).catch(() => {
        showToast("⚠️ Không thể sao chép vào bộ nhớ tạm");
      });
    }
  });

  // Re-read current page metadata (clean reload)
  document.getElementById("btn-refresh-cite")?.addEventListener("click", async () => {
    const btnRefresh = document.getElementById("btn-refresh-cite");
    if (btnRefresh) {
      btnRefresh.querySelector("svg").style.transition = "transform 0.5s ease";
      btnRefresh.querySelector("svg").style.transform = "rotate(360deg)";
      setTimeout(() => { btnRefresh.querySelector("svg").style.transform = ""; }, 500);
    }
    showToast(typeof getI18nText === "function" ? getI18nText("toast_syncing") : "Đang tải lại thông tin...");

    // Discard any draft from storage for this URL so live page data is cleanly restored
    const dKey = getDraftKey();
    if (dKey) {
      storRemove(dKey);
    }
    const draftBanner = document.getElementById("draft-banner");
    if (draftBanner) draftBanner.style.display = "none";

    await syncActiveTabData(true, true);
    showToast(typeof getI18nText === "function" ? getI18nText("toast_sync_done") : "✓ Đã cập nhật trích dẫn mới!");
  });

  // Local PDF Upload & Drag-and-drop
  const inputPdf = document.getElementById("input-local-pdf-file");
  const btnUploadPdf = document.getElementById("btn-upload-local-pdf");
  if (btnUploadPdf && inputPdf) {
    btnUploadPdf.addEventListener("click", () => {
      inputPdf.click();
    });
    inputPdf.addEventListener("change", (e) => {
      const file = e.target.files?.[0];
      if (!file) return;
      showToast("toast_pdf_loading", "info", [file.name]);
      const reader = new FileReader();
      reader.onload = (evt) => {
        try {
          const buf = evt.target.result;
          const meta = parsePdfBuffer(buf, file.name);
          currentMeta = {
            ...currentMeta,
            sourceType: "pdf",
            title: meta.title || cleanPdfFilenameToTitle("", file.name),
            authors: meta.authors || "",
            date: meta.date || "",
            container: meta.container || "Tài liệu cục bộ (PDF)",
            pages: "",
            url: file.name,
            doi: ""
          };
          originalExtractedMeta = { ...currentMeta };
          syncInputs();
          updateCitationDisplay();
          showToast("toast_pdf_loaded", "success", [file.name]);
        } catch (err) {
          console.error("Local PDF parsing error:", err);
          showToast("toast_pdf_extract_err", "error");
        }
      };
      reader.readAsArrayBuffer(file);
    });
  }

  // Drag & drop PDF files directly into citation box
  const citeBox = document.getElementById("citation-text");
  if (citeBox) {
    citeBox.addEventListener("dragover", (e) => {
      e.preventDefault();
      citeBox.style.borderColor = "#38bdf8";
      citeBox.style.background = "rgba(56, 189, 248, 0.08)";
    });
    citeBox.addEventListener("dragleave", () => {
      citeBox.style.borderColor = "";
      citeBox.style.background = "";
    });
    citeBox.addEventListener("drop", (e) => {
      e.preventDefault();
      citeBox.style.borderColor = "";
      citeBox.style.background = "";
      const file = e.dataTransfer.files?.[0];
      if (file && (file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf"))) {
        showToast("toast_pdf_loading", "info", [file.name]);
        const reader = new FileReader();
        reader.onload = (evt) => {
          try {
            const buf = evt.target.result;
            const meta = parsePdfBuffer(buf, file.name);
            currentMeta = {
              ...currentMeta,
              sourceType: "pdf",
              title: meta.title || cleanPdfFilenameToTitle("", file.name),
              authors: meta.authors || "",
              date: meta.date || "",
              container: meta.container || "Tài liệu cục bộ (PDF)",
              pages: "",
              url: file.name,
              doi: ""
            };
            originalExtractedMeta = { ...currentMeta };
            syncInputs();
            updateCitationDisplay();
            showToast("toast_pdf_loaded", "success", [file.name]);
          } catch (err) {
            console.error("Local PDF drag parsing error:", err);
            showToast("toast_pdf_extract_err", "error");
          }
        };
        reader.readAsArrayBuffer(file);
      }
    });
  }

  // Author Rules Guide Modal
  document.getElementById("btn-show-author-rules")?.addEventListener("click", () => {
    const m = document.getElementById("author-rules-modal");
    if (m) m.style.display = "block";
  });
  document.getElementById("btn-close-author-rules")?.addEventListener("click", () => {
    const m = document.getElementById("author-rules-modal");
    if (m) m.style.display = "none";
  });

  // Trust, Standards & Privacy Modal
  const trustModal = document.getElementById("trust-modal");
  document.getElementById("btn-open-trust")?.addEventListener("click", () => {
    if (trustModal) trustModal.style.display = "block";
  });
  document.getElementById("btn-close-trust")?.addEventListener("click", () => {
    if (trustModal) trustModal.style.display = "none";
  });
  trustModal?.addEventListener("click", (e) => {
    if (e.target === trustModal) trustModal.style.display = "none";
  });
  // -----------------------------------------
  // Cookie Manager: Raw String (Copy / Import)
  // -----------------------------------------
  document.getElementById("btn-copy-raw-cookie")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_export_no_url", "warning");
    try {
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
      if (!cookiesApi) return showToast("toast_cookie_export_no_api", "error");
      
      const cookies = await cookiesApi.getAll({ url: currentTabUrl });
      if (!cookies || cookies.length === 0) return showToast("toast_cookie_export_empty", "warning");
      
      const rawString = cookies.map(c => `${c.name}=${c.value}`).join("; ");
      const textarea = document.getElementById("cookie-raw-text");
      if (textarea) textarea.value = rawString;
      
      await navigator.clipboard.writeText(rawString);
      showToast("toast_cookie_str_copied", "success", [cookies.length]);
    } catch (e) {
      console.error(e);
      showToast("toast_cookie_export_error", "error");
    }
  });

document.getElementById("btn-import-raw-cookie")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_export_no_url", "warning");
    const rawString = document.getElementById("cookie-raw-text")?.value.trim();
    if (!rawString) return showToast("toast_cookie_paste_needed", "warning");
    
    try {
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
      if (!cookiesApi) return showToast("toast_cookie_export_no_api", "error");
      
      const pairs = rawString.split(";").map(s => s.trim()).filter(s => s.length > 0);
      let successCount = 0;
      const urlObj = new URL(currentTabUrl);
      const domain = urlObj.hostname;
      const urlStr = urlObj.origin + "/";
      
      const setPromises = pairs.map(async (pair) => {
        const idx = pair.indexOf("=");
        if (idx < 0) return false;
        const name = pair.substring(0, idx).trim();
        const value = pair.substring(idx + 1).trim();
        try {
          await cookiesApi.set({
            url: urlStr,
            name: name,
            value: value,
            domain: domain,
            path: "/"
          });
          return true;
        } catch(e) {
          console.warn("Failed to set raw cookie", name, e);
          return false;
        }
      });
      const results = await Promise.all(setPromises);
      successCount = results.filter(r => r).length;
      showToast("toast_cookie_imported", "success", [successCount]);
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi && currentTabObj?.id) tabsApi.reload(currentTabObj.id);
    } catch (e) {
      console.error(e);
      showToast("toast_cookie_import_error", "error");
    }
  });

  // -----------------------------------------
  // Cookie Manager: Import & Export JSON
  // -----------------------------------------
  
  // Restored RIS Events
  document.getElementById("btn-download-ris")?.addEventListener("click", () => {
    if (!currentMeta.title) return showToast("Chưa có thông tin để xuất RIS!", "warning");
    const risStr = buildRisCitation(currentMeta);
    const blob = new Blob([risStr], { type: "application/x-research-info-systems;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = (currentMeta.title.substring(0, 40).replace(/[^a-zA-Z0-9]/g, "_") || "citation") + ".ris";
    a.click();
    URL.revokeObjectURL(url);
    showToast("💾 Đã tải xuống file RIS!", "success");
  });

  document.getElementById("btn-export-ris-all")?.addEventListener("click", () => {
    exportRisAll();
  });

document.getElementById("btn-export-cookie")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_export_no_url", "warning");
    try {
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
      if (!cookiesApi) return showToast("toast_cookie_export_no_api", "error");
      
      const cookies = await cookiesApi.getAll({ url: currentTabUrl });
      if (!cookies || cookies.length === 0) return showToast("toast_cookie_export_empty", "warning");
      
      const blob = new Blob([JSON.stringify(cookies, null, 2)], { type: "application/json;charset=utf-8" });
      const u = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = u;
      const domain = new URL(currentTabUrl).hostname;
      a.download = `cookies_${domain}_${Date.now()}.json`;
      a.click();
      URL.revokeObjectURL(u);
      showToast("toast_cookie_export_success", "success", [cookies.length]);
    } catch (e) {
      console.error(e);
      showToast("toast_cookie_export_error", "error");
    }
  });

  const btnImportCookie = document.getElementById("btn-import-cookie");
  if (btnImportCookie) {
    let cookieInput = document.getElementById("input-cookie-file");
    if (!cookieInput) {
      cookieInput = document.createElement("input");
      cookieInput.type = "file";
      cookieInput.accept = ".json,application/json";
      cookieInput.style.display = "none";
      document.body.appendChild(cookieInput);
    }
    
    btnImportCookie.addEventListener("click", () => cookieInput.click());
    cookieInput.addEventListener("change", (e) => {
      const file = e.target.files?.[0];
      if (!file) return;
      
      const reader = new FileReader();
      reader.onload = async (evt) => {
        try {
          const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
          if (!cookiesApi) throw new Error("No API");
          
          const cookies = JSON.parse(evt.target.result);
          if (!Array.isArray(cookies)) throw new Error("Invalid format");
          
          let successCount = 0;
          const setPromises = cookies.map(async (c) => {
            let url = "http" + (c.secure ? "s" : "") + "://" + c.domain.replace(/^\./, "") + c.path;
            try {
              const targetStoreId = (currentTabObj && currentTabObj.cookieStoreId)
                ? currentTabObj.cookieStoreId
                : (c.storeId || undefined);
              const setArgs = {
                url: url,
                name: c.name,
                value: c.value,
                path: c.path,
                secure: c.secure,
                httpOnly: c.httpOnly
              };
              // Fix: Host-only cookies must not specify a domain.
              if (!c.hostOnly && c.domain) {
                setArgs.domain = c.domain;
              }
              // Fix: Preserve exact SameSite status (including unspecified).
              if (c.sameSite && ["no_restriction", "lax", "strict", "unspecified"].includes(c.sameSite.toLowerCase())) {
                setArgs.sameSite = c.sameSite.toLowerCase();
              }
              // Some browsers drop expirationDate if it's in the past or invalid. Optional.
              if (c.expirationDate) {
                 setArgs.expirationDate = c.expirationDate;
              }
              if (targetStoreId) setArgs.storeId = targetStoreId;
              
              await cookiesApi.set(setArgs);
              return true;
            } catch (err) {
              console.warn("Failed to set cookie:", c.name, err);
              return false;
            }
          });
          const results = await Promise.all(setPromises);
          successCount = results.filter(r => r).length;
          showToast("toast_cookie_import_success", "success", [successCount, cookies.length]);
          
          // Optionally reload the tab to apply cookies
          const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
          if (tabsApi && currentTabObj?.id) {
            tabsApi.reload(currentTabObj.id);
          }
        } catch (err) {
          console.error(err);
          showToast("toast_cookie_import_error", "error");
        }
        cookieInput.value = ""; // Reset
      };
      reader.readAsText(file);
    });
  }

  // -------------------------------------------------------------
  // Live Domain Tracking & Cookie Utilities
  // -------------------------------------------------------------
  async function updateCookieTabUI() {
    const domainEl = document.getElementById("cookie-current-domain");
    const countEl = document.getElementById("cookie-total-count");
    const rawTextEl = document.getElementById("cookie-raw-text");
    if (!domainEl || !countEl) return;

    if (!currentTabUrl || currentTabUrl.startsWith("about:") || currentTabUrl.startsWith("chrome:") || currentTabUrl.startsWith("moz-extension:")) {
      domainEl.textContent = "Không hỗ trợ trang nội bộ";
      countEl.textContent = "0";
      return;
    }

    try {
      const u = new URL(currentTabUrl);
      domainEl.textContent = u.hostname;
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : ((typeof chrome !== "undefined" ? chrome.cookies : null));
      if (cookiesApi) {
        const cookies = await cookiesApi.getAll({ url: currentTabUrl });
        const count = cookies ? cookies.length : 0;
        countEl.textContent = count.toString();
        if (rawTextEl && !rawTextEl.value && cookies && cookies.length > 0) {
          rawTextEl.value = cookies.map(c => `${c.name}=${c.value}`).join("; ");
        }
      }
    } catch (e) {
      console.warn("updateCookieTabUI error:", e);
    }
  }

  // Copy raw cookie string (name=value; name2=value2...)
  document.getElementById("btn-copy-raw-cookie")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_no_url", "warning");
    try {
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
      if (!cookiesApi) return showToast("toast_cookie_no_api", "error");
      const cookies = await cookiesApi.getAll({ url: currentTabUrl });
      if (!cookies || cookies.length === 0) return showToast("toast_cookie_none", "warning");
      const rawStr = cookies.map(c => `${c.name}=${c.value}`).join("; ");
      const rawTextEl = document.getElementById("cookie-raw-text");
      if (rawTextEl) rawTextEl.value = rawStr;
      await navigator.clipboard.writeText(rawStr);
      showToast("toast_cookie_str_copied", "success", [cookies.length]);
    } catch (e) {
      console.error(e);
      showToast("toast_cookie_copy_err", "error");
    }
  });

  // Import raw cookie string (name=value; name2=value2...)
  document.getElementById("btn-import-raw-cookie")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_no_url", "warning");
    const rawTextEl = document.getElementById("cookie-raw-text");
    const rawVal = (rawTextEl?.value || "").trim();
    if (!rawVal) return showToast("toast_cookie_paste_needed", "warning");
    try {
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
      if (!cookiesApi) return showToast("toast_cookie_no_api", "error");
      const pairs = rawVal.split(";").map(s => s.trim()).filter(Boolean);
      let success = 0;
      for (const pair of pairs) {
        const idx = pair.indexOf("=");
        if (idx === -1) continue;
        const name = pair.substring(0, idx).trim();
        const value = pair.substring(idx + 1).trim();
        try {
          await cookiesApi.set({
            url: currentTabUrl,
            name,
            value,
            path: "/"
          });
          success++;
        } catch (err) {}
      }
      showToast("toast_cookie_import_success", "success", [success, pairs.length]);
      updateCookieTabUI();
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi && currentTabObj?.id) {
        tabsApi.reload(currentTabObj.id);
      }
    } catch (e) {
      console.error(e);
      showToast("toast_cookie_import_err", "error");
    }
  });

  // Delete all cookies for current active page
  document.getElementById("btn-delete-current-cookies")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_no_url", "warning");
    try {
      const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
      if (!cookiesApi) return showToast("toast_cookie_no_api", "error");
      const cookies = await cookiesApi.getAll({ url: currentTabUrl });
      if (!cookies || cookies.length === 0) return showToast("toast_cookie_none", "warning");
      let removed = 0;
      for (const c of cookies) {
        const u = "http" + (c.secure ? "s" : "") + "://" + c.domain.replace(/^\./, "") + c.path;
        try {
          const removeArgs = { url: u, name: c.name, storeId: c.storeId };
          if (c.partitionKey) removeArgs.partitionKey = c.partitionKey;
          if (await cookiesApi.remove(removeArgs)) removed++;
        } catch (e) {}
      }
      const rawTextEl = document.getElementById("cookie-raw-text");
      if (rawTextEl) rawTextEl.value = "";
      showToast("toast_cookie_deleted", "success", [removed]);
      updateCookieTabUI();
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi && currentTabObj?.id) {
        tabsApi.reload(currentTabObj.id);
      }
    } catch (e) {
      console.error(e);
      showToast("toast_cookie_del_err", "error");
    }
  });

  // Bypass paywall: Clear site cookies + cache + localStorage, then reload fresh
  document.getElementById("btn-clear-site-data")?.addEventListener("click", async () => {
    if (!currentTabUrl) return showToast("toast_cookie_no_url", "warning");
    if (/^(about:|chrome:|moz-extension:|edge:|view-source:|devtools:)/i.test(currentTabUrl)) {
      return showToast("toast_cookie_no_url", "warning");
    }

    let parsed;
    try {
      parsed = new URL(currentTabUrl);
    } catch (e) {
      return showToast("toast_cookie_no_url", "warning");
    }
    const hostname = parsed.hostname;
    const origin = parsed.origin;

    const isFirefox = typeof navigator !== "undefined" && /firefox/i.test(navigator.userAgent || "");
    const cookiesApi = (typeof browser !== "undefined" && browser.cookies) ? browser.cookies : (typeof chrome !== "undefined" ? chrome.cookies : null);
    const browsingData = (typeof browser !== "undefined" && browser.browsingData) ? browser.browsingData : (typeof chrome !== "undefined" ? chrome.browsingData : null);
    const scriptingApi = (typeof chrome !== "undefined" && chrome.scripting) ? chrome.scripting : ((typeof browser !== "undefined" && browser.scripting) ? browser.scripting : null);
    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);

    let anyWorked = false;

    try {
      // 1) Cookies via cookies API — handles Firefox Total Cookie Protection (partitioned cookies)
      if (cookiesApi) {
        try {
          const cookies = await cookiesApi.getAll({ url: currentTabUrl });
          if (cookies && cookies.length > 0) {
            let removed = 0;
            for (const c of cookies) {
              const u = "http" + (c.secure ? "s" : "") + "://" + c.domain.replace(/^\./, "") + c.path;
              const args = { url: u, name: c.name };
              if (c.storeId) args.storeId = c.storeId;
              if (c.partitionKey) args.partitionKey = c.partitionKey;
              try {
                if (await cookiesApi.remove(args)) removed++;
              } catch (err) {
                console.warn("[BypassPaywall] cookie remove failed:", c.name, err);
              }
            }
            console.log("[BypassPaywall] removed cookies:", removed, "/", cookies.length);
            if (removed > 0) anyWorked = true;
          }
        } catch (err) {
          console.warn("[BypassPaywall] cookies.getAll failed:", err);
        }
      }

      // 2) Cache + localStorage + indexedDB + serviceWorkers, scoped to this site.
      //    NOTE: Firefox schema only accepts its own keys/options — using
      //    `hostnames` + Firefox-supported keys, Chrome keys/`origins` otherwise.
      if (browsingData) {
        try {
          const dataTypes = { cache: true, localStorage: true, indexedDB: true, serviceWorkers: true };
          if (!isFirefox) {
            dataTypes.cacheStorage = true;
            dataTypes.fileSystems = true;
            dataTypes.webSQL = true;
          }
          const removalOptions = isFirefox
            ? { hostnames: [hostname] }
            : { since: 0, origins: [origin] };
          await browsingData.remove(removalOptions, dataTypes);
          anyWorked = true;
        } catch (err) {
          console.warn("[BypassPaywall] browsingData.remove failed, using dedicated APIs:", err);
          try { await browsingData.removeCache({}); anyWorked = true; } catch (e2) { console.warn("[BypassPaywall]", e2); }
          try { await browsingData.removeLocalStorage({ hostnames: [hostname] }); anyWorked = true; } catch (e2) { console.warn("[BypassPaywall]", e2); }
        }
      }

      // 3) Wipe localStorage/sessionStorage in the live tab as a last resort
      if (!anyWorked && scriptingApi && currentTabObj?.id) {
        try {
          await scriptingApi.executeScript({
            target: { tabId: currentTabObj.id },
            func: () => {
              try { localStorage.clear(); } catch (e) {}
              try { sessionStorage.clear(); } catch (e) {}
            }
          });
          anyWorked = true;
        } catch (err) {
          console.warn("[BypassPaywall] executeScript failed:", err);
        }
      }

      const rawTextEl = document.getElementById("cookie-raw-text");
      if (rawTextEl) rawTextEl.value = "";

      // 4) Reload WITHOUT cache so the site must build a brand-new session
      if (tabsApi && currentTabObj?.id) {
        try {
          await tabsApi.reload(currentTabObj.id, { bypassCache: true });
        } catch (e) {
          try { tabsApi.reload(currentTabObj.id); } catch (e2) { console.warn("[BypassPaywall] reload failed:", e2); }
        }
      }

      if (anyWorked) {
        showToast("toast_site_data_cleared", "success");
      } else {
        showToast("toast_site_data_err", "error");
      }
      setTimeout(updateCookieTabUI, 1000);
    } catch (e) {
      console.error("[BypassPaywall] error:", e);
      showToast("toast_site_data_err", "error");
    }
  });



  // Open Sidebar / Side Panel from Popup
  document.getElementById("btn-open-sidebar")?.addEventListener("click", () => {
    try {
      if (typeof chrome !== "undefined" && chrome.runtime) {
        chrome.runtime.sendMessage({ action: "OPEN_IN_PAGE_SIDEBAR" });
      } else if (typeof browser !== "undefined" && browser.runtime) {
        browser.runtime.sendMessage({ action: "OPEN_IN_PAGE_SIDEBAR" });
      }
    } catch (e) {}
    if (document.body.classList.contains("is-popup")) {
      setTimeout(() => window.close(), 100);
    }
  });

  // Privacy Policy Link
  document.getElementById("link-privacy-policy")?.addEventListener("click", (e) => {
    e.preventDefault();
    const curLang = (window.i18n && window.i18n.getCurrentLanguage) ? window.i18n.getCurrentLanguage() : "vi";
    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
    const runtimeApi = (typeof browser !== "undefined" && browser.runtime) ? browser.runtime : (typeof chrome !== "undefined" ? chrome.runtime : null);
    if (tabsApi && runtimeApi) {
      tabsApi.create({ url: runtimeApi.getURL(`OS/html/privacy.html?lang=${curLang}`) });
    } else {
      window.open(`privacy.html?lang=${curLang}`, "_blank");
    }
  });

  // Save current citation to bibliography
  document.getElementById("btn-save-biblio")?.addEventListener("click", saveCurrentToBiblio);

  // Open & Close Bibliography Modal
  document.getElementById("btn-open-biblio")?.addEventListener("click", () => {
    const bm = document.getElementById("biblio-modal");
    if (bm) bm.style.display = "block";
    renderBiblioModalList();
  });
  document.getElementById("btn-close-biblio")?.addEventListener("click", () => {
    const bm = document.getElementById("biblio-modal");
    if (bm) bm.style.display = "none";
  });

  // Search filter inside modal
  document.getElementById("biblio-search-input")?.addEventListener("input", (e) => {
    currentModalFilter = e.target.value;
    renderBiblioModalList();
  });

  // Modal Style Selector Tabs
  ["ieee", "apa", "harvard", "bibtex", "mla"].forEach(tabKey => {
    document.getElementById(`modal-tab-${tabKey}`)?.addEventListener("click", () => {
      ["ieee", "apa", "harvard", "bibtex", "mla"].forEach(k => {
        document.getElementById(`modal-tab-${k}`)?.classList.toggle("active", k === tabKey);
      });
      currentModalTab = tabKey;
      renderBiblioModalList();
    });
  });

  // Modal Bulk Action Buttons
  document.getElementById("btn-copy-all-biblio")?.addEventListener("click", copyAllBiblio);
  document.getElementById("btn-export-bib-all")?.addEventListener("click", exportBibAll);
  document.getElementById("btn-export-ris-all")?.addEventListener("click", exportRisAll);
  document.getElementById("btn-export-txt-all")?.addEventListener("click", exportTxtAll);
  document.getElementById("btn-clear-all-biblio")?.addEventListener("click", clearAllBiblio);

  // Citation Customization Settings Auto-Save
  document.getElementById("cite-pref-accessed")?.addEventListener("change", saveCitationSettings);
  document.getElementById("cite-pref-remove-diacritics")?.addEventListener("change", saveCitationSettings);
  document.getElementById("cite-pref-author-style")?.addEventListener("change", saveCitationSettings);
  document.getElementById("cite-pref-date-style")?.addEventListener("change", saveCitationSettings);
  document.getElementById("cite-pref-autocopy")?.addEventListener("change", saveCitationSettings);

  // Quick action author buttons (Bỏ dấu & In hoa)
  document.getElementById("btn-quick-nodiacritics")?.addEventListener("click", () => {
    const el = document.getElementById("f-authors");
    if (el && el.value) {
      el.value = removeVietnameseDiacritics(el.value);
      currentMeta.authors = el.value;
      updateCitationDisplay();
      saveDraft();
      showToast("✓ Đã chuyển sang không dấu!");
    }
  });

  document.getElementById("btn-quick-uppercase")?.addEventListener("click", () => {
    const el = document.getElementById("f-authors");
    if (el && el.value) {
      el.value = removeVietnameseDiacritics(el.value).toUpperCase();
      currentMeta.authors = el.value;
      updateCitationDisplay();
      saveDraft();
      showToast("✓ Đã in hoa toàn bộ!");
    }
  });

  // Download .bib
  document.getElementById("btn-download-bib")?.addEventListener("click", () => {
    const bib = buildBibtexCitation(currentMeta);
    const blob = new Blob([bib], { type: "text/plain;charset=utf-8" });
    const u = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = u;
    a.download = `${generateBibtexKey(currentMeta.authors, currentMeta.date, currentMeta.title)}.bib`;
    a.click();
    URL.revokeObjectURL(u);
  });

  // Reset draft
  document.getElementById("btn-reset-draft")?.addEventListener("click", () => {
    storRemove(getDraftKey(), () => {
      if (originalExtractedMeta) {
        currentMeta = { ...originalExtractedMeta };
        syncInputs();
        updateCitationDisplay();
      }
      const db = document.getElementById("draft-banner");
      if (db) db.style.display = "none";
      showToast("✓ Đã đặt lại từ trang gốc!");
    });
  });

  // Tab 2: Redaction Controls - Separate Buttons
  document.getElementById("btn-start-inspect")?.addEventListener("click", () => {
    isInspectMode = true;
    updateInspectButtonsUI();
    // If redactions were paused, unpause so newly picked redactions are immediately visible
    if (isRedactionsPaused) {
      isRedactionsPaused = false;
      updateRedactionVisibilityUI();
      sendTabMessage({ action: "TOGGLE_REDACTIONS_PAUSE", paused: false });
    }
    sendTabMessage({
      action: "START_INSPECT",
      style: currentRedactStyle,
      blurPx: currentBlurPx
    }, (res) => {
      if (res && Array.isArray(res.list)) {
        const rc = document.getElementById("redact-count");
        if (rc) rc.textContent = res.count || 0;
        renderRedactedList(res.list);
      }
      showToast("🎯 Đã bật chế độ chọn che đối tượng!");
    });
  });

  document.getElementById("btn-stop-inspect")?.addEventListener("click", () => {
    isInspectMode = false;
    updateInspectButtonsUI();
    sendTabMessage({ action: "STOP_INSPECT" }, () => {
      showToast("⏹️ Đã tắt chọn đối tượng!");
    });
  });

  document.getElementById("btn-enable-redactions")?.addEventListener("click", () => {
    if (!isRedactionsPaused) {
      showToast("🙈 Che đối tượng đang bật rồi!");
      return;
    }
    isRedactionsPaused = false;
    updateRedactionVisibilityUI();
    sendTabMessage({ action: "TOGGLE_REDACTIONS_PAUSE", paused: false }, () => {
      showToast("🙈 Đã bật lại che đối tượng!");
    });
  });

  document.getElementById("btn-disable-redactions")?.addEventListener("click", () => {
    if (isRedactionsPaused) {
      showToast("👁️ Đang ở chế độ xem trang gốc rồi!");
      return;
    }
    isRedactionsPaused = true;
    updateRedactionVisibilityUI();
    sendTabMessage({ action: "TOGGLE_REDACTIONS_PAUSE", paused: true }, () => {
      showToast("👁️ Đã tắt che (Đang xem trang gốc)");
    });
  });

  document.querySelectorAll('input[name="redact-style"]').forEach(r => {
    r.addEventListener("change", (e) => {
      currentRedactStyle = e.target.value;
      const sliderBox = document.getElementById("blur-slider-box");
      sliderBox.style.display = currentRedactStyle === "blur" ? "block" : "none";
      sendTabMessage({
        action: "SET_REDACT_STYLE",
        style: currentRedactStyle,
        blurPx: currentBlurPx,
        applyToLast: true
      });
    });
  });

  const blurSlider = document.getElementById("blur-slider");
  blurSlider?.addEventListener("input", (e) => {
    currentBlurPx = parseInt(e.target.value, 10);
    const bvt = document.getElementById("blur-val-text");
    if (bvt) bvt.textContent = `${currentBlurPx}px`;
    sendTabMessage({
      action: "SET_REDACT_STYLE",
      style: currentRedactStyle,
      blurPx: currentBlurPx
    });
  });

  document.getElementById("btn-apply-all-style")?.addEventListener("click", () => {
    sendTabMessage({
      action: "APPLY_STYLE_TO_ALL",
      style: currentRedactStyle,
      blurPx: currentBlurPx
    }, (res) => {
      if (res && res.list) renderRedactedList(res.list);
      showToast("✓ Đã đổi tất cả phần tử sang kiểu mới!");
    });
  });

  document.getElementById("btn-undo-redact")?.addEventListener("click", () => {
    sendTabMessage({ action: "UNDO_REDACT" }, (res) => {
      if (res) {
        const rc = document.getElementById("redact-count");
        if (rc) rc.textContent = res.count || 0;
        renderRedactedList(res.list || []);
      }
    });
  });

  document.getElementById("btn-clear-redact")?.addEventListener("click", () => {
    if (confirm("Khôi phục lại trang gốc và xóa tất cả phần tử đang che?")) {
      sendTabMessage({ action: "CLEAR_ALL_REDACT" }, () => {
        const rc = document.getElementById("redact-count");
        if (rc) rc.textContent = 0;
        isRedactionsPaused = false;
        updateRedactionVisibilityUI();
        renderRedactedList([]);
        showToast("✓ Đã khôi phục trang gốc!");
      });
    }
  });

  // ESC key to cancel inspect mode or element capture when focused in sidebar
  window.addEventListener("keydown", (e) => {
    if (e.key === "Escape") {
      if (isInspectMode) {
        isInspectMode = false;
        updateInspectButtonsUI();
        sendTabMessage({ action: "STOP_INSPECT" });
        showToast("⏹️ Đã tắt chế độ chọn che!");
      }
      if (isElementCapturePicking) {
        isElementCapturePicking = false;
        const banner = document.getElementById("element-cap-active-banner");
        if (banner) banner.style.display = "none";
        sendTabMessage({ action: "STOP_ELEMENT_CAPTURE" });
        showToast("⏹️ Đã hủy chọn chụp bảng!");
      }
      const modal = document.getElementById("biblio-modal");
      if (modal && modal.style.display === "block") {
        modal.style.display = "none";
      }
      const trustM = document.getElementById("trust-modal");
      if (trustM && trustM.style.display === "block") {
        trustM.style.display = "none";
      }
      const authorM = document.getElementById("author-rules-modal");
      if (authorM && authorM.style.display === "block") {
        authorM.style.display = "none";
      }
    }
  });

  // Tab 3: Element Capture Controls
  document.getElementById("btn-cap-element")?.addEventListener("click", async () => {
    const tab = await ensureActiveTab();
    if (!tab || !tab.id) return showToast("❌ Không tìm thấy tab hoạt động!");
    await ensureContentScriptInjected(tab.id);
    isElementCapturePicking = true;
    const banner = document.getElementById("element-cap-active-banner");
    if (banner) banner.style.display = "block";
    showToast("🎯 Hãy rê chuột và click vào bảng hoặc thẻ cần chụp!");
    sendTabMessage({ action: "START_ELEMENT_CAPTURE" });
  });

  document.getElementById("btn-cancel-cap-element")?.addEventListener("click", () => {
    isElementCapturePicking = false;
    const banner = document.getElementById("element-cap-active-banner");
    if (banner) banner.style.display = "none";
    sendTabMessage({ action: "STOP_ELEMENT_CAPTURE" });
    showToast("⏹️ Đã hủy chọn đối tượng!");
  });

  // Tab 3: Standard Screenshot Controls
  document.getElementById("btn-cap-visible")?.addEventListener("click", captureVisibleScreen);
  document.getElementById("btn-cap-fullpage")?.addEventListener("click", captureFullPageSmart);

  document.getElementById("btn-copy-screenshot")?.addEventListener("click", async () => {
    if (!lastCapturedDataUrl) return;
    try {
      const res = await fetch(lastCapturedDataUrl);
      const blob = await res.blob();
      await navigator.clipboard.write([new ClipboardItem({ [blob.type]: blob })]);
      showToast("✔ Đã copy ảnh vào Clipboard!");
    } catch (e) {
      showToast("err_009", "error");
    }
  });

  document.getElementById("btn-download-screenshot")?.addEventListener("click", () => {
    if (!lastCapturedDataUrl) return;
    const isJpeg = screenshotSettings.format === "jpeg";
    const ext = isJpeg ? "jpg" : "png";
    const cleanTitle = (currentMeta.title || "screenshot")
      .replace(/[^\w\s\u00C0-\u024F\u1E00-\u1EFF]/g, "")
      .trim()
      .replace(/\s+/g, "_")
      .slice(0, 32);
    const a = document.createElement("a");
    a.href = lastCapturedDataUrl;
    a.download = `screenshot_${cleanTitle || "capture"}_${Date.now()}.${ext}`;
    a.click();
  });

  // Tab 3: Screenshot Settings Auto-Save
  document.getElementById("cap-pref-autocopy")?.addEventListener("change", saveScreenshotSettings);
  document.getElementById("cap-pref-format")?.addEventListener("change", saveScreenshotSettings);
  document.getElementById("cap-pref-delay")?.addEventListener("change", saveScreenshotSettings);

  // Tab 3: Screen & Tab Video Recording Controls
  document.getElementById("btn-start-record")?.addEventListener("click", startVideoRecording);
  document.getElementById("btn-stop-record")?.addEventListener("click", stopVideoRecording);
  document.getElementById("btn-cancel-record")?.addEventListener("click", cancelVideoRecording);
  document.getElementById("btn-download-video")?.addEventListener("click", downloadRecordedVideo);
  document.getElementById("btn-discard-video")?.addEventListener("click", discardRecordedVideo);

  // Video Settings Auto-Save
  document.getElementById("video-pref-audio")?.addEventListener("change", saveVideoSettings);
  document.getElementById("video-pref-autodownload")?.addEventListener("change", saveVideoSettings);
  document.getElementById("video-pref-resolution")?.addEventListener("change", saveVideoSettings);
  document.getElementById("video-pref-fps")?.addEventListener("change", saveVideoSettings);
  document.getElementById("video-pref-countdown")?.addEventListener("change", saveVideoSettings);

  document.getElementById("btn-cancel-countdown")?.addEventListener("click", cancelVideoCountdown);

  // Dual-Web Linked Tabs Controls & Shortcut
  
  // Restored Prompter Events
  
  // Restored Script Text Event
  let videoScriptTimer = null;
  document.getElementById("video-script-text")?.addEventListener("input", () => {
    clearTimeout(videoScriptTimer);
    videoScriptTimer = setTimeout(saveVideoSettings, 500);
  });

document.getElementById("btn-save-prompter")?.addEventListener("click", () => {
    saveVideoSettings();
    showToast("✅ Đã lưu kịch bản!", "success");
  });

  document.getElementById("btn-popout-prompter")?.addEventListener("click", () => {
    saveVideoSettings();
    setTimeout(() => {
      const wApi = (typeof browser !== "undefined" && browser.windows) ? browser.windows : (typeof chrome !== "undefined" ? chrome.windows : null);
      if (wApi) {
        wApi.create({
          url: (typeof browser !== "undefined" ? browser.runtime.getURL("OS/html/prompter.html") : chrome.runtime.getURL("OS/html/prompter.html")),
          type: "popup",
          width: 380,
          height: 480
        });
      }
    }, 400);
  });

document.getElementById("btn-quick-swap-tabs")?.addEventListener("click", swapDualTabs);
  document.getElementById("btn-swap-arrow")?.addEventListener("click", swapDualTabs);
  document.getElementById("pill-tab-b")?.addEventListener("click", swapDualTabs);
  document.getElementById("btn-toggle-tab-picker")?.addEventListener("click", toggleDualTabDropdown);
  document.getElementById("select-linked-tab")?.addEventListener("change", async (e) => {
    const selectedTabId = parseInt(e.target.value, 10);
    if (!selectedTabId) return;
    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
    if (tabsApi) {
      try {
        const tab = await tabsApi.get(selectedTabId);
        if (tab) {
          linkedTabObj = tab;
          updateDualTabsUI();
          toggleDualTabDropdown();
          showToast("toast_tab_linked", "success", [(tab.title || "Tab").slice(0, 24)]);
        }
      } catch (err) {}
    }
  });

  // Global Alt+Q inside sidebar
  window.addEventListener("keydown", (e) => {
    if (e.altKey && (e.key === "q" || e.key === "Q")) {
      e.preventDefault();
      swapDualTabs();
    }
  });

  // Listen for updates from content script (Firefox + Chrome compatible)
  const _sidebarRuntimeApi = (typeof browser !== "undefined" && browser.runtime) ? browser.runtime
    : ((typeof chrome !== "undefined" && chrome.runtime) ? chrome.runtime : null);
  if (_sidebarRuntimeApi && _sidebarRuntimeApi.onMessage) {
    _sidebarRuntimeApi.onMessage.addListener((msg) => {
    if (msg.type === "REDACTION_UPDATED") {
      const rc = document.getElementById("redact-count");
      if (rc) rc.textContent = msg.count || 0;
      if (Array.isArray(msg.list)) renderRedactedList(msg.list);
    } else if (msg.type === "INSPECT_MODE_CHANGED") {
      isInspectMode = msg.active;
      updateInspectButtonsUI();
    } else if (msg.type === "REDACTION_PAUSE_CHANGED") {
      isRedactionsPaused = msg.isPaused;
      updateRedactionVisibilityUI();
    } else if (msg.type === "ELEMENT_CAPTURE_CHOSEN") {
      isElementCapturePicking = false;
      const banner = document.getElementById("element-cap-active-banner");
      if (banner) banner.style.display = "none";
      captureChosenElement(msg.info);
    } else if (msg.type === "SNIP_RECT_CHOSEN") {
      isElementCapturePicking = false;
      const banner = document.getElementById("element-cap-active-banner");
      if (banner) banner.style.display = "none";
      captureSnipRect(msg);
    } else if (msg.type === "ELEMENT_CAPTURE_CANCELLED") {
      isElementCapturePicking = false;
      const banner = document.getElementById("element-cap-active-banner");
      if (banner) banner.style.display = "none";
      showToast("Đã dừng chọn đối tượng!");
    } else if (msg.type === "SPA_URL_CHANGED" || msg.type === "PAGE_NAVIGATED") {
      clearTimeout(tabUpdateTimer);
      tabUpdateTimer = setTimeout(() => {
        syncActiveTabData(true);
      }, 350);
    } else if (msg.type === "SWAP_DUAL_TABS_REQUEST") {
      swapDualTabs();
    }
  });
  }

  // Function to sync metadata and redactions for currently active tab
  async function syncActiveTabData(forceReset = false, ignoreDraft = false) {
    const tab = await ensureActiveTab();
    if (!tab || !tab.id) return;

    // Dual-Web Switcher: Track tab transition
    if (currentTabObj && currentTabObj.id !== tab.id) {
      linkedTabObj = currentTabObj;
    }
    currentTabObj = tab;
    updateDualTabsUI();

    const isDifferentUrl = currentTabUrl !== (tab.url || "");
    const wasEmpty = !currentTabUrl || !currentMeta.title;
    currentTabUrl = tab.url || "";

    const prevNotes = (document.getElementById("f-notes")?.value || currentMeta.notes || "").trim();
    const prevTag = (document.getElementById("f-tag")?.value || currentMeta.tag || "").trim();

    if (forceReset || isDifferentUrl || wasEmpty) {
      currentMeta = {
        title: tab.title && tab.title !== "Untitled" ? tab.title : "",
        authors: "",
        year: "",
        date: "",
        journal: "",
        volume: "",
        issue: "",
        pages: "",
        doi: "",
        url: currentTabUrl,
        container: "",
        sourceType: "webpage",
        tag: prevTag,
        notes: prevNotes
      };
      originalExtractedMeta = { ...currentMeta };
      syncInputs();
      updateCitationDisplay();
    }

    if (isPdfUrl(currentTabUrl)) {
      const pdfMeta = await extractPdfMetadataFromUrl(currentTabUrl, tab.title);
      if (pdfMeta) {
        currentMeta = { ...currentMeta, ...pdfMeta };
        originalExtractedMeta = { ...currentMeta };
        // Auto-fetch clean metadata if DOI is found
        const potentialDoi = currentMeta.doi || (currentTabUrl.match(/\b(10\.\d{4,9}\/[-._;()/:A-Za-z0-9]+)\b/i) || [])[1] || "";
        if (potentialDoi) {
           const doiClean = potentialDoi.replace(/[.,;)]+$/, "");
           try {
             const doiRes = await fetch(`https://doi.org/` + encodeURIComponent(doiClean), {
               headers: { "Accept": "application/vnd.citationstyles.csl+json" }
             });
             if (doiRes.ok) {
               const data = await doiRes.json();
               if (data.title) currentMeta.title = data.title;
               const dataAuthors = (data.author || []).map(a => {
                 if (a.name) return normalizeAuthorDisplayName(a.name);
                 if (a.family && a.given) {
                   const lastLow = removeVietnameseDiacritics(a.family).toLowerCase();
                   const isVn = VIETNAMESE_SURNAMES.has(a.family.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastLow);
                   return isVn ? `${a.family} ${a.given}`.trim() : `${a.given} ${a.family}`.trim();
                 }
                 return normalizeAuthorDisplayName(a.family || a.given || "");
               }).filter(Boolean).join(", ");
               if (dataAuthors) currentMeta.authors = dataAuthors;
               const year = data.issued?.["date-parts"]?.[0]?.[0] || "";
               const month = data.issued?.["date-parts"]?.[0]?.[1] || "";
               const day = data.issued?.["date-parts"]?.[0]?.[2] || "";
               let date = year ? String(year) : "";
               if (year && month) date += `-${String(month).padStart(2, "0")}` + (day ? `-${String(day).padStart(2, "0")}` : "");
               if (date) currentMeta.date = date;
               const container = data["container-title"] || data.publisher;
               if (container) currentMeta.container = container;
               if (data.page) currentMeta.pages = `pp. ${data.page}`;
               currentMeta.doi = doiClean;
               if (data.URL) currentMeta.url = data.URL;
               currentMeta.sourceType = "academic";
             }
             
             // OpenAlex for cited_by_count
             const oaRes = await fetch(`https://api.openalex.org/works/https://doi.org/` + encodeURIComponent(doiClean));
             if (oaRes.ok) {
                 const oaData = await oaRes.json();
                 if (typeof oaData.cited_by_count === 'number') {
                     currentMeta.cited_by_count = oaData.cited_by_count; updateCitationDisplay(); updateSourceBadges(currentMeta.sourceType, currentMeta.container);
                 }
             }
           } catch (e) {
             console.warn("Auto DOI/OpenAlex fetch failed:", e);
           }
        }
        
        // Also Auto-fetch for arXiv URL
        const potentialArxiv = (currentTabUrl.match(/arxiv\.org\/(?:pdf|abs)\/(\d{4}\.\d{4,5}(?:v\d+)?)/i) || [])[1] || "";
        if (potentialArxiv) {
           try {
             const axRes = await fetch(`https://export.arxiv.org/api/query?id_list=` + encodeURIComponent(potentialArxiv));
             if (axRes.ok) {
               const xmlText = await axRes.text();
               const parser = new DOMParser();
               const xmlDoc = parser.parseFromString(xmlText, "text/xml");
               const entry = xmlDoc.querySelector("entry");
               if (entry) {
                 const title = entry.querySelector("title")?.textContent?.replace(/\s+/g, " ").trim();
                 if (title) currentMeta.title = title;
                 const authors = Array.from(entry.querySelectorAll("author name")).map(n => normalizeAuthorDisplayName(n.textContent.trim())).filter(Boolean).join(", ");
                 if (authors) currentMeta.authors = authors;
                 const published = entry.querySelector("published")?.textContent || "";
                 if (published) currentMeta.date = published.slice(0, 10);
                 currentMeta.container = "arXiv preprint";
                 currentMeta.pages = `Rep. arXiv:${potentialArxiv}`;
                 currentMeta.doi = `arXiv:${potentialArxiv}`;
                 currentMeta.url = `https://arxiv.org/abs/${potentialArxiv}`;
                 currentMeta.sourceType = "academic";
               }
             }
           } catch (e) {
             console.warn("Auto arXiv fetch failed:", e);
           }
        }
        
        // Preserve existing user notes and tags
        const userNotes = document.getElementById("f-notes")?.value || currentMeta.notes;
        if (userNotes) currentMeta.notes = userNotes;
        const userTag = document.getElementById("f-tag")?.value || currentMeta.tag;
        if (userTag) currentMeta.tag = userTag;

        originalExtractedMeta = { ...currentMeta };

        if (!ignoreDraft) {
          checkDraft(originalExtractedMeta || currentMeta);
        }
        syncInputs();
        updateCitationDisplay();
      }
    } else {
      const extracted = await sendTabMessage({ action: "EXTRACT_PAGE_METADATA" });
      if (extracted && (extracted.title || extracted.authors || extracted.date || extracted.container || extracted.doi)) {
        currentMeta = { ...currentMeta, ...extracted };
        if (currentMeta.authors) {
          currentMeta.authors = normalizeAuthorsString(currentMeta.authors);
        }
        if (!currentMeta.title && tab.title) {
          currentMeta.title = tab.title;
        }
        originalExtractedMeta = { ...currentMeta };
      } else if (!currentMeta.title && tab.title) {
        currentMeta.title = tab.title;
        currentMeta.url = tab.url || currentTabUrl;
        originalExtractedMeta = { ...currentMeta };
      }

      // 1. Clean site brand prefixes from title (e.g. "Frontiers | ...", "Nature | ...")
      if (currentMeta.title) {
        currentMeta.title = currentMeta.title.replace(/^(?:Frontiers|Nature|Science|Springer|Elsevier|Wiley|PLOS|ACM|IEEE)\s*\|\s*/i, "").trim();
      }

      // 2. Auto-detect DOI from URL if not yet extracted
      if (!currentMeta.doi && currentTabUrl) {
        const urlDoiMatch = currentTabUrl.match(/\b(10\.\d{4,9}\/[-._;()/:A-Za-z0-9]+)\b/);
        if (urlDoiMatch) {
          currentMeta.doi = urlDoiMatch[1].replace(/[\/#?]+$/, "");
        }
      }

      // 3. Auto CrossRef enrichment for Academic web articles with DOI
      if (currentMeta.doi) {
        const isAcademicSite = /frontiersin\.org|nature\.com|sciencedirect\.com|springer\.com|wiley\.com|ieee\.org|acm\.org|biorxiv\.org|medrxiv\.org|plos\.org|cell\.com|pnas\.org|tandfonline\.com|sagepub\.com|oup\.com/i.test(currentTabUrl || "");
        if (!currentMeta.authors || !currentMeta.container || !currentMeta.date || currentMeta.sourceType === "academic" || isAcademicSite) {
          try {
            const cleanDoi = currentMeta.doi.trim().replace(/^https?:\/\/doi\.org\//, "");
            const crRes = await fetch(`https://api.crossref.org/works/${encodeURIComponent(cleanDoi)}`, {
              headers: { "User-Agent": "ScholarFlow/2.4 (mailto:contact@scholarflow.org)" }
            });
            if (crRes.ok) {
              const crData = await crRes.json();
              const msg = crData.message;
              if (msg) {
                if (msg.title && msg.title[0]) {
                  currentMeta.title = msg.title[0];
                }
                if (msg["container-title"] && msg["container-title"][0]) {
                  currentMeta.container = msg["container-title"][0];
                }
                if (msg.author && Array.isArray(msg.author) && msg.author.length > 0) {
                  currentMeta.authors = msg.author.map(a => {
                    if (a.name) return normalizeAuthorDisplayName(a.name);
                    if (a.family && a.given) {
                      const lastLow = removeVietnameseDiacritics(a.family).toLowerCase();
                      const isVn = VIETNAMESE_SURNAMES.has(a.family.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastLow);
                      return isVn ? `${a.family} ${a.given}`.trim() : `${a.given} ${a.family}`.trim();
                    }
                    return normalizeAuthorDisplayName(a.family || a.given || "");
                  }).filter(Boolean).join(", ");
                }
                const dateObj = (msg.issued && msg.issued["date-parts"] && msg.issued["date-parts"][0])
                  || (msg["published-print"] && msg["published-print"]["date-parts"] && msg["published-print"]["date-parts"][0])
                  || (msg["published-online"] && msg["published-online"]["date-parts"] && msg["published-online"]["date-parts"][0])
                  || (msg["published"] && msg["published"]["date-parts"] && msg["published"]["date-parts"][0])
                  || (msg.created && msg.created["date-parts"] && msg.created["date-parts"][0]);
                if (dateObj) {
                  if (dateObj.length === 1) currentMeta.date = `${dateObj[0]}`;
                  else if (dateObj.length === 2) currentMeta.date = `${dateObj[0]}-${String(dateObj[1]).padStart(2, "0")}`;
                  else if (dateObj.length >= 3) currentMeta.date = `${dateObj[0]}-${String(dateObj[1]).padStart(2, "0")}-${String(dateObj[2]).padStart(2, "0")}`;
                }
                let pList = [];
                if (msg.volume) pList.push(`vol. ${msg.volume}`);
                if (msg.issue) pList.push(`no. ${msg.issue}`);
                if (msg.page) pList.push(`pp. ${msg.page}`);
                if (pList.length > 0) currentMeta.pages = pList.join(", ");
                currentMeta.sourceType = "academic";
                originalExtractedMeta = { ...currentMeta };
              }
            }
          } catch (e) {
            console.warn("Auto CrossRef fetch failed:", e);
          }
        }
      }

      // OpenAlex API Integration: Metrics badge (cited_by_count) and metadata synchronization
      if (currentMeta.doi) {
        try {
          const cleanDoi = currentMeta.doi.trim().replace(/^https?:\/\/doi\.org\//, "");
          const oaRes = await fetch(`https://api.openalex.org/works/https://doi.org/` + encodeURIComponent(cleanDoi));
          if (oaRes.ok) {
            const oaData = await oaRes.json();
            if (typeof oaData.cited_by_count === "number") {
              currentMeta.cited_by_count = oaData.cited_by_count;
            }
            if (!currentMeta.title || currentMeta.title === "Untitled") {
              if (oaData.title) currentMeta.title = oaData.title;
            }
            if (!currentMeta.authors && oaData.authorships && Array.isArray(oaData.authorships)) {
              const oaAuthors = oaData.authorships.map(a => normalizeAuthorDisplayName(a.author?.display_name)).filter(Boolean).join(", ");
              if (oaAuthors) currentMeta.authors = oaAuthors;
            }
            if (!currentMeta.date) {
              if (oaData.publication_date) currentMeta.date = oaData.publication_date;
              else if (oaData.publication_year) currentMeta.date = String(oaData.publication_year);
            }
            if (!currentMeta.container && oaData.primary_location?.source?.display_name) {
              currentMeta.container = oaData.primary_location.source.display_name;
            }
            if (!currentMeta.pages && oaData.biblio) {
              let p = [];
              if (oaData.biblio.volume) p.push(`vol. ${oaData.biblio.volume}`);
              if (oaData.biblio.issue) p.push(`no. ${oaData.biblio.issue}`);
              if (oaData.biblio.first_page) {
                if (oaData.biblio.last_page) p.push(`pp. ${oaData.biblio.first_page}-${oaData.biblio.last_page}`);
                else p.push(`p. ${oaData.biblio.first_page}`);
              }
              if (p.length > 0) currentMeta.pages = p.join(", ");
            }
            currentMeta.sourceType = "academic";
            originalExtractedMeta = { ...currentMeta };
            updateSourceBadges(currentMeta.sourceType, currentMeta.container);
          }
        } catch (e) {
          console.warn("Auto OpenAlex fetch for webpage failed:", e);
        }
      }

      // 4. Preserve existing user notes and tags
      const userNotes = document.getElementById("f-notes")?.value || currentMeta.notes;
      if (userNotes) currentMeta.notes = userNotes;
      const userTag = document.getElementById("f-tag")?.value || currentMeta.tag;
      if (userTag) currentMeta.tag = userTag;

      // Secondary fallback for YouTube: SPA navigation leaves stale DOM. Fetch HTML directly for accurate date/author.
      if (currentTabUrl && (currentTabUrl.includes("youtube.com/watch") || currentTabUrl.includes("youtu.be/"))) {
        try {
          const ytHtmlRes = await fetch(currentTabUrl);
          if (ytHtmlRes.ok) {
            const htmlText = await ytHtmlRes.text();
            
            // Extract Date
            const mDate = htmlText.match(/meta itemprop="startDate" content="([^"]+)"/) || htmlText.match(/meta itemprop="datePublished" content="([^"]+)"/) || htmlText.match(/meta itemprop="uploadDate" content="([^"]+)"/);
            if (mDate && mDate[1]) {
              let rawDate = mDate[1];
              let parsedDate = "";
              if (rawDate.includes("T")) {
                const d = new Date(rawDate);
                if (!isNaN(d.getTime())) {
                  parsedDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
                }
              }
              if (!parsedDate || parsedDate.length < 4) {
                const p = rawDate.split("T")[0];
                if (p.length >= 4) parsedDate = p;
              }
              if (parsedDate) currentMeta.date = parsedDate; // FORCE OVERWRITE
            }
            
            // Extract Author
            const mAuth = htmlText.match(/<link itemprop="name" content="([^"]+)">/) || htmlText.match(/"author"\s*:\s*"([^"]+)"/);
            if (mAuth && mAuth[1]) {
              currentMeta.authors = mAuth[1]; // FORCE OVERWRITE
            }

            // Extract Title
            const mTitle = htmlText.match(/meta name="title" content="([^"]+)"/);
            if (mTitle && mTitle[1]) {
              currentMeta.title = mTitle[1]; // FORCE OVERWRITE
            }
            
            originalExtractedMeta = { ...currentMeta };
          }
        } catch (e) {
          console.warn("YouTube direct fetch fallback failed:", e);
        }
      }

      if (!ignoreDraft) {
        checkDraft(originalExtractedMeta || currentMeta);
      }
      syncInputs();
      updateCitationDisplay();
    }

    const status = await sendTabMessage({ action: "GET_REDACT_STATUS" });
    if (status) {
      const rCount = document.getElementById("redact-count");
      if (rCount) rCount.textContent = status.count || 0;
      isInspectMode = status.isInspectMode || false;
      isRedactionsPaused = status.isRedactionsPaused || false;
      updateInspectButtonsUI();
      updateRedactionVisibilityUI();
      renderRedactedList(status.list || []);
    }
  }

  // Auto-sync when switching tabs or refreshing page (critical for persistent Firefox sidebar & YouTube SPA navigation)
  let tabUpdateTimer = null;
  const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
  if (tabsApi?.onActivated) {
    tabsApi.onActivated.addListener((activeInfo) => {
      activeTabId = activeInfo.tabId;
      syncActiveTabData(true);
    });
  }
  if (tabsApi?.onUpdated) {
    tabsApi.onUpdated.addListener((tabId, changeInfo) => {
      if (tabId === activeTabId && (changeInfo.status === "complete" || changeInfo.url || changeInfo.title)) {
        clearTimeout(tabUpdateTimer);
        tabUpdateTimer = setTimeout(() => {
          syncActiveTabData(true);
        }, 400);
      }
    });
  }
  const windowsApi = (typeof browser !== "undefined" && browser.windows) ? browser.windows : (typeof chrome !== "undefined" ? chrome.windows : null);
  if (windowsApi?.onFocusChanged) {
    windowsApi.onFocusChanged.addListener((windowId) => {
      if (windowId !== windowsApi.WINDOW_ID_NONE) {
        clearTimeout(tabUpdateTimer);
        tabUpdateTimer = setTimeout(() => {
          syncActiveTabData(true);
        }, 300);
      }
    });
  }

  // Detect if running inside a Popup window
  if (window.location.pathname.endsWith("popup.html") || window.location.search.includes("view=popup")) {
    document.body.classList.add("is-popup");
  }

  // Listen for language switch event
  window.addEventListener("app-language-changed", (e) => {
    syncCustomSelects();
    updateCitationDisplay();
    if (currentMeta) {
      updateSourceBadges(currentMeta.sourceType, currentMeta.container);
    }
    if (verifiedResultData) {
      renderVerifyResult(verifiedResultData, document.getElementById("verify-input")?.value || "");
    }
    updateInspectButtonsUI();
    updateRedactionVisibilityUI();
    renderBiblioModalList();
    updateDualTabsUI();
    populateDualTabDropdown();
    if (typeof renderAutofillList === "function") renderAutofillList();
    if (typeof renderTodoList === "function") renderTodoList();

    // Notify active content script about the language update
    const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
    if (tabsApi && activeTabId) {
      try {
        const p = tabsApi.sendMessage(activeTabId, { action: "SET_LANGUAGE", lang: e.detail?.lang });
        if (p && typeof p.catch === "function") {
          p.catch(() => {});
        }
      } catch (err) {}
    }

    const toastMsg = window.i18n ? window.i18n.t("toast_lang_changed") : null;
    if (toastMsg) {
      showToast(toastMsg);
    }
  });

  
  const verEl = document.getElementById("app-version-display");
  if (verEl && typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.getManifest) {
    const m = chrome.runtime.getManifest();
    if (m && m.version) verEl.textContent = "v" + m.version;
  }
  // Initial Sync
  try { updateInspectButtonsUI(); } catch (e) { console.warn(e); }
  try { updateRedactionVisibilityUI(); } catch (e) { console.warn(e); }
  try { initCustomSelects(); } catch (e) { console.warn(e); }
  try { loadCitationSettings(); } catch (e) { console.warn(e); }
  try { initSourceVerifier(); } catch (e) { console.warn(e); }
  try { loadSavedBibliographies(); } catch (e) { console.warn(e); }
  try { loadScreenshotSettings(); } catch (e) { console.warn(e); }
  try { loadVideoSettings(); } catch (e) { console.warn(e); }
  try { syncActiveTabData(true); } catch (e) { console.warn(e); }
});

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "QUOTE_TO_CITE" && request.selectionText) {
    const text = request.selectionText;
    const fNotes = document.getElementById("f-notes");
    if (fNotes) {
      if (fNotes.value) fNotes.value += " | " + text;
      else fNotes.value = `"${text}"`;
      currentMeta.notes = fNotes.value;
      updateNotesClearButton();
      updateCitationDisplay();
      saveDraft();
    }
    showToast("✅ Đã chèn trích đoạn vào mục Ghi chú!");
    
    // Switch to tab 1
    const tCite = document.querySelector('[data-target="tab-cite"]');
    if (tCite) tCite.click();
  }
});
  const navWrapper = document.getElementById("nav-wrapper");
  const navScrollLeft = document.getElementById("nav-scroll-left");
  const navScrollRight = document.getElementById("nav-scroll-right");

  if (navWrapper && navScrollLeft && navScrollRight) {
    function updateNavScrollButtons() {
      if (navWrapper.scrollLeft > 4) {
        navScrollLeft.classList.remove("is-hidden");
      } else {
        navScrollLeft.classList.add("is-hidden");
      }
      
      if (navWrapper.scrollLeft < navWrapper.scrollWidth - navWrapper.clientWidth - 4) {
        navScrollRight.classList.remove("is-hidden");
      } else {
        navScrollRight.classList.add("is-hidden");
      }
    }

    navScrollLeft.addEventListener("click", () => {
      navWrapper.scrollBy({ left: -100, behavior: "smooth" });
    });

    navScrollRight.addEventListener("click", () => {
      navWrapper.scrollBy({ left: 100, behavior: "smooth" });
    });

    navWrapper.addEventListener("scroll", updateNavScrollButtons);
    // Initial check
    setTimeout(updateNavScrollButtons, 100);
  }
  /* -------------------------------------------------------------
     TAB AUTOFILL
  ------------------------------------------------------------- */
  let savedAutofill = [];

  function renderAutofillList() {
    const list = document.getElementById("autofill-list");
    if (!list) return;
    list.textContent = "";
    const delText = (window.i18n ? window.i18n.t("btn_delete") : null) || "Xóa";
    const copyText = (window.i18n ? window.i18n.t("btn_copy") : null) || "Sao chép";

    savedAutofill.forEach((item, index) => {
      const div = document.createElement("div");
      div.className = "feature-card";
      div.style.display = "flex";
      div.style.flexDirection = "column";
      div.style.gap = "6px";
      div.style.padding = "8px";
      div.style.position = "relative";
      const autofillName = document.createElement("div");
      autofillName.style.fontWeight = "700";
      autofillName.style.color = "var(--primary)";
      autofillName.style.fontSize = "12px";
      autofillName.textContent = item.name;

      const autofillValue = document.createElement("div");
      autofillValue.style.fontFamily = "ui-monospace, monospace";
      autofillValue.style.fontSize = "11px";
      autofillValue.style.background = "rgba(0,0,0,0.2)";
      autofillValue.style.padding = "4px";
      autofillValue.style.borderRadius = "4px";
      autofillValue.style.whiteSpace = "pre-wrap";
      autofillValue.style.wordBreak = "break-all";
      autofillValue.textContent = item.value;

      const delAutofillBtn = document.createElement("button");
      delAutofillBtn.className = "btn-text-small btn-del-autofill";
      delAutofillBtn.setAttribute("data-index", index);
      delAutofillBtn.style.position = "absolute";
      delAutofillBtn.style.top = "8px";
      delAutofillBtn.style.right = "8px";
      delAutofillBtn.style.color = "#f87171";
      delAutofillBtn.textContent = delText;

      const copyAutofillBtn = document.createElement("button");
      copyAutofillBtn.className = "btn btn-secondary btn-copy-autofill";
      copyAutofillBtn.setAttribute("data-index", index);
      copyAutofillBtn.style.padding = "4px 8px";
      copyAutofillBtn.style.marginTop = "4px";
      copyAutofillBtn.style.display = "inline-flex";
      copyAutofillBtn.style.alignItems = "center";
      copyAutofillBtn.style.justifyContent = "center";
      copyAutofillBtn.style.gap = "4px";
      const autofillCopyIcon = document.createElement("span");
      autofillCopyIcon.innerHTML = '<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>';
      copyAutofillBtn.appendChild(autofillCopyIcon);
      const autofillCopyLabel = document.createElement("span");
      autofillCopyLabel.textContent = copyText;
      copyAutofillBtn.appendChild(autofillCopyLabel);

      div.appendChild(autofillName);
      div.appendChild(autofillValue);
      div.appendChild(delAutofillBtn);
      div.appendChild(copyAutofillBtn);
      list.appendChild(div);
    });

    list.querySelectorAll('.btn-del-autofill').forEach(btn => {
      btn.addEventListener("click", (e) => {
        const idx = parseInt(e.target.getAttribute("data-index"), 10);
        savedAutofill.splice(idx, 1);
        storSet({ "sf_autofill": savedAutofill });
        renderAutofillList();
      });
    });

    list.querySelectorAll('.btn-copy-autofill').forEach(btn => {
      btn.addEventListener("click", (e) => {
        const idx = parseInt(e.target.getAttribute("data-index"), 10);
        const text = savedAutofill[idx].value;
        navigator.clipboard.writeText(text).then(() => {
          const toastCopied = (window.i18n ? window.i18n.t("autofill_toast_copied", null, { name: savedAutofill[idx].name }) : null) || `✓ Đã sao chép: ${savedAutofill[idx].name}`;
          showToast(toastCopied);
        });
      });
    });
  }

  const btnAddAutofill = document.getElementById("btn-autofill-add");
  if (btnAddAutofill) {
    btnAddAutofill.addEventListener("click", () => {
      const nameInput = document.getElementById("autofill-name");
      const valInput = document.getElementById("autofill-value");
      const name = (nameInput.value || "").trim();
      const value = (valInput.value || "").trim();
      if (!name || !value) {
        const warnMsg = (window.i18n ? window.i18n.t("autofill_toast_required") : null) || "Vui lòng nhập đủ tên và giá trị!";
        showToast(warnMsg, "warning");
        return;
      }
      savedAutofill.push({ name, value });
      storSet({ "sf_autofill": savedAutofill });
      nameInput.value = "";
      valInput.value = "";
      renderAutofillList();
      const addedMsg = (window.i18n ? window.i18n.t("autofill_toast_added") : null) || "Đã thêm trường Autofill mới!";
      showToast(addedMsg);
    });
  }

  storGet("sf_autofill", (res) => {
    if (res && res.sf_autofill) savedAutofill = res.sf_autofill;
    renderAutofillList();
  });

  /* -------------------------------------------------------------
     TAB TODO
  ------------------------------------------------------------- */
  let savedTodos = [];
  let currentTodoFilter = "all";
  let editingTodoIndex = -1;

  function updateTodoStats() {
    const total = savedTodos.length;
    const done = savedTodos.filter(t => t.done).length;
    const percent = total > 0 ? Math.round((done / total) * 100) : 0;

    const badgeStats = document.getElementById("todo-badge-stats");
    if (badgeStats) {
      badgeStats.textContent = `${done}/${total}`;
      const progressTooltip = (window.i18n ? window.i18n.t("todo_progress", null, { done, total, percent }) : null) || `Đã xong: ${done}/${total} việc (${percent}%)`;
      badgeStats.setAttribute("title", progressTooltip);
    }

    const progressBar = document.getElementById("todo-progress-bar");
    if (progressBar) {
      progressBar.style.width = `${percent}%`;
    }
  }

  function renderTodoList() {
    const list = document.getElementById("todo-list");
    if (!list) return;
    list.textContent = "";

    updateTodoStats();

    const editText = (window.i18n ? window.i18n.t("todo_btn_edit") : null) || "Sửa";
    const delText = (window.i18n ? window.i18n.t("btn_delete") : null) || "Xóa";
    const saveText = (window.i18n ? window.i18n.t("todo_btn_save") : null) || "Lưu";
    const cancelText = (window.i18n ? window.i18n.t("todo_btn_cancel") : null) || "Hủy";
    const urgentText = (window.i18n ? window.i18n.t("todo_priority_urgent") : null) || "🔴 Gấp";
    const normalText = (window.i18n ? window.i18n.t("todo_priority_normal") : null) || "🟡 Vừa";
    const lowText = (window.i18n ? window.i18n.t("todo_priority_low") : null) || "🟢 Thấp";
    const emptyText = (window.i18n ? window.i18n.t("todo_empty_list") : null) || "Chưa có việc nào trong danh sách. Hãy thêm nhiệm vụ nghiên cứu bên trên!";

    const visibleTodos = savedTodos
      .map((item, originalIndex) => ({ ...item, originalIndex }))
      .filter(item => {
        if (currentTodoFilter === "active") return !item.done;
        if (currentTodoFilter === "done") return item.done;
        return true;
      });

    if (visibleTodos.length === 0) {
      const emptyDiv = document.createElement("div");
      emptyDiv.style.textAlign = "center";
      emptyDiv.style.padding = "24px 14px";
      emptyDiv.style.color = "var(--text-muted)";
      emptyDiv.style.fontSize = "12px";
      emptyDiv.style.lineHeight = "1.5";
      emptyDiv.style.border = "1px dashed rgba(255,255,255,0.12)";
      emptyDiv.style.borderRadius = "8px";
      emptyDiv.style.background = "rgba(15,23,42,0.3)";
      const emptyEmoji = document.createElement("div");
      emptyEmoji.style.fontSize = "18px";
      emptyEmoji.style.marginBottom = "4px";
      emptyEmoji.textContent = "📝";
      const emptyMessage = document.createElement("div");
      emptyMessage.textContent = emptyText;
      emptyDiv.appendChild(emptyEmoji);
      emptyDiv.appendChild(emptyMessage);
      list.appendChild(emptyDiv);
      return;
    }

    visibleTodos.forEach(({ originalIndex, ...item }) => {
      const card = document.createElement("div");
      const isEditing = (editingTodoIndex === originalIndex);
      const priorityClass = `priority-${item.priority || 'normal'}`;
      card.className = `todo-card ${priorityClass} ${item.done ? "is-done" : ""}`;
      card.dataset.index = originalIndex;

      if (isEditing) {
        const wrap = document.createElement("div");
        wrap.className = "todo-edit-wrap";

        const textInput = document.createElement("input");
        textInput.type = "text";
        textInput.className = "form-control todo-edit-text";
        textInput.value = item.text;
        textInput.style.fontSize = "13px";
        textInput.style.padding = "6px 10px";
        textInput.style.width = "100%";
        wrap.appendChild(textInput);

        const editRow = document.createElement("div");
        editRow.style.display = "flex";
        editRow.style.gap = "6px";
        const prioSelect = document.createElement("select");
        prioSelect.className = "form-control todo-edit-priority";
        prioSelect.style.fontSize = "11.5px";
        prioSelect.style.width = "100px";
        prioSelect.style.padding = "4px 6px";
        const mkOption = (val, labelText) => {
          const opt = document.createElement("option");
          opt.value = val;
          opt.textContent = labelText;
          opt.selected = (item.priority === val) || (!item.priority && val === "normal");
          return opt;
        };
        prioSelect.appendChild(mkOption("normal", normalText));
        prioSelect.appendChild(mkOption("urgent", urgentText));
        prioSelect.appendChild(mkOption("low", lowText));

        const detailInput = document.createElement("input");
        detailInput.type = "text";
        detailInput.className = "form-control todo-edit-detail";
        detailInput.placeholder = "Ghi chú chi tiết / link...";
        detailInput.value = item.detail || "";
        detailInput.style.fontSize = "11.5px";
        detailInput.style.flex = "1";
        detailInput.style.padding = "4px 8px";
        editRow.appendChild(prioSelect);
        editRow.appendChild(detailInput);
        wrap.appendChild(editRow);

        const editActions = document.createElement("div");
        editActions.className = "todo-edit-actions";
        const cancelEditBtn = document.createElement("button");
        cancelEditBtn.type = "button";
        cancelEditBtn.className = "btn btn-secondary btn-cancel-edit";
        cancelEditBtn.setAttribute("data-index", originalIndex);
        cancelEditBtn.style.padding = "4px 10px";
        cancelEditBtn.style.fontSize = "11px";
        cancelEditBtn.textContent = cancelText;
        const saveEditBtn = document.createElement("button");
        saveEditBtn.type = "button";
        saveEditBtn.className = "btn btn-primary btn-save-edit";
        saveEditBtn.setAttribute("data-index", originalIndex);
        saveEditBtn.style.padding = "4px 12px";
        saveEditBtn.style.fontSize = "11px";
        saveEditBtn.style.fontWeight = "700";
        saveEditBtn.textContent = saveText;
        editActions.appendChild(cancelEditBtn);
        editActions.appendChild(saveEditBtn);
        wrap.appendChild(editActions);

        card.appendChild(wrap);
      } else {
        let priorityBadgeClass = "todo-priority-normal";
        let priorityLabel = normalText;
        if (item.priority === "urgent") {
          priorityBadgeClass = "todo-priority-urgent";
          priorityLabel = urgentText;
        } else if (item.priority === "low") {
          priorityBadgeClass = "todo-priority-low";
          priorityLabel = lowText;
        }

        const main = document.createElement("div");
        main.className = "todo-card-main";

        const labelCheck = document.createElement("label");
        labelCheck.className = "todo-checkbox-wrap";
        labelCheck.title = item.done ? "Đánh dấu chưa xong" : "Đánh dấu hoàn thành";
        const chk = document.createElement("input");
        chk.type = "checkbox";
        chk.className = "todo-check";
        chk.setAttribute("data-index", originalIndex);
        chk.checked = !!item.done;
        const chkBox = document.createElement("div");
        chkBox.className = "todo-checkbox-box";
        const chkIcon = document.createElement("span");
        chkIcon.innerHTML = '<svg class="todo-check-icon" viewBox="0 0 24 24" width="11" height="11" stroke="#ffffff" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>';
        chkBox.appendChild(chkIcon);
        labelCheck.appendChild(chk);
        labelCheck.appendChild(chkBox);

        const textWrap = document.createElement("div");
        textWrap.className = "todo-text-content";
        const titleEl = document.createElement("div");
        titleEl.className = "todo-title-text";
        titleEl.textContent = item.text;
        const metaRow = document.createElement("div");
        metaRow.className = "todo-meta-row";
        const prioBadge = document.createElement("span");
        prioBadge.className = `todo-priority-badge ${priorityBadgeClass}`;
        prioBadge.textContent = priorityLabel;
        metaRow.appendChild(prioBadge);
        if (item.createdAt) {
          const dateBadge = document.createElement("span");
          dateBadge.className = "todo-date-badge";
          dateBadge.textContent = item.createdAt;
          metaRow.appendChild(dateBadge);
        }
        textWrap.appendChild(titleEl);
        textWrap.appendChild(metaRow);
        if (item.detail) {
          const detailEl = document.createElement("div");
          detailEl.className = "todo-detail-box";
          detailEl.textContent = item.detail;
          textWrap.appendChild(detailEl);
        }

        const cardActions = document.createElement("div");
        cardActions.className = "todo-actions";
        const editActionBtn = document.createElement("button");
        editActionBtn.type = "button";
        editActionBtn.className = "todo-action-btn btn-edit";
        editActionBtn.setAttribute("data-index", originalIndex);
        editActionBtn.title = editText;
        const editActionIcon = document.createElement("span");
        editActionIcon.innerHTML = '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>';
        editActionBtn.appendChild(editActionIcon);
        const delActionBtn = document.createElement("button");
        delActionBtn.type = "button";
        delActionBtn.className = "todo-action-btn btn-del";
        delActionBtn.setAttribute("data-index", originalIndex);
        delActionBtn.title = delText;
        const delActionIcon = document.createElement("span");
        delActionIcon.innerHTML = '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>';
        delActionBtn.appendChild(delActionIcon);
        cardActions.appendChild(editActionBtn);
        cardActions.appendChild(delActionBtn);

        main.appendChild(labelCheck);
        main.appendChild(textWrap);
        main.appendChild(cardActions);
        card.appendChild(main);
      }


      list.appendChild(card);
    });

    list.querySelectorAll('.todo-check').forEach(chk => {
      chk.addEventListener("change", (e) => {
        const idx = parseInt(e.target.getAttribute("data-index"), 10);
        if (savedTodos[idx]) {
          savedTodos[idx].done = e.target.checked;
          storSet({ "sf_todos": savedTodos });
          renderTodoList();
        }
      });
    });

    list.querySelectorAll('.btn-del').forEach(btn => {
      btn.addEventListener("click", (e) => {
        const idx = parseInt(e.currentTarget.getAttribute("data-index"), 10);
        if (!isNaN(idx) && savedTodos[idx]) {
          savedTodos.splice(idx, 1);
          if (editingTodoIndex === idx) editingTodoIndex = -1;
          storSet({ "sf_todos": savedTodos });
          renderTodoList();
        }
      });
    });

    list.querySelectorAll('.btn-edit').forEach(btn => {
      btn.addEventListener("click", (e) => {
        const idx = parseInt(e.currentTarget.getAttribute("data-index"), 10);
        if (!isNaN(idx)) {
          editingTodoIndex = idx;
          renderTodoList();
          const editInput = list.querySelector('.todo-edit-text');
          if (editInput) {
            editInput.focus();
            editInput.select();
          }
        }
      });
    });

    list.querySelectorAll('.btn-save-edit').forEach(btn => {
      btn.addEventListener("click", (e) => {
        const idx = parseInt(e.currentTarget.getAttribute("data-index"), 10);
        const card = e.currentTarget.closest('.todo-card');
        if (card && savedTodos[idx]) {
          const newText = (card.querySelector('.todo-edit-text')?.value || "").trim();
          const newPriority = card.querySelector('.todo-edit-priority')?.value || "normal";
          const newDetail = (card.querySelector('.todo-edit-detail')?.value || "").trim();

          if (!newText) return;

          savedTodos[idx].text = newText;
          savedTodos[idx].priority = newPriority;
          savedTodos[idx].detail = newDetail;
          editingTodoIndex = -1;
          storSet({ "sf_todos": savedTodos });
          showToast("todo_toast_updated");
          renderTodoList();
        }
      });
    });

    list.querySelectorAll('.btn-cancel-edit').forEach(btn => {
      btn.addEventListener("click", () => {
        editingTodoIndex = -1;
renderTodoList();
  });
});

// ----------------------------------------------------------------------------
// Calendar (ICS subscription) module
// ----------------------------------------------------------------------------
  }

  // Filter Buttons
  const filterBtns = document.querySelectorAll('.todo-filter-btn');
  filterBtns.forEach(btn => {
    btn.addEventListener("click", (e) => {
      filterBtns.forEach(b => b.classList.remove("active"));
      e.currentTarget.classList.add("active");
      currentTodoFilter = e.currentTarget.getAttribute("data-filter") || "all";
      renderTodoList();
    });
  });

  // Add Task
  const btnAddTodo = document.getElementById("btn-todo-add");
  const inputTodo = document.getElementById("todo-input");
  const selectPriority = document.getElementById("todo-priority-select");
  const inputDetail = document.getElementById("todo-detail-input");

  if (btnAddTodo && inputTodo) {
    const addTodo = () => {
      const text = (inputTodo.value || "").trim();
      if (!text) {
        inputTodo.focus();
        return;
      }
      const priority = (selectPriority ? selectPriority.value : "normal") || "normal";
      const detail = (inputDetail ? inputDetail.value : "").trim();

      const now = new Date();
      const timeStr = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

      savedTodos.unshift({
        id: Date.now().toString(),
        text: text,
        detail: detail,
        priority: priority,
        done: false,
        createdAt: timeStr
      });

      storSet({ "sf_todos": savedTodos });
      inputTodo.value = "";
      if (inputDetail) inputDetail.value = "";
      if (selectPriority) selectPriority.value = "normal";
      renderTodoList();
    };

    btnAddTodo.addEventListener("click", addTodo);
    inputTodo.addEventListener("keypress", (e) => {
      if (e.key === "Enter") addTodo();
    });
    if (inputDetail) {
      inputDetail.addEventListener("keypress", (e) => {
        if (e.key === "Enter") addTodo();
      });
    }
  }

  // Copy All Tasks
  const btnCopyAll = document.getElementById("btn-todo-copy-all");
  if (btnCopyAll) {
    btnCopyAll.addEventListener("click", () => {
      if (savedTodos.length === 0) return;
      const lines = savedTodos.map(t => {
        const mark = t.done ? "[x]" : "[ ]";
        const pLabel = t.priority === "urgent" ? "(Gấp) " : (t.priority === "low" ? "(Thấp) " : "");
        let line = `${mark} ${pLabel}${t.text}`;
        if (t.detail) line += `\n    └ Ghi chú: ${t.detail}`;
        return line;
      });
      const header = `📋 SCHOLARFLOW TODO LIST (${new Date().toLocaleDateString()}):\n----------------------------------------\n`;
      const fullContent = header + lines.join("\n");
      navigator.clipboard.writeText(fullContent).then(() => {
        showToast("todo_toast_copied");
      }).catch(err => {
        console.error("Copy failed:", err);
      });
    });
  }

  // Export to TXT
  const btnExport = document.getElementById("btn-todo-export");
  if (btnExport) {
    btnExport.addEventListener("click", () => {
      if (savedTodos.length === 0) return;
      const lines = savedTodos.map((t, idx) => {
        const mark = t.done ? "[HOÀN THÀNH]" : "[CHƯA XONG]";
        const pLabel = t.priority === "urgent" ? "[ƯU TIÊN GẤP]" : (t.priority === "low" ? "[ƯU TIÊN THẤP]" : "[BÌNH THƯỜNG]");
        let line = `${idx + 1}. ${mark} ${pLabel} ${t.text}`;
        if (t.createdAt) line += ` (Tạo lúc: ${t.createdAt})`;
        if (t.detail) line += `\n   -> Ghi chú/Tham khảo: ${t.detail}`;
        return line;
      });
      const content = `========================================\n SCHOLARFLOW RESEARCH TASK LIST\n Xuất lúc: ${new Date().toLocaleString()}\n========================================\n\n` + lines.join("\n\n");
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `ScholarFlow_TodoList_${new Date().toISOString().slice(0, 10)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      showToast("todo_toast_exported");
    });
  }

  // Clear Done Tasks
  const btnClearDone = document.getElementById("btn-todo-clear-done");
  if (btnClearDone) {
    btnClearDone.addEventListener("click", () => {
      const doneCount = savedTodos.filter(t => t.done).length;
      if (doneCount === 0) return;
      savedTodos = savedTodos.filter(t => !t.done);
      editingTodoIndex = -1;
      storSet({ "sf_todos": savedTodos });
      const toastMsg = (window.i18n ? window.i18n.t("todo_toast_cleared", null, { count: doneCount }) : null) || `✓ Đã dọn dẹp ${doneCount} việc đã hoàn thành!`;
      showToast(toastMsg);
      renderTodoList();
    });
  }

  storGet("sf_todos", (res) => {
    if (res && res.sf_todos && Array.isArray(res.sf_todos)) {
      savedTodos = res.sf_todos;
    }
renderTodoList();
  });

