// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/redact.js
// Tab 2: element redact & blur controller
// Extracted from js/sidebar.js (lines 3765-3984) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Tab 2: Element Redact & Blur Controller
// ----------------------------------------------------------------------------
function updateInspectButtonsUI() {
  const btnStart = document.getElementById("btn-start-inspect");
  const btnStop = document.getElementById("btn-stop-inspect");
  if (!btnStart || !btnStop) return;

  const tStart = window.i18n ? window.i18n.t("btn_start_inspect") : "Bật chọn che";
  const tStop = window.i18n ? window.i18n.t("btn_stop_inspect") : "Dừng chọn";

  if (isInspectMode) {
    btnStart.textContent = `🎯 ${tStart}...`;
    btnStart.className = "btn btn-danger";
    btnStart.style.opacity = "1";

    btnStop.className = "btn btn-primary";
    btnStop.style.opacity = "1";
    btnStop.style.cursor = "pointer";
    btnStop.textContent = tStop;
  } else {
    btnStart.textContent = `🎯 ${tStart}`;
    btnStart.className = "btn btn-primary";
    btnStart.style.opacity = "1";

    btnStop.className = "btn btn-secondary";
    btnStop.style.opacity = "0.65";
    btnStop.textContent = tStop;
  }
}

function updateRedactionVisibilityUI() {
  const btnEnable = document.getElementById("btn-enable-redactions");
  const btnDisable = document.getElementById("btn-disable-redactions");
  if (!btnEnable || !btnDisable) return;

  const tEnable = window.i18n ? window.i18n.t("btn_enable_redact") : "Bật che";
  const tDisable = window.i18n ? window.i18n.t("btn_disable_redact") : "Xem bản gốc";

  if (isRedactionsPaused) {
    btnEnable.className = "btn btn-secondary";
    btnEnable.style.opacity = "0.75";
    btnEnable.style.boxShadow = "none";
    btnEnable.textContent = `🙈 ${tEnable}`;

    btnDisable.className = "btn btn-warning";
    btnDisable.style.opacity = "1";
    btnDisable.style.boxShadow = "0 0 10px rgba(245, 158, 11, 0.4)";
    btnDisable.textContent = `👁️ ${tDisable} ✓`;
  } else {
    btnEnable.className = "btn btn-success";
    btnEnable.style.opacity = "1";
    btnEnable.style.boxShadow = "0 0 10px rgba(16, 185, 129, 0.4)";
    btnEnable.textContent = `🙈 ${tEnable} ✓`;

    btnDisable.className = "btn btn-secondary";
    btnDisable.style.opacity = "0.75";
    btnDisable.style.boxShadow = "none";
    btnDisable.textContent = `👁️ ${tDisable}`;
  }
}

function appendFormattedText(el, text) {
  const parts = String(text || "").split(/\*([^\*]+)\*/);
  for (let i = 0; i < parts.length; i++) {
    if (!parts[i]) continue;
    const node = document.createElement(i % 2 === 1 ? "i" : "span");
    node.textContent = parts[i];
    el.appendChild(node);
  }
}

function createResearchNoteNode(note, lang) {
  const noteLabel = (window.i18n ? window.i18n.t("lbl_notes") : null) ||
    (lang === "en" ? "Research Notes" : (lang === "zh" ? "研究笔记" : (lang === "ja" ? "研究メモ" : (lang === "ru" ? "Заметки к исследованию" : "Ghi chú nghiên cứu"))));
  let clean = String(note || "").trim();
  while (
    (clean.startsWith('"') && clean.endsWith('"')) ||
    (clean.startsWith('“') && clean.endsWith('”')) ||
    (clean.startsWith('«') && clean.endsWith('»'))
  ) {
    clean = clean.slice(1, -1).trim();
  }
  const wrap = document.createElement("div");
  wrap.style.marginTop = "12px";
  wrap.style.paddingTop = "8px";
  wrap.style.borderTop = "1px dashed rgba(255,255,255,0.15)";
  wrap.style.fontSize = "11px";
  wrap.style.lineHeight = "1.55";
  wrap.style.color = "#94a3b8";
  wrap.style.fontStyle = "italic";
  const label = document.createElement("div");
  label.style.fontStyle = "normal";
  label.style.fontWeight = "600";
  label.style.color = "#cbd5e1";
  label.style.fontSize = "10px";
  label.style.textTransform = "uppercase";
  label.style.letterSpacing = "0.5px";
  label.style.marginBottom = "3px";
  label.textContent = noteLabel + ":";
  wrap.appendChild(label);
  const content = buildNoteMarkdownNode(clean);
  const holder = document.createElement("span");
  holder.style.fontStyle = "italic";
  holder.appendChild(content);
  wrap.appendChild(holder);
  return wrap;
}

function updateNotesClearButton() {
  const btn = document.getElementById("btn-clear-notes");
  const input = document.getElementById("f-notes");
  if (btn && input) btn.style.display = input.value ? "block" : "none";
  notesUpdateCount();
}

function renderRedactedList(list) {
  currentRedactedList = list || [];
  const container = document.getElementById("redacted-items-list");
  if (!container) return;

  container.textContent = "";

  if (!list || list.length === 0) {
    const emptyBox = document.createElement("div");
    emptyBox.className = "empty-list-box";

    const emptyIcon = document.createElement("div");
    emptyIcon.className = "empty-list-icon";
    emptyIcon.textContent = "🛡️";

    const emptyTitle = document.createElement("div");
    emptyTitle.className = "empty-list-title";
    emptyTitle.textContent = window.i18n ? window.i18n.t("lbl_no_redacted") : "Chưa có phần tử nào được che";

    const emptySub = document.createElement("div");
    emptySub.className = "empty-list-sub";
    emptySub.textContent = window.i18n ? window.i18n.t("lbl_no_redacted_sub") : "Bấm \"Bật chọn che\" rồi nhấp vào đối tượng trên trang để bảo mật.";

    emptyBox.appendChild(emptyIcon);
    emptyBox.appendChild(emptyTitle);
    emptyBox.appendChild(emptySub);
    container.appendChild(emptyBox);
    return;
  }

  const styleMap = {
    blur: (px) => `🌫️ Mờ ${px || 12}px`,
    blackout: () => "⬛ Hộp đen",
    pixelate: () => "▦ Điểm ảnh",
    hide: () => "👻 Ẩn"
  };

  list.forEach((item, index) => {
    const card = document.createElement("div");
    card.className = "redacted-item-card";
    card.dataset.id = item.id;
    card.title = window.i18n ? window.i18n.t("Rê chuột để soi vị trí trên trang web, click để cuộn tới") : "Rê chuột để soi vị trí trên trang web, click để cuộn tới";

    const left = document.createElement("div");
    left.className = "redacted-item-left";

    const indexBadge = document.createElement("span");
    indexBadge.className = "redacted-index-badge";
    indexBadge.textContent = `#${index + 1}`;

    const tagPill = document.createElement("span");
    tagPill.className = "redacted-tag-pill";
    tagPill.textContent = `<${item.tagName}>`;

    const stylePill = document.createElement("span");
    stylePill.className = "redacted-style-pill";
    const getStyleLabel = styleMap[item.style] || (() => "Che");
    stylePill.textContent = getStyleLabel(item.blurPx);

    const snippet = document.createElement("span");
    snippet.className = "redacted-snippet-text";
    snippet.textContent = item.snippet || "Phần tử trang";

    left.appendChild(indexBadge);
    left.appendChild(tagPill);
    left.appendChild(stylePill);
    left.appendChild(snippet);

    const btnRemove = document.createElement("button");
    btnRemove.className = "btn-remove-item";
    btnRemove.dataset.id = item.id;
    btnRemove.title = window.i18n ? window.i18n.t("Gỡ bỏ che phần tử này") : "Gỡ bỏ che phần tử này";
    btnRemove.textContent = "✕";

    card.appendChild(left);
    card.appendChild(btnRemove);
    container.appendChild(card);

    // Hover card to pulse highlight element on webpage
    card.addEventListener("mouseenter", () => {
      sendTabMessage({ action: "HIGHLIGHT_REDACTED_ELEMENT", id: item.id });
    });
    card.addEventListener("mouseleave", () => {
      sendTabMessage({ action: "UNHIGHLIGHT_REDACTED_ELEMENT" });
    });
    card.addEventListener("click", () => {
      sendTabMessage({ action: "HIGHLIGHT_REDACTED_ELEMENT", id: item.id });
    });

    // Delete single redaction
    btnRemove.addEventListener("click", (e) => {
      e.stopPropagation();
      sendTabMessage({ action: "REMOVE_REDACTION_BY_ID", id: item.id }, (res) => {
        if (res) {
          const rc = document.getElementById("redact-count");
        if (rc) rc.textContent = res.count || 0;
          renderRedactedList(res.list || []);
          showToast("✓ Đã gỡ bỏ che phần tử!");
        }
      });
    });
  });
}

