// ---------------------------------------------------------------------------
// ScholarFlow module: OS/js/verify.js
// Academic source verifier (Crossref/OpenAlex/arXiv/YouTube) + anti-hallucination
// Extracted from js/sidebar.js (lines 2891-3764) - load order matters.
// Generated by scripts/split/apply_split.ps1 - do not edit line order.
// ---------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// Academic Source Verifier & AI Hallucination Detector (Anti-Hallucination)
// ----------------------------------------------------------------------------
let verifiedResultData = null;

function computeStringSimilarity(str1, str2) {
  if (!str1 || !str2) return 0;
  const normalize = (s) => s.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, "").split(/\s+/).filter(w => w.length > 2);
  const words1 = new Set(normalize(str1));
  const words2 = new Set(normalize(str2));
  if (words1.size === 0 || words2.size === 0) return 0;

  let intersection = 0;
  words1.forEach(w => {
    if (words2.has(w)) intersection++;
  });

  const union = new Set([...words1, ...words2]).size;
  const jaccard = intersection / union;
  const dice = (2 * intersection) / (words1.size + words2.size);
  return (jaccard + dice) / 2;
}

function getVerifyI18n(key, fallback = "", params = null) {
  if (window.i18n && typeof window.i18n.t === "function") {
    const val = window.i18n.t(key, null, params);
    if (val && val !== key) return val;
  }
  let str = fallback || key;
  if (params && typeof params === "object") {
    for (const [k, v] of Object.entries(params)) {
      str = str.split("{" + k + "}").join(v !== undefined && v !== null ? v : "");
    }
  }
  return str;
}

async function verifyAcademicSource(rawText, tabMeta = null) {
  // 1. Extract potential DOI (e.g. 10.1145/... or 10.1038/...)
  const doiRegex = /\b(10\.\d{4,9}\/[-._;()/:A-Za-z0-9]+)\b/i;
  const doiMatch = rawText.match(doiRegex);
  const detectedDoi = doiMatch ? doiMatch[1].replace(/[.,;)]+$/, "") : null;

  // 2. Extract potential arXiv ID (e.g. arXiv:1706.03762 or arxiv.org/abs/1706.03762)
  const arxivRegex = /\b(?:arxiv:\s*|arxiv\.org\/(?:abs|pdf)\/)(\d{4}\.\d{4,5}(?:v\d+)?)\b/i;
  const arxivMatch = rawText.match(arxivRegex);
  const detectedArxiv = arxivMatch ? arxivMatch[1] : null;

  // 3. Extract clean search title from citation string
  let queryTitle = rawText.trim();
  const quoteMatch = rawText.match(/["“]([^"”]{6,180})["”]/);
  if (quoteMatch) {
    queryTitle = quoteMatch[1];
  } else {
    // Strip leading [1], (1), etc.
    queryTitle = queryTitle.replace(/^\[\d+\]\s*/, "").replace(/^\(\d+\)\s*/, "");
    if (detectedDoi) queryTitle = queryTitle.replace(detectedDoi, "");
    queryTitle = queryTitle.replace(/https?:\/\/\S+/g, "");
    // If APA/Harvard format: Author (Year). Title...
    const apaMatch = queryTitle.match(/\((?:19|20)\d{2}[a-z]?\)\.\s*([^.]{8,180})/i);
    if (apaMatch) {
      queryTitle = apaMatch[1];
    } else {
      const parts = queryTitle.split(/[.;\n]/).map(p => p.trim()).filter(p => p.length > 5);
      if (parts.length > 1) {
        queryTitle = parts.reduce((a, b) => b.length > a.length ? b : a, parts[0]);
      }
      if (queryTitle.length < 5 && rawText.length >= 5) {
        queryTitle = rawText.slice(0, 120).trim();
      }
    }
  }
  // Sanitize queryTitle for API: remove special chars, collapse whitespace, limit length
  const sanitizedQuery = queryTitle.replace(/[<>"'{}|\\^`\[\]]/g, " ").replace(/\s+/g, " ").trim().slice(0, 100);

  // --- STRATEGY 0: Live Web / Video / Academic Portal Direct Verification ---
  const urlRegex = /\bhttps?:\/\/[^\s"'<>\)]+/i;
  const urlMatch = rawText.match(urlRegex);
  const detectedUrl = urlMatch ? urlMatch[0].replace(/[.,;)]+$/, "") : null;

  // --- STRATEGY 0X: Fast-path when called from "Dùng trang hiện tại" button ---
  // If tabMeta is passed, we already have the live page data; no CORS fetch needed.
  if (tabMeta && tabMeta.url) {
    const liveUrl = tabMeta.url || "";
    const liveTitle = tabMeta.title || queryTitle;
    const liveAuthors = typeof tabMeta.authors === "string" ? tabMeta.authors : (Array.isArray(tabMeta.authors) ? tabMeta.authors.join(", ") : "");
    const liveDate = tabMeta.date || "";
    const liveContainer = tabMeta.container || "";
    const liveDoi = tabMeta.doi || "";

    // 0X-A: YouTube via oEmbed (always most accurate for YT videos)
    if (liveUrl.includes("youtube.com") || liveUrl.includes("youtu.be")) {
      try {
        const ytRes = await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(liveUrl)}&format=json`, { signal: AbortSignal.timeout(7000) });
        if (ytRes.ok) {
          const ytData = await ytRes.json();
          return {
            status: "VERIFIED",
            confidence: 100,
            isReal: true,
            title: ytData.title || liveTitle,
            authors: ytData.author_name || liveAuthors || getVerifyI18n("verify_author_yt_channel", "Kênh YouTube"),
            year: liveDate ? liveDate.slice(0, 4) : "",
            venue: "YouTube",
            doi: liveUrl,
            realUrl: liveUrl,
            pdfUrl: null,
            reasonKey: "verify_reason_yt_api",
            reasonParams: { channel: ytData.author_name || "YouTube" },
            reason: getVerifyI18n("verify_reason_yt_api", `Video YouTube có thật, xác thực thành công qua API chính thức YouTube. Kênh: ${ytData.author_name || "YouTube"}.`, { channel: ytData.author_name || "YouTube" })
          };
        }
      } catch (e) {
        console.warn("YouTube oEmbed fast-path error:", e);
      }
      // Fallback: use existing meta
      return {
        status: "VERIFIED",
        confidence: 95,
        isReal: true,
        title: liveTitle,
        authors: liveAuthors || "Kênh YouTube",
        year: liveDate ? liveDate.slice(0, 4) : "",
        venue: "YouTube",
        doi: liveUrl,
        realUrl: liveUrl,
        pdfUrl: null,
        reasonKey: "verify_reason_yt_live",
        reasonParams: { url: liveUrl },
        reason: getVerifyI18n("verify_reason_yt_live", `Video YouTube đang mở trực tiếp trên trình duyệt của bạn tại: ${liveUrl}`, { url: liveUrl })
      };
    }

    // 0X-B: DOI-registered academic paper
    if (liveDoi) {
      try {
        const doiRes = await fetch(`https://doi.org/${encodeURIComponent(liveDoi)}`, {
          headers: { "Accept": "application/vnd.citationstyles.csl+json" },
          signal: AbortSignal.timeout(7000)
        });
        if (doiRes.ok) {
          const data = await doiRes.json();
          const verifiedTitle = data.title || liveTitle;
          const authors = (data.author || []).map(a => {
            if (a.name) return normalizeAuthorDisplayName(a.name);
            if (a.family && a.given) {
              const lastLow = removeVietnameseDiacritics(a.family).toLowerCase();
              const isVn = VIETNAMESE_SURNAMES.has(a.family.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastLow);
              return isVn ? `${a.family} ${a.given}`.trim() : `${a.given} ${a.family}`.trim();
            }
            return normalizeAuthorDisplayName(a.family || a.given || "");
          }).filter(Boolean).join(", ");
          const year = data.issued?.["date-parts"]?.[0]?.[0]
            || data["published-print"]?.["date-parts"]?.[0]?.[0]
            || data["published-online"]?.["date-parts"]?.[0]?.[0]
            || data.published?.["date-parts"]?.[0]?.[0]
            || data.created?.["date-parts"]?.[0]?.[0]
            || data.deposited?.["date-parts"]?.[0]?.[0]
            || "";
          const venue = data["container-title"] || data.publisher || liveContainer;
          const realUrl = data.URL || `https://doi.org/${liveDoi}`;
          return {
            status: "VERIFIED",
            confidence: 100,
            isReal: true,
            title: verifiedTitle,
            authors: authors || liveAuthors || getVerifyI18n("verify_author_multiple", "Nhiều tác giả"),
            year: year ? String(year) : "",
            venue: venue || null, // Will be translated at render time
            doi: liveDoi,
            realUrl,
            pdfUrl: null,
            reasonKey: "verify_reason_doi_fast",
            reasonParams: {},
            reason: getVerifyI18n("verify_reason_doi_fast", "Mã DOI đã được đăng ký chính thức trên International DOI Foundation. Bài báo học thuật có thật 100%.")
          };
        }
      } catch (e) {
        console.warn("DOI fast-path error:", e);
      }
    }

    // 0X-C: For news/blog/general websites — instant verify from live tab (no CORS fetch)
    let domainName = "";
    try { domainName = new URL(liveUrl).hostname.replace(/^www\./, ""); } catch (_) { domainName = liveUrl; }

    const year = liveDate ? (liveDate.match(/\b(19\d\d|20\d\d)\b/) || [""])[0] : "";
    return {
      status: "VERIFIED",
      confidence: 96,
      isReal: true,
      title: liveTitle,
      authors: liveAuthors || domainName,
      year,
      venue: liveContainer || domainName,
      doi: "",
      realUrl: liveUrl,
      pdfUrl: null,
      reasonKey: "verify_reason_web",
      reasonParams: { domain: domainName },
      reason: getVerifyI18n("verify_reason_web", `Nguồn này đang được mở trực tiếp trên trình duyệt của bạn và được xác thực là có thật (tên miền: ${domainName}). Đây là trang web/báo chí — không có trong CSDL học thuật Crossref/OpenAlex vì không phải ấn phẩm khoa học.`, { domain: domainName })
    };
  }

  // Strategy 0A: Official YouTube oEmbed Verification (from manual URL input)
  if (detectedUrl && (detectedUrl.includes("youtube.com") || detectedUrl.includes("youtu.be"))) {
    try {
      const ytRes = await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(detectedUrl)}&format=json`, { signal: AbortSignal.timeout(7000) });
      if (ytRes.ok) {
        const ytData = await ytRes.json();
        return {
          status: "VERIFIED",
          confidence: 100,
          isReal: true,
          title: ytData.title || queryTitle,
          authors: ytData.author_name || getVerifyI18n("verify_author_yt_channel", "Kênh YouTube"),
          year: "",
          venue: "YouTube",
          doi: detectedUrl,
          realUrl: detectedUrl,
          pdfUrl: null,
          reasonKey: "verify_reason_yt_manual",
          reasonParams: { channel: ytData.author_name || "YouTube" },
          reason: getVerifyI18n("verify_reason_yt_manual", `Nguồn video YouTube có thật 100%! Đã xác thực thành công từ máy chủ YouTube (Kênh chính thức: ${ytData.author_name || "YouTube"}).`, { channel: ytData.author_name || "YouTube" })
        };
      }
    } catch (e) {
      console.warn("YouTube oEmbed verification error:", e);
    }
  }

  if (detectedUrl) {
    try {
      const pageRes = await fetch(detectedUrl, { mode: "cors", signal: AbortSignal.timeout(6000) });
      if (pageRes.ok) {
        const html = await pageRes.text();
        const doc = new DOMParser().parseFromString(html, "text/html");

        const getMeta = (...names) => {
          for (const n of names) {
            const el = doc.querySelector(`meta[name="${n}" i], meta[property="${n}" i]`);
            if (el && el.getAttribute("content")) return el.getAttribute("content").trim();
          }
          return "";
        };

        const pageTitleMeta = getMeta(
          "citation_title",
          "DC.Title",
          "DC.title",
          "og:title",
          "twitter:title"
        ) || (doc.title ? doc.title.replace(/\s*[|\-–—].*$/, "").trim() : "");

        const pageAuthors = Array.from(doc.querySelectorAll('meta[name="citation_author" i], meta[name="DC.Creator.PersonalName" i], meta[name="DC.Creator" i]'))
          .map(el => normalizeAuthorDisplayName(el.getAttribute("content")?.trim()))
          .filter(Boolean)
          .join(", ") || normalizeAuthorDisplayName(getMeta("author"));

        const pageJournal = getMeta(
          "citation_journal_title",
          "DC.Source",
          "citation_publisher",
          "DC.Publisher",
          "og:site_name"
        );

        const pageDate = getMeta(
          "citation_date",
          "DC.Date.issued",
          "DC.Date.created",
          "article:published_time"
        );

        let pageYear = "";
        if (pageDate) {
          const ym = pageDate.match(/\b(19\d\d|20\d\d)\b/);
          if (ym) pageYear = ym[1];
        }

        const pagePdf = getMeta("citation_pdf_url") || "";
        const pageDoi = getMeta("citation_doi", "DC.Identifier.DOI");
        let domainName = "";
        try { domainName = new URL(detectedUrl).hostname; } catch (e) { domainName = detectedUrl; }

        if (pageTitleMeta && pageTitleMeta.length >= 5) {
          const sim = computeStringSimilarity(queryTitle, pageTitleMeta);
          const isAcademicMeta = !!(getMeta("citation_title") || getMeta("DC.Source") || getMeta("citation_journal_title") || pagePdf);

          if (sim >= 0.40 || isAcademicMeta || queryTitle.length < 10) {
            return {
              status: "VERIFIED",
              confidence: sim >= 0.6 || isAcademicMeta ? 100 : 92,
              isReal: true,
              title: pageTitleMeta,
              authors: pageAuthors || getVerifyI18n("verify_author_source", "Tác giả công bố tại nguồn"),
              year: pageYear || "",
              venue: pageJournal || domainName,
              doi: pageDoi || detectedUrl,
              realUrl: detectedUrl,
              pdfUrl: pagePdf || null,
              reasonKey: "verify_reason_direct_url",
              reasonParams: { domain: domainName },
              reason: getVerifyI18n("verify_reason_direct_url", `Nguồn có thật 100%! Đã truy cập thành công và xác thực dữ liệu bài báo từ máy chủ (${domainName}).`, { domain: domainName })
            };
          }
        }
      }
    } catch (e) {
      console.warn("Direct URL verification error:", e);
    }
  }

  // --- STRATEGY 1: Verified by DOI ---
  if (detectedDoi) {
    try {
      const doiRes = await fetch(`https://doi.org/${encodeURIComponent(detectedDoi)}`, {
        headers: { "Accept": "application/vnd.citationstyles.csl+json" }
      });
      if (doiRes.ok) {
        const data = await doiRes.json();
        const verifiedTitle = data.title || queryTitle;
        const authors = (data.author || []).map(a => {
          if (a.name) return normalizeAuthorDisplayName(a.name);
          if (a.family && a.given) {
            const lastLow = removeVietnameseDiacritics(a.family).toLowerCase();
            const isVn = VIETNAMESE_SURNAMES.has(a.family.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastLow);
            return isVn ? `${a.family} ${a.given}`.trim() : `${a.given} ${a.family}`.trim();
          }
          return normalizeAuthorDisplayName(a.family || a.given || "");
        }).filter(Boolean).join(", ");
        const year = data.issued?.["date-parts"]?.[0]?.[0] || data.created?.["date-parts"]?.[0]?.[0] || "";
        const venue = data["container-title"] || data.publisher || "";
        const realUrl = data.URL || `https://doi.org/${detectedDoi}`;

        return {
          status: "VERIFIED",
          confidence: 100,
          isReal: true,
          title: verifiedTitle,
          authors: authors || getVerifyI18n("verify_author_multiple", "Nhiều tác giả"),
          year: year ? String(year) : "",
          venue: venue || null, // Will be translated at render time
          doi: detectedDoi,
          realUrl,
          pdfUrl: null,
          reasonKey: "verify_reason_doi",
          reasonParams: {},
          reason: getVerifyI18n("verify_reason_doi", "Mã DOI này đã được cấp phép và đăng ký chính thức trên cơ sở dữ liệu học thuật quốc tế (International DOI Foundation).")
        };
      }
    } catch (e) {
      console.warn("DOI lookup error:", e);
    }
  }

  // --- STRATEGY 2: Verified by arXiv ---
  if (detectedArxiv) {
    try {
      const axRes = await fetch(`https://export.arxiv.org/api/query?id_list=${encodeURIComponent(detectedArxiv)}`);
      if (axRes.ok) {
        const xmlText = await axRes.text();
        const parser = new DOMParser();
        const xmlDoc = parser.parseFromString(xmlText, "text/xml");
        const entry = xmlDoc.querySelector("entry");
        if (entry) {
          const entryTitle = entry.querySelector("title")?.textContent?.replace(/\s+/g, " ").trim() || "";
          const entryAuthors = Array.from(entry.querySelectorAll("author name")).map(n => n.textContent.trim()).join("; ");
          const published = entry.querySelector("published")?.textContent || "";
          const year = published.slice(0, 4);
          const pdfLink = `https://arxiv.org/pdf/${detectedArxiv}.pdf`;
          const realUrl = `https://arxiv.org/abs/${detectedArxiv}`;

          return {
            status: "VERIFIED",
            confidence: 98,
            isReal: true,
            title: entryTitle,
            authors: entryAuthors || "Nhiều tác giả",
            year,
            venue: `arXiv (${detectedArxiv})`,
            doi: `arXiv:${detectedArxiv}`,
            realUrl,
            pdfUrl: pdfLink,
            reasonKey: "verify_reason_arxiv",
            reasonParams: {},
            reason: getVerifyI18n("verify_reason_arxiv", "Bài báo này đã được kiểm chứng và lưu trữ chính thức trên kho học thuật mở toàn cầu arXiv.")
          };
        }
      }
    } catch (e) {
      console.warn("arXiv lookup error:", e);
    }
  }

  // --- STRATEGY 3: OpenAlex Global Registry (250M+ works) ---
  if (sanitizedQuery && sanitizedQuery.length >= 6) {
    try {
      const oaRes = await fetch(`https://api.openalex.org/works?filter=title.search:${encodeURIComponent(sanitizedQuery)}&per-page=3`, { signal: AbortSignal.timeout(5000) });
      if (oaRes.ok) {
        const oaData = await oaRes.json();
        const results = oaData.results || [];
        if (results.length > 0) {
          const best = results[0];
          const bestTitle = best.title || "";
          const similarity = computeStringSimilarity(queryTitle, bestTitle);

          if (similarity >= 0.70) {
            const authors = (best.authorships || []).map(a => normalizeAuthorDisplayName(a.author?.display_name)).filter(Boolean).join(", ");
            const year = best.publication_year ? String(best.publication_year) : "";
            const venue = best.primary_location?.source?.display_name || "";
            const doi = best.doi ? best.doi.replace("https://doi.org/", "") : "";
            const realUrl = best.doi || best.primary_location?.landing_page_url || (doi ? `https://doi.org/${doi}` : "");
            const pdfUrl = best.open_access?.oa_url || null;
            const citedCount = typeof best.cited_by_count === "number" ? best.cited_by_count : 0;
            const isOa = !!best.open_access?.is_oa;
            const typeKey = best.type === "journal-article" ? "verify_type_journal" : (best.type === "proceedings-article" ? "verify_type_proceedings" : (best.type === "book-chapter" ? "verify_type_book_chapter" : (best.type === "dissertation" ? "verify_type_dissertation" : "verify_type_academic")));
            const typeStr = getVerifyI18n(typeKey, "Ấn phẩm học thuật");

            let reasonDetail = "";
            let reasonKey = "";
            let reasonParams = {};
            if (similarity >= 0.82) {
              reasonKey = "verify_reason_openalex_exact";
              reasonParams = { type: typeStr };
              const details = [];
              details.push(getVerifyI18n("verify_reason_openalex_exact", `Xác thực thành công trên mạng lưới học thuật toàn cầu OpenAlex (${typeStr}).`, { type: typeStr }));
              if (venue) {
                details.push(getVerifyI18n("verify_detail_venue", `Xuất bản tại: ${venue}${year ? ` (${year})` : ""}.`, { venue: `${venue}${year ? ` (${year})` : ""}` }));
              } else if (year) {
                details.push(getVerifyI18n("verify_detail_year", `Năm công bố: ${year}.`, { year }));
              }
              if (citedCount > 0) {
                details.push(getVerifyI18n("verify_detail_citations", `Đã có ${citedCount.toLocaleString()} lượt trích dẫn khoa học.`, { count: citedCount.toLocaleString() }));
              }
              if (isOa) {
                details.push(getVerifyI18n("verify_detail_oa", "Tài liệu mở tự do (Open Access)."));
              }
              reasonDetail = details.join(" ");
            } else {
              reasonKey = "verify_reason_openalex_partial";
              reasonParams = { percent: Math.round(similarity * 100), venue: venue ? ` (${venue})` : "" };
              reasonDetail = getVerifyI18n("verify_reason_openalex_partial", `Tìm thấy bài báo có tiêu đề tương tự (${Math.round(similarity * 100)}% trùng khớp)${venue ? ` tại ${venue}` : ""}. Vui lòng đối soát lại tên tác giả hoặc năm công bố để đảm bảo chuẩn xác.`, reasonParams);
            }

            return {
              status: similarity >= 0.82 ? "VERIFIED" : "PARTIAL",
              confidence: Math.round(similarity * 100),
              isReal: true,
              title: bestTitle,
              authors: authors || getVerifyI18n("verify_author_unknown", "Không rõ tác giả"),
              year,
              venue: venue || getVerifyI18n("verify_venue_journal_conf", "Tạp chí / Hội nghị học thuật"),
              doi,
              realUrl,
              pdfUrl,
              citedCount,
              isOa,
              typeKey,
              reasonKey,
              reasonParams,
              reason: reasonDetail
            };
          }
        }
      }
    } catch (e) {
      console.warn("OpenAlex lookup error:", e);
    }

    // --- STRATEGY 4: Crossref Bibliographic Database (150M+ works) ---
    try {
      const crRes = await fetch(`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(sanitizedQuery)}&rows=3`, { signal: AbortSignal.timeout(5000) });
      if (crRes.ok) {
        const crData = await crRes.json();
        const items = crData.message?.items || [];
        if (items.length > 0) {
          const best = items[0];
          const bestTitle = (best.title && best.title[0]) ? best.title[0] : "";
          const similarity = computeStringSimilarity(queryTitle, bestTitle);

          if (similarity >= 0.65) {
            const authors = (best.author || []).map(a => {
              if (a.name) return normalizeAuthorDisplayName(a.name);
              if (a.family && a.given) {
                const lastLow = removeVietnameseDiacritics(a.family).toLowerCase();
                const isVn = VIETNAMESE_SURNAMES.has(a.family.toLowerCase()) || VIETNAMESE_SURNAMES.has(lastLow);
                return isVn ? `${a.family} ${a.given}`.trim() : `${a.given} ${a.family}`.trim();
              }
              return normalizeAuthorDisplayName(a.family || a.given || "");
            }).filter(Boolean).join(", ");
            const year = best.issued?.["date-parts"]?.[0]?.[0]
              || best["published-print"]?.["date-parts"]?.[0]?.[0]
              || best["published-online"]?.["date-parts"]?.[0]?.[0]
              || best.published?.["date-parts"]?.[0]?.[0]
              || best.created?.["date-parts"]?.[0]?.[0]
              || best.deposited?.["date-parts"]?.[0]?.[0]
              || "";
            const venue = (best["container-title"] && best["container-title"][0]) ? best["container-title"][0] : best.publisher || "";
            const doi = best.DOI || "";
            const realUrl = best.URL || (doi ? `https://doi.org/${doi}` : "");
            const citedCount = typeof best["is-referenced-by-count"] === "number" ? best["is-referenced-by-count"] : 0;
            const typeKey = best.type === "journal-article" ? "verify_type_journal" : (best.type === "proceedings-article" ? "verify_type_proceedings" : (best.type === "book-chapter" ? "verify_type_book_chapter" : "verify_type_intl"));
            const typeStr = getVerifyI18n(typeKey, "Ấn phẩm quốc tế");

            let reasonDetail = "";
            let reasonKey = "";
            let reasonParams = {};
            if (similarity >= 0.80) {
              reasonKey = "verify_reason_crossref_exact";
              reasonParams = { type: typeStr };
              const details = [];
              details.push(getVerifyI18n("verify_reason_crossref_exact", `Xác thực thành công trong cơ sở dữ liệu xuất bản quốc tế Crossref (${typeStr}).`, { type: typeStr }));
              if (venue) {
                details.push(getVerifyI18n("verify_detail_venue", `Nhà xuất bản / Tạp chí: ${venue}${year ? ` (${year})` : ""}.`, { venue: `${venue}${year ? ` (${year})` : ""}` }));
              } else if (year) {
                details.push(getVerifyI18n("verify_detail_year", `Năm công bố: ${year}.`, { year }));
              }
              if (citedCount > 0) {
                details.push(getVerifyI18n("verify_detail_citations", `Đã có ${citedCount.toLocaleString()} lượt trích dẫn ghi nhận.`, { count: citedCount.toLocaleString() }));
              }
              reasonDetail = details.join(" ");
            } else {
              reasonKey = "verify_reason_crossref_partial";
              reasonParams = { percent: Math.round(similarity * 100), venue: venue || "Crossref" };
              reasonDetail = getVerifyI18n("verify_reason_crossref_partial", `Tìm thấy tài liệu có tiêu đề tương tự (${Math.round(similarity * 100)}% trùng khớp) tại ${venue || "Crossref"}. Cần đối chiếu lại thông tin tác giả và năm xuất bản.`, reasonParams);
            }

            return {
              status: similarity >= 0.80 ? "VERIFIED" : "PARTIAL",
              confidence: Math.round(similarity * 100),
              isReal: true,
              title: bestTitle,
              authors: authors || getVerifyI18n("verify_author_unknown", "Không rõ tác giả"),
              year: year ? String(year) : "",
              venue: venue || getVerifyI18n("verify_venue_conf_publisher", "Hội thảo / Nhà xuất bản học thuật"),
              doi,
              realUrl,
              pdfUrl: null,
              citedCount,
              typeKey,
              reasonKey,
              reasonParams,
              reason: reasonDetail
            };
          }
        }
      }
    } catch (e) {
      console.warn("Crossref lookup error:", e);
    }
  }

  // --- STRATEGY 5: Not Found in International Repositories ---
  return {
    status: "NOT_FOUND",
    confidence: 20,
    isReal: false,
    title: queryTitle,
    authors: "",
    year: "",
    venue: "",
    doi: "",
    realUrl: "",
    pdfUrl: null,
    reasonKey: "verify_reason_not_found",
    reasonParams: {},
    reason: getVerifyI18n("verify_reason_not_found", "Chưa tìm thấy bản ghi trùng khớp trên cơ sở dữ liệu quốc tế (Crossref & OpenAlex). Đây có thể là tài liệu nội bộ, kỷ yếu chưa cấp chỉ số DOI quốc tế, hoặc trích dẫn nhân tạo do mô hình AI tự sinh. Bạn có thể bấm 'Google Scholar' bên dưới để đối soát thực tế.")
  };
}

async function handleVerifySource(forcedText = null, tabMeta = null) {
  const inputEl = document.getElementById("verify-input");
  const text = (typeof forcedText === "string" ? forcedText : (inputEl ? inputEl.value : "")).trim();
  if (!text) {
    showToast(getVerifyI18n("verify_toast_empty", "Vui lòng dán trích dẫn, tên bài báo hoặc mã DOI cần đối soát!"));
    return;
  }
  if (inputEl && typeof forcedText === "string") {
    inputEl.value = forcedText;
  }

  const resultBox = document.getElementById("verify-result-box");
  const statusTitle = document.getElementById("verify-status-title");
  const confBadge = document.getElementById("verify-confidence-badge");
  const statusDesc = document.getElementById("verify-status-desc");
  const detailsBox = document.getElementById("verify-matched-details");
  const btnReal = document.getElementById("btn-open-real-source");
  const btnPdf = document.getElementById("btn-open-oa-pdf");
  const btnApply = document.getElementById("btn-apply-verified-to-form");

  if (resultBox) resultBox.style.display = "block";
  if (detailsBox) detailsBox.style.display = "none";
  if (btnReal) btnReal.style.display = "none";
  if (btnPdf) btnPdf.style.display = "none";
  if (btnApply) btnApply.style.display = "none";

  if (statusTitle) {
    statusTitle.textContent = getVerifyI18n("verify_loading_title", "Đang tra cứu trên mạng lưới học thuật quốc tế...");
    statusTitle.style.color = "#38bdf8";
  }
  if (confBadge) {
    confBadge.textContent = getVerifyI18n("verify_loading_badge", "Đang đối soát");
    confBadge.style.color = "#38bdf8";
    confBadge.style.borderColor = "rgba(56, 189, 248, 0.4)";
    confBadge.style.background = "rgba(56, 189, 248, 0.1)";
  }
  if (statusDesc) {
    statusDesc.textContent = getVerifyI18n("verify_loading_desc", "Đang đối soát thông tin qua Crossref (150M+ tài liệu), DOI Foundation và OpenAlex...");
  }

  try {
    const res = await verifyAcademicSource(text, tabMeta);
    renderVerifyResult(res, text);
  } catch (err) {
    console.error("verifyAcademicSource error:", err); showToast("err_003", "error");
    if (statusTitle) {
      statusTitle.textContent = getVerifyI18n("verify_err_title", "Lỗi khi kết nối mạng lưới học thuật");
      statusTitle.style.color = "#f59e0b";
    }
    if (statusDesc) {
      statusDesc.textContent = getVerifyI18n("verify_err_desc", "Không thể kết nối máy chủ xác minh. Hãy kiểm tra kết nối mạng hoặc thử lại với tên bài báo ngắn gọn hơn.");
    }
    if (confBadge) confBadge.textContent = getVerifyI18n("verify_err_badge", "Lỗi mạng");
  }
}

function renderVerifyResult(result, originalQuery) {
  verifiedResultData = result;

  const resultBox = document.getElementById("verify-result-box");
  const statusTitle = document.getElementById("verify-status-title");
  const confBadge = document.getElementById("verify-confidence-badge");
  const statusDesc = document.getElementById("verify-status-desc");
  const detailsBox = document.getElementById("verify-matched-details");

  const matchedTitle = document.getElementById("verify-matched-title");
  const matchedAuthors = document.getElementById("verify-matched-authors");
  const matchedVenue = document.getElementById("verify-matched-venue");
  const matchedDoi = document.getElementById("verify-matched-doi");

  const btnReal = document.getElementById("btn-open-real-source");
  const btnPdf = document.getElementById("btn-open-oa-pdf");
  const btnScholar = document.getElementById("btn-open-scholar");
  const btnCrossref = document.getElementById("btn-open-crossref");
  const btnApply = document.getElementById("btn-apply-verified-to-form");

  if (!resultBox) return;
  resultBox.style.display = "block";

  // Dynamic translated reason calculation
  let dynamicReason = result.reason || "";
  if (result.reasonKey === "verify_reason_openalex_exact" || result.reasonKey === "verify_reason_crossref_exact") {
    const typeStr = getVerifyI18n(result.typeKey || "verify_type_academic", "Ấn phẩm học thuật");
    const details = [];
    details.push(getVerifyI18n(result.reasonKey, "", { type: typeStr }));
    if (result.venue) {
      details.push(getVerifyI18n("verify_detail_venue", "", { venue: `${result.venue}${result.year ? ` (${result.year})` : ""}` }));
    } else if (result.year) {
      details.push(getVerifyI18n("verify_detail_year", "", { year: result.year }));
    }
    if (result.citedCount > 0) {
      details.push(getVerifyI18n("verify_detail_citations", "", { count: result.citedCount.toLocaleString() }));
    }
    if (result.isOa) {
      details.push(getVerifyI18n("verify_detail_oa", ""));
    }
    dynamicReason = details.filter(Boolean).join(" ");
  } else if (result.reasonKey) {
    dynamicReason = getVerifyI18n(result.reasonKey, result.reason, result.reasonParams || {});
  }

  if (result.status === "VERIFIED") {
    if (statusTitle) {
      statusTitle.textContent = getVerifyI18n("verify_badge_exact", "✓ Đã xác thực – Nguồn học thuật có thật");
      statusTitle.style.color = "#10b981";
    }
    if (confBadge) {
      confBadge.textContent = `${result.confidence}% (100%)`;
      confBadge.style.color = "#10b981";
      confBadge.style.borderColor = "rgba(16, 185, 129, 0.45)";
      confBadge.style.background = "rgba(16, 185, 129, 0.12)";
    }
    if (statusDesc) statusDesc.textContent = dynamicReason;
  } else if (result.status === "PARTIAL") {
    if (statusTitle) {
      statusTitle.textContent = getVerifyI18n("verify_badge_partial", "Trùng khớp một phần – Cần kiểm tra chi tiết");
      statusTitle.style.color = "#f59e0b";
    }
    if (confBadge) {
      confBadge.textContent = `${result.confidence}%`;
      confBadge.style.color = "#f59e0b";
      confBadge.style.borderColor = "rgba(245, 158, 11, 0.45)";
      confBadge.style.background = "rgba(245, 158, 11, 0.12)";
    }
    if (statusDesc) statusDesc.textContent = dynamicReason;
  } else {
    if (statusTitle) {
      statusTitle.textContent = getVerifyI18n("verify_badge_notfound", "Chưa tìm thấy trong CSDL quốc tế");
      statusTitle.style.color = "#ef4444";
    }
    if (confBadge) {
      confBadge.textContent = getVerifyI18n("verify_status_idle", "Chưa xác minh");
      confBadge.style.color = "#ef4444";
      confBadge.style.borderColor = "rgba(239, 68, 68, 0.45)";
      confBadge.style.background = "rgba(239, 68, 68, 0.12)";
    }
    if (statusDesc) statusDesc.textContent = dynamicReason;
  }

  // Show details box if real paper was found
  if (result.isReal && result.title && detailsBox) {
    detailsBox.style.display = "block";
    if (matchedTitle) matchedTitle.textContent = result.title;
    
    const authorPrefix = getVerifyI18n("verify_label_author", "Tác giả: ");
    const venuePrefix = getVerifyI18n("verify_label_venue", "Nơi XB: ");
    const unknownAuthor = getVerifyI18n("verify_author_unknown", "Không rõ");
    const intlVenue = getVerifyI18n("verify_venue_intl", "Ấn phẩm học thuật");
    const citeSuffix = getVerifyI18n("verify_label_citations_suffix", "lượt trích dẫn");
    const inDb = getVerifyI18n("verify_doi_in_db", "Có trong cơ sở dữ liệu");

    if (matchedAuthors) matchedAuthors.textContent = `${authorPrefix}${result.authors || unknownAuthor}`;
    if (matchedVenue) {
      let vText = `${venuePrefix}${(result.venue && result.venue !== "null") ? result.venue : intlVenue} ${result.year ? "(" + result.year + ")" : ""}`;
      if (result.citedCount) {
        vText += ` • ${result.citedCount.toLocaleString()} ${citeSuffix}`;
      }
      if (result.isOa) {
        vText += ` • Open Access`;
      }
      matchedVenue.textContent = vText;
    }
    if (matchedDoi) matchedDoi.textContent = `DOI / ID: ${result.doi || result.realUrl || inDb}`;
  } else if (detailsBox) {
    detailsBox.style.display = "none";
  }

  // 1. Direct Real Source Button
  if (result.isReal && result.realUrl && btnReal) {
    btnReal.style.display = "block";
    btnReal.onclick = () => {
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi?.create) tabsApi.create({ url: result.realUrl });
      else window.open(result.realUrl, "_blank");
    };
  } else if (btnReal) {
    btnReal.style.display = "none";
  }

  // 2. Open Access PDF Button
  if (result.pdfUrl && btnPdf) {
    btnPdf.style.display = "block";
    btnPdf.onclick = () => {
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi?.create) tabsApi.create({ url: result.pdfUrl });
      else window.open(result.pdfUrl, "_blank");
    };
  } else if (btnPdf) {
    btnPdf.style.display = "none";
  }

  // 3. Search Fallback Buttons
  const searchQuery = (result.isReal && result.title) ? result.title : originalQuery;
  const btnGoogle = document.getElementById("btn-open-google");
  if (btnGoogle) {
    btnGoogle.onclick = () => {
      const gUrl = `https://www.google.com/search?q=${encodeURIComponent(searchQuery)}`;
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi?.create) tabsApi.create({ url: gUrl });
      else window.open(gUrl, "_blank");
    };
  }
  if (btnScholar) {
    btnScholar.onclick = () => {
      const sUrl = `https://scholar.google.com/scholar?q=${encodeURIComponent(searchQuery)}`;
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi?.create) tabsApi.create({ url: sUrl });
      else window.open(sUrl, "_blank");
    };
  }
  if (btnCrossref) {
    btnCrossref.onclick = () => {
      const crUrl = `https://search.crossref.org/?q=${encodeURIComponent(searchQuery)}`;
      const tabsApi = (typeof browser !== "undefined" && browser.tabs) ? browser.tabs : (typeof chrome !== "undefined" ? chrome.tabs : null);
      if (tabsApi?.create) tabsApi.create({ url: crUrl });
      else window.open(crUrl, "_blank");
    };
  }

  // 4. Apply to Citation form
  if (result.isReal && result.title && btnApply) {
    btnApply.style.display = "block";
    btnApply.onclick = () => {
      if (result.title) document.getElementById("f-title").value = result.title;
      if (result.authors) document.getElementById("f-authors").value = normalizeAuthorsString(result.authors);
      if (result.year) document.getElementById("f-date").value = result.year;
      if (result.venue) document.getElementById("f-container").value = result.venue;
      if (result.doi) document.getElementById("f-doi").value = result.doi;
      if (result.realUrl) document.getElementById("f-url").value = result.realUrl;
      document.getElementById("f-source-type").value = "academic";
      syncMetaFromInputs();
      showToast(getVerifyI18n("verify_toast_applied", "✔ Đã áp dụng thông tin bài báo chuẩn xác vào tiện ích!"));
    };
  } else if (btnApply) {
    btnApply.style.display = "none";
  }
}

function initSourceVerifier() {
  const verifyInput = document.getElementById("verify-input");
  const clearBtn = document.getElementById("btn-clear-verify-input");
  const pasteBtn = document.getElementById("btn-paste-verify");
  const currPageBtn = document.getElementById("btn-use-current-page-verify");
  const runBtn = document.getElementById("btn-run-verify");

  if (verifyInput && clearBtn) {
    verifyInput.addEventListener("input", () => {
      clearBtn.style.display = verifyInput.value ? "block" : "none";
    });
    clearBtn.addEventListener("click", () => {
      verifyInput.value = "";
      clearBtn.style.display = "none";
      const resBox = document.getElementById("verify-result-box");
      if (resBox) resBox.style.display = "none";
    });
    verifyInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        handleVerifySource();
      }
    });
  }

  pasteBtn?.addEventListener("click", async () => {
    try {
      const text = await navigator.clipboard.readText();
      if (text && text.trim()) {
        if (verifyInput) {
          verifyInput.value = text.trim();
          if (clearBtn) clearBtn.style.display = "block";
        }
        handleVerifySource(text.trim());
      } else {
        showToast("📋 Bộ nhớ tạm (Clipboard) đang trống!");
      }
    } catch (e) {
      showToast("💡 Hãy bấm phím Ctrl+V vào ô để dán!");
    }
  });

  currPageBtn?.addEventListener("click", () => {
    // Prefer URL first (oEmbed/DOI/direct verify), fallback to title
    const text = currentMeta.doi
      ? currentMeta.doi
      : (currentMeta.url && !currentMeta.url.startsWith("file://")
          ? currentMeta.url
          : (currentMeta.title || ""));
    if (text && text.trim()) {
      if (verifyInput) {
        verifyInput.value = text.trim();
        if (clearBtn) clearBtn.style.display = "block";
      }
      handleVerifySource(text.trim(), currentMeta);
    } else {
      showToast("Chưa nhận diện được tiêu đề hoặc URL trang hiện tại!");
    }
  });

  runBtn?.addEventListener("click", () => {
    handleVerifySource();
  });
}

